Repository apache/mxnet, pull requests merged in 2018-11, with the labels that each got.

#12331 Moves f16c autodetection to its own cmake module
  CMakeLists.txt
  cmake/AutoDetectF16C.cmake
Labels: pr-awaiting-review

#12878 ONNX export: Cleanup
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/mx2onnx/export_onnx.py
Labels: ONNX, pr-work-in-progress

#13081 Maven Surefire bug workaround
  scala-package/pom.xml
Labels: Build, Scala, pr-awaiting-review

#12998 remove legacy installation of Roxygen2 5.0 and add R-specific clean target (#12993)
  Makefile
  R-package/.Rbuildignore
  R-package/DESCRIPTION
  R-package/R/zzz.R
  R-package/dummy.NAMESPACE
Labels: R, pr-awaiting-response

#13056 Gluon LSTM Projection and Clipping
  ci/docker/runtime_functions.sh
  python/mxnet/gluon/rnn/rnn_layer.py
  python/mxnet/test_utils.py
  src/operator/cudnn_rnn-inl.h
  src/operator/nn/concat.cc
  src/operator/rnn-inl.h
  src/operator/rnn.cu
  tests/python/gpu/test_gluon_gpu.py
  tests/python/gpu/test_operator_gpu.py
  tests/python/unittest/common.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_gluon_rnn.py
  tests/python/unittest/test_operator.py
Labels: Gluon, pr-awaiting-testing

#13082 Fix Scala README
  scala-package/README.md
Labels: Doc, Scala, pr-awaiting-review

#12995 [MXNET-1180] Scala Image API
  scala-package/core/src/main/scala/org/apache/mxnet/Image.scala
  scala-package/core/src/test/scala/org/apache/mxnet/ImageSuite.scala
Labels: Scala, pr-awaiting-review

#13065 [MXNET-793] Virtual testing with Qemu, refinement and extract test results to root MXNet folder
  ci/README.md
  ci/docker/Dockerfile.build.test.arm_qemu
  ci/docker/install/ubuntu_arm_qemu.sh
  ci/docker/qemu/ansible.cfg
  ci/docker/qemu/playbook.yml
  ci/docker/qemu/qemu_run.sh
  ci/docker/qemu/runtime_functions.py
  ci/docker/qemu/vmcontrol.py
Labels: CI, pr-awaiting-review

#12968 Updated / Deleted some examples
  ci/docker/runtime_functions.sh
  example/multivariate_time_series/README.md
  example/named_entity_recognition/README.md
  example/named_entity_recognition/src/metrics.py
  example/named_entity_recognition/src/ner.py
  example/nce-loss/README.md
  example/numpy-ops/numpy_softmax.py
  example/onnx/super_resolution.py
  example/python-howto/README.md
  example/python-howto/data_iter.py
  example/python-howto/debug_conv.py
  example/python-howto/monitor_weights.py
  example/python-howto/multiple_outputs.py
  example/vae-gan/README.md
  example/vae-gan/convert_data.py
  example/vae-gan/vaegan_mxnet.py
  tests/python-pytest/onnx/import/onnx_import_test.py
Labels: Example, pr-awaiting-merge

#13052 Fix incorrect variable name in tutorial code
  docs/tutorials/scala/char_lstm.md
Labels: Scala, pr-awaiting-review

#12997 A better take forward kernel for CPU
  src/operator/tensor/indexing_op.cc
  src/operator/tensor/indexing_op.cu
  src/operator/tensor/indexing_op.h
Labels: Operator, pr-awaiting-review

#13067 ONNX export: Scalar, Reshape - Set appropriate tensor type …
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
Labels: ONNX, pr-awaiting-review

#12954 Fix example for mxnet.nd.contrib.cond and fix typo in src/engine
  python/mxnet/ndarray/contrib.py
  src/engine/engine.cc
  src/engine/threaded_engine.h
Labels: pr-awaiting-merge

#12881 Improve the Clojure Package README to Make it Easier to Get Started
  contrib/clojure-package/README.md
Labels: Clojure

#13038 [MXNET-918] Introduce Random module / Refact code generation
  scala-package/macros/src/main/scala/org/apache/mxnet/APIDocGenerator.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/GeneratorBase.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/NDArrayMacro.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/SymbolMacro.scala
Labels: Scala, pr-awaiting-review

#13115 Fix a typo in operator guide
  docs/faq/add_op_in_backend.md
Labels: Doc, Operator, pr-awaiting-review

#12999 [Issue #11912] throw mxnet exceptions when decoding invalid images.
  python/mxnet/image/image.py
  src/io/image_io.cc
  tests/python/unittest/test_image.py
Labels: Data-loading, pr-awaiting-review

#12918 Update adversary attack generation example
  example/adversary/README.md
  example/adversary/adversary_generation.ipynb
  python/mxnet/test_utils.py
Labels: pr-awaiting-review

#13137 Disable travis tests
  .travis.yml
Labels: pr-awaiting-merge

#12951 Update Gluon example folder
  docs/tutorials/unsupervised_learning/gan.md
  example/gluon/actor_critic/actor_critic.py
  example/gluon/dc_gan/README.md
  example/gluon/dc_gan/__init__.py
  example/gluon/dc_gan/dcgan.py
  example/gluon/dc_gan/inception_score.py
  example/gluon/house_prices/kaggle_k_fold_cross_validation.py
  example/gluon/learning_rate_manipulation.py
  example/gluon/lstm_crf/lstm_crf.py
  example/gluon/mnist/mnist.py
  example/gluon/sn_gan/data.py
  example/gluon/sn_gan/model.py
  example/gluon/sn_gan/train.py
  example/gluon/sn_gan/utils.py
  example/gluon/super_resolution/super_resolution.py
  example/notebooks/README.md
Labels: pr-awaiting-review

#13049 Document the newly added env variable
  docs/faq/env_var.md
Labels: Doc, pr-awaiting-review

#13092 [MXNET-1193] Fix Docker Cleanup Race Condition
  ci/build.py
Labels: Docker, pr-awaiting-review

#12784 Improved git reset for CI builds
  ci/Jenkinsfile_utils.groovy
Labels: CI, pr-work-in-progress

#13117 Infer dtype in SymbolBlock import from input symbol (v1.3.x)
  python/mxnet/gluon/block.py
  python/mxnet/gluon/parameter.py
  tests/python/gpu/test_gluon_gpu.py
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-merge

#13118 [MXNET-953] Fix oob memory read (v1.3.x)
  src/operator/tensor/elemwise_unary_op_basic.cc
Labels: pr-awaiting-merge

#13119 [MXNET-969] Fix buffer overflow in RNNOp (v1.3.x)
  src/operator/rnn-inl.h
Labels: pr-awaiting-merge

#13120 [MXNET-922] Fix memleak in profiler (v1.3.x)
  src/profiler/profiler.cc
  src/profiler/profiler.h
Labels: pr-awaiting-merge

#13121 Set correct update on kvstore flag in dist_device_sync mode (v1.3.x)
  python/mxnet/gluon/trainer.py
  tests/nightly/dist_device_sync_kvstore.py
Labels: pr-awaiting-merge

#13123 CudnnFind() usage improvements (v1.3.x)
  CONTRIBUTORS.md
  docs/faq/env_var.md
  include/mxnet/base.h
  include/mxnet/c_api.h
  perl-package/AI-MXNetCAPI/mxnet.i
  python/mxnet/context.py
  src/c_api/c_api.cc
  src/operator/nn/cudnn/cudnn_algoreg-inl.h
  src/operator/nn/cudnn/cudnn_convolution-inl.h
  src/operator/nn/cudnn/cudnn_deconvolution-inl.h
  src/storage/pooled_storage_manager.h
  tests/python/gpu/test_gluon_gpu.py
Labels: pr-awaiting-merge

#13124 Fix lazy record io when used with dataloader and multi_worker > 0 (v1.3.x)
  python/mxnet/gluon/data/dataloader.py
  python/mxnet/gluon/data/dataset.py
  tests/python/unittest/test_gluon_data.py
Labels: pr-awaiting-merge

#13129 Gluon LSTM Projection and Clipping Support (#13055) v1.3.x
  ci/docker/runtime_functions.sh
  python/mxnet/gluon/rnn/rnn_layer.py
  python/mxnet/test_utils.py
  src/operator/cudnn_rnn-inl.h
  src/operator/nn/concat.cc
  src/operator/rnn-inl.h
  src/operator/rnn.cu
  tests/python/gpu/test_gluon_gpu.py
  tests/python/gpu/test_operator_gpu.py
  tests/python/unittest/common.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_gluon_rnn.py
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-merge

#13155 fix broken links (v1.3.x)
  docs/api/python/gluon/model_zoo.md
  docs/api/python/optimization/optimization.md
  docs/community/contribute.md
Labels: pr-awaiting-merge

#13153 add/update infer_range docs (v1.3.x)
  python/mxnet/ndarray/ndarray.py
  python/mxnet/symbol/symbol.py
  scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala
Labels: pr-awaiting-merge

#13154 fix broken Python IO API docs (v1.3.x)
  docs/api/python/io/io.md
  python/mxnet/io.py
Labels: pr-awaiting-merge

#13151 allow foreach on input with 0 length (v1.3.x)
  src/operator/control_flow.cc
  tests/python/unittest/test_contrib_control_flow.py
Labels: pr-awaiting-merge

#13158 fixed symbols naming in RNNCell, LSTMCell, GRUCell (v1.3.x)
  python/mxnet/gluon/rnn/rnn_cell.py
  tests/python/unittest/test_gluon_rnn.py
Labels: pr-awaiting-review

#13157 Fixed __setattr__ method of _MXClassPropertyMetaClass (v1.3.x)
  python/mxnet/base.py
Labels: pr-awaiting-review

#13156 Document the newly added env variable (v1.3.x)
  docs/faq/env_var.md
Labels: pr-awaiting-review

#13152 [MXNET-1179] Enforce deterministic algorithms in convolution layers (v1.3.x)
  src/operator/nn/cudnn/cudnn_convolution-inl.h
  src/operator/nn/cudnn/cudnn_deconvolution-inl.h
  src/operator/nn/cudnn/cudnn_pooling-inl.h
Labels: pr-awaiting-review

#13145 Add documentation on GPU performance on Quantization example
  example/quantization/README.md
  example/quantization/imagenet_inference.py
Labels: pr-awaiting-review

#13099 [MXNET-1194] Reenable nightly tutorials tests for Python2 and Python3
  ci/docker/runtime_functions.sh
  docs/settings.ini
  docs/tutorials/basic/module.md
  docs/tutorials/basic/symbol.md
  docs/tutorials/control_flow/ControlFlowTutorial.md
  docs/tutorials/gluon/hybrid.md
  docs/tutorials/gluon/learning_rate_finder.md
  docs/tutorials/gluon/learning_rate_schedules.md
  docs/tutorials/gluon/save_load_params.md
  docs/tutorials/onnx/export_mxnet_to_onnx.md
  docs/tutorials/onnx/fine_tuning_gluon.md
  docs/tutorials/python/linear-regression.md
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/nightly/JenkinsfileForBinaries
  tests/tutorials/test_sanity_tutorials.py
  tests/tutorials/test_tutorials.py
Labels: Test, pr-awaiting-review

#12950 Update dec example
  example/deep-embedded-clustering/README.md
  example/deep-embedded-clustering/data.py
  example/deep-embedded-clustering/dec.py
Labels: pr-awaiting-review

#12934 Updated capsnet example
  example/capsnet/README.md
  example/capsnet/capsulenet.py
Labels: Example, pr-awaiting-review

#13068 Updates to several examples
  example/reinforcement-learning/ddpg/README.md
  example/reinforcement-learning/dqn/setup.sh
  example/restricted-boltzmann-machine/README.md
  example/rnn-time-major/bucket_io.py
  example/rnn-time-major/get_sherlockholmes_data.sh
  example/rnn-time-major/readme.md
  example/rnn-time-major/rnn_cell_demo.py
  example/rnn/README.md
  example/rnn/bucketing/README.md
  example/rnn/large_word_lm/data.py
  example/rnn/large_word_lm/readme.md
  example/rnn/word_lm/README.md
  example/sparse/linear_classification/data.py
  example/speech_recognition/README.md
  example/speech_recognition/label_util.py
  example/speech_recognition/log_util.py
  example/speech_recognition/main.py
  example/speech_recognition/singleton.py
  example/speech_recognition/stt_datagenerator.py
  example/speech_recognition/stt_io_iter.py
  example/speech_recognition/stt_metric.py
  example/speech_recognition/stt_utils.py
  example/speech_recognition/train.py
  example/ssd/README.md
  example/stochastic-depth/sd_cifar10.py
  example/stochastic-depth/sd_mnist.py
  example/svm_mnist/svm_mnist.py
  example/svrg_module/README.md
  example/svrg_module/benchmarks/svrg_benchmark.ipynb
  example/svrg_module/linear_regression/data_reader.py
  example/svrg_module/linear_regression/train.py
Labels: Example, pr-awaiting-review

#13180 Remove test for non existing index copy operator (v1.3.x)
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13183 [MXNET-1187] Added Tutorial for Java under mxnet.io/docs/tutorials
  docs/tutorials/index.md
  docs/tutorials/java/mxnet_java_on_intellij.md
  tests/tutorials/test_sanity_tutorials.py
Labels: pr-awaiting-review

#13177 Fix Sphinx python docstring formatting error.
  python/mxnet/gluon/nn/basic_layers.py
Labels: pr-awaiting-review

#13101 [Doc] Fix repo paths in Ubuntu build doc
  docs/install/ubuntu_setup.md
Labels: Doc, pr-awaiting-review

#12827 Update scala intellij tutorial
  docs/tutorials/scala/mxnet_scala_on_intellij.md
Labels: Doc, Scala

#13093 Improve cpp-package example build files.
  cpp-package/example/Makefile
  cpp-package/example/README.md
  cpp-package/example/example.mk
Labels: C++, pr-awaiting-review

#13195 Fix Sphinx document parsing error.
  docs/api/python/gluon/model_zoo.md
  docs/api/python/io/io.md
Labels: Doc, pr-awaiting-review

#13176 Fix #13090, Add image.imread to python API doc.
  docs/api/python/image/image.md
Labels: pr-awaiting-merge

#13175 Fix Sphinx docstring formatting error. (#13004, #13005, #13006)
  python/mxnet/gluon/rnn/rnn_cell.py
  python/mxnet/rnn/rnn_cell.py
Labels: Doc, pr-awaiting-review

#13174 Fix #12944, Fix Sphinx python docstring formatting error.
  python/mxnet/gluon/parameter.py
Labels: pr-awaiting-review

#13186 [Example] Add a instruction to redirect the user to gluon-cv
  example/ssd/README.md
Labels: pr-awaiting-merge

#13207 [Scala][Clojure] Fix problem with some OSX not handling the cast on imDecode
  scala-package/core/src/main/scala/org/apache/mxnet/Image.scala
Labels: Clojure, Scala

#13107 Port of scala Image API to clojure
  contrib/clojure-package/src/org/apache/clojure_mxnet/image.clj
  contrib/clojure-package/test/org/apache/clojure_mxnet/image_test.clj
Labels: Clojure

#13215 Fixed Documentation issues
  python/mxnet/metric.py
  python/mxnet/module/sequential_module.py
Labels: pr-awaiting-review

#13200 Disable flaky test test_operator.test_dropout (v1.3.x)
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13205 [Example] Update faster rcnn doc
  example/rcnn/README.md
Labels: pr-awaiting-review

#13170 Fix Sphinx doc errors
  docs/api/python/image/image.md
  docs/api/python/module/module.md
  docs/api/python/symbol/symbol.md
  python/mxnet/contrib/svrg_optimization/svrg_module.py
  python/mxnet/rnn/rnn.py
  python/mxnet/rnn/rnn_cell.py
  python/mxnet/symbol/symbol.py
  python/mxnet/symbol_doc.py
  src/operator/contrib/adaptive_avg_pooling.cc
Labels: pr-awaiting-review

#13148 Fix Sphinx python docstring error: initializer.InitDesc (#12939)
  python/mxnet/initializer.py
Labels: pr-awaiting-review

#13149 Fix Sphinx python docstring error: text contrib module (#12949)
  python/mxnet/contrib/text/embedding.py
  python/mxnet/contrib/text/vocab.py
Labels: pr-awaiting-review

#13213 Sphinx failure fixes
  docs/api/python/ndarray/ndarray.md
  python/mxnet/ndarray/utils.py
Labels: Doc, pr-awaiting-review

#13203 [MXNET-793] Virtualized ARMv7 with Qemu CI integration
  Jenkinsfile
  ci/docker/qemu/runtime_functions.py
Labels: pr-awaiting-review

#10803 [MXNET-397] remove unused rotateM_
  src/io/image_aug_default.cc
Labels: pr-awaiting-review

#12631 [MXNET-953] Fix oob memory read
  src/operator/tensor/elemwise_unary_op_basic.cc
Labels: pr-awaiting-review

#13159 [MXNET-1202] Change Builder class into a better way
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/NDArray.scala
  scala-package/core/src/test/java/org/apache/mxnet/javaapi/NDArrayTest.java
  scala-package/macros/src/main/scala/org/apache/mxnet/APIDocGenerator.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/javaapi/JavaNDArrayMacro.scala
Labels: pr-awaiting-review

#13131 [MXNET-1077] update log4j version of Scala package
  scala-package/pom.xml
Labels: pr-awaiting-review

#12902 Disable Flaky test test_operator.test_clip
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#12964 Update multi-task learning example
  example/multi-task/README.md
  example/multi-task/example_multi_task.py
  example/multi-task/multi-task-learning.ipynb
Labels: pr-awaiting-review

#13182 Add functionality to build.py to disable caching
  ci/README.md
  ci/build.py
  ci/docker_cache.py
  ci/requirements.txt
Labels: pr-awaiting-review

#13202 Tool to ease compilation and reproduction of test results
  cmake/cmake_options.yml
  dev_menu.py
Labels: pr-awaiting-review

#12904 support upper triangular matrices in linalg
  src/operator/tensor/la_op-inl.h
  src/operator/tensor/la_op.cc
  src/operator/tensor/la_op.h
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13160 Fix Sphinx python docstrings
  docs/api/python/ndarray/sparse.md
  python/mxnet/gluon/model_zoo/vision/mobilenet.py
  python/mxnet/module/base_module.py
  python/mxnet/ndarray/ndarray.py
  python/mxnet/ndarray/sparse.py
  python/mxnet/optimizer/optimizer.py
  python/mxnet/recordio.py
  python/mxnet/test_utils.py
  python/mxnet/visualization.py
  src/operator/tensor/matrix_op.cc
Labels: pr-awaiting-merge

#12975 Implemented a regression unit test for #11793
  tests/python/unittest/test_module.py
Labels: C++, pr-awaiting-review

#13071 Add Java API docs generation
  docs/mxdoc.py
  docs/settings.ini
Labels: Java

#13251 Fix Sphinx error in ONNX file
  python/mxnet/contrib/onnx/onnx2mx/import_model.py
Labels: pr-awaiting-merge

#13242 [MXNET-918] [Introduce Random module / Refact code generation (#13038)][Cherry pick]
  scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/benchmark/ObjectDetectionBenchmark.java
  scala-package/macros/src/main/scala/org/apache/mxnet/APIDocGenerator.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/GeneratorBase.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/NDArrayMacro.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/SymbolMacro.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/javaapi/JavaNDArrayMacro.scala
Labels: Java, pr-awaiting-review

#13196 [Example] Fixing Gradcam implementation
  docs/tutorials/vision/cnn_visualization.md
  example/cnn_visualization/gradcam.py
  example/cnn_visualization/vgg.py
Labels: pr-awaiting-merge

#13043 Fix test failure due to hybridize call in test_gluon_rnn.test_layer_fill_shape
  CONTRIBUTORS.md
  src/imperative/cached_op.cc
  src/imperative/imperative.cc
  tests/python/unittest/test_gluon_rnn.py
Labels: Backend, Gluon, pr-awaiting-review

#13246 Addressed sphinx build issue
  docs/_static/js/auto_module_index.js
  docs/api/python/ndarray/ndarray.md
  docs/api/python/ndarray/random.md
Labels: pr-awaiting-review

#13229 Add gauss err function operator
  docs/api/python/ndarray/ndarray.md
  docs/api/python/symbol/symbol.md
  src/operator/math_functions-inl.h
  src/operator/mshadow_op.h
  src/operator/operator_tune.cc
  src/operator/tensor/elemwise_unary_op_basic.cc
  src/operator/tensor/elemwise_unary_op_basic.cu
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13168 Add Turing and Volta support to arch_name
  cmake/FirstClassLangCuda.cmake
Labels: pr-awaiting-review

#13249 Bugfix in ci/docker_cache.py
  ci/docker_cache.py
Labels: pr-awaiting-merge

#13189 Fix scaladoc build errors
  docs/mxdoc.py
  scala-package/core/pom.xml
  scala-package/core/src/main/scala/org/apache/mxnet/Context.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Executor.scala
  scala-package/core/src/main/scala/org/apache/mxnet/IO.scala
  scala-package/core/src/main/scala/org/apache/mxnet/KVStore.scala
  scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Optimizer.scala
  scala-package/core/src/main/scala/org/apache/mxnet/ResourceScope.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Symbol.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Visualization.scala
  scala-package/core/src/main/scala/org/apache/mxnet/io/MXDataIter.scala
  scala-package/core/src/main/scala/org/apache/mxnet/io/NDArrayIter.scala
  scala-package/core/src/main/scala/org/apache/mxnet/io/PrefetchingIter.scala
  scala-package/core/src/main/scala/org/apache/mxnet/io/ResizeIter.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/Context.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/IO.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/Shape.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/BaseModule.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/BucketingModule.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/DataParallelExecutorGroup.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/Module.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/SequentialModule.scala
Labels: pr-awaiting-merge

#13128 Add missing documentations for getnnz
  src/operator/contrib/nnz.cc
Labels: pr-awaiting-merge

#13259 Addressed ONNX module notes for short form description
  python/mxnet/contrib/onnx/mx2onnx/export_model.py
  python/mxnet/contrib/onnx/onnx2mx/import_model.py
  python/mxnet/contrib/onnx/onnx2mx/import_to_gluon.py
Labels: pr-awaiting-merge

#13258 Java Benchmark failure
  scala-package/.gitignore
  scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/benchmark/JavaBenchmark.java
Labels: pr-awaiting-merge

#12380 Manually track num_max_thread
  src/engine/openmp.cc
Labels: pr-awaiting-review

#12985 adding unit test for MKLDNN FullyConnected operator
  tests/cpp/operator/mkldnn_operator_test.cc
Labels: MKLDNN, Operator, pr-awaiting-review

#13256 Fix sphinx issues
  src/operator/contrib/index_copy.cc
  src/operator/contrib/quadratic_op.cc
  src/operator/contrib/roi_align.cc
Labels: pr-awaiting-merge

#13239 [Example] fix train mnist for inception-bn and resnet
  example/image-classification/train_mnist.py
Labels: pr-awaiting-merge

#13218 Fix a bug in index_copy
  src/operator/contrib/index_copy-inl.h
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-merge

#13165 Addressed doc issues
  python/mxnet/gluon/nn/basic_layers.py
  python/mxnet/ndarray/ndarray.py
Labels: pr-awaiting-merge

#13267 [MXNET-1181] Added command line alternative to IntelliJ in install instructions
  docs/tutorials/java/mxnet_java_on_intellij.md
  docs/tutorials/scala/mxnet_java_install_and_run_examples.md
Labels: pr-awaiting-merge

#13255 [Example] Gradcam consolidation in tutorial
  docs/conf.py
  docs/tutorial_utils/vision/cnn_visualization/gradcam.py
  docs/tutorials/vision/cnn_visualization.md
  example/cnn_visualization/README.md
  example/cnn_visualization/gradcam_demo.py
  example/cnn_visualization/vgg.py
Labels: Example, pr-awaiting-review

#13144 [MXNET-1203] Tutorial infogan
  docs/tutorials/gluon/info_gan.md
  docs/tutorials/index.md
  tests/tutorials/test_tutorials.py
Labels: pr-awaiting-review

#13235 Remove obsolete memory cost example
  docs/architecture/note_memory.md
  example/memcost/Makefile
  example/memcost/README.md
  example/memcost/inception_memcost.py
Labels: pr-awaiting-review

#13237 [MXNET-1182] Predictor example
  scala-package/examples/scripts/infer/predictor/run_predictor_java_example.sh
  scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/infer/predictor/PredictorExample.java
  scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/infer/predictor/README.md
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/javaapi/Predictor.scala
Labels: pr-work-in-progress

#13261 Fix Sphinx errors in box_nms
  src/operator/contrib/bounding_box.cc
Labels: pr-awaiting-merge

#13252 Fix Sphinx errors
  python/mxnet/gluon/contrib/rnn/conv_rnn_cell.py
  python/mxnet/io/io.py
  python/mxnet/test_utils.py
Labels: pr-awaiting-merge

#13275 Sphinx errors in Gluon
  python/mxnet/autograd.py
  python/mxnet/gluon/block.py
  python/mxnet/gluon/contrib/nn/basic_layers.py
  python/mxnet/gluon/contrib/rnn/rnn_cell.py
  python/mxnet/gluon/data/vision/datasets.py
  python/mxnet/gluon/loss.py
  python/mxnet/gluon/nn/basic_layers.py
  python/mxnet/gluon/parameter.py
  python/mxnet/test_utils.py
Labels: pr-awaiting-merge

#13194 Fix Sphinx python docstring formatting error.
  src/operator/nn/batch_norm.cc
Labels: pr-awaiting-merge

#13291 Visualization doc fix. Added notes for shortform
  python/mxnet/visualization.py
Labels: pr-awaiting-merge

#13214 Sphinx failure fixes. Fixes most of the "Duplicate object description" warnings
  docs/api/python/symbol/random.md
Labels: pr-awaiting-merge

#13299 Update Dense Block doc
  python/mxnet/gluon/nn/basic_layers.py
Labels: pr-awaiting-merge

#13304 Add url and license to clojure package project
  contrib/clojure-package/project.clj
Labels: Clojure, pr-awaiting-merge

#13286 [Example] Add docstring for test optimizer and test score
  cpp-package/example/test_optimizer.cpp
  cpp-package/example/test_score.cpp
Labels: pr-awaiting-merge

#13280 [Example] Update cpp example README
  cpp-package/example/README.md
Labels: pr-awaiting-merge

#13184 [Example]update NER example readme on module prediction
  example/named_entity_recognition/README.md
Labels: pr-awaiting-merge

#13276 enabling test_dropout after fixing flaky issue
  src/operator/nn/dropout-inl.h
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13305 Made fixes to sparse.py and sparse.md
  docs/api/python/ndarray/sparse.md
  python/mxnet/ndarray/sparse.py
Labels: pr-awaiting-merge

#13210 Fix descriptions in scaladocs for macro ndarray/sybmol APIs
  scala-package/macros/src/main/scala/org/apache/mxnet/APIDocGenerator.scala
Labels: pr-awaiting-merge

#13307 [Example] Gradcam- Fixing a link
  docs/tutorials/vision/cnn_visualization.md
Labels: pr-awaiting-merge

#13192 Updated the Instructions for use of the label bot
  CONTRIBUTORS.md
Labels: pr-awaiting-merge

#11047 [MXNET-33] Enhance mkldnn pooling to support full convention
  src/operator/nn/mkldnn/mkldnn_pooling-inl.h
  src/operator/nn/mkldnn/mkldnn_pooling.cc
  tests/python/gpu/test_operator_gpu.py
Labels: pr-awaiting-review

#13296 Fix R GPU flaky test
  Makefile
Labels: pr-awaiting-merge

#13302 modified code for working in gpu context.
  docs/tutorials/python/predict_image.md
Labels: pr-awaiting-merge

#12356 [MXNET-860] Use modernized ranged loops where possible
  src/c_api/c_api_symbolic.cc
  src/c_api/c_predict_api.cc
  src/common/exec_utils.h
  src/executor/attach_op_execs_pass.cc
  src/executor/graph_executor.cc
  src/imperative/cached_op.cc
  src/imperative/imperative.cc
  src/imperative/imperative_utils.cc
  src/io/image_aug_default.cc
  src/io/image_det_aug_default.cc
  src/kvstore/comm.h
  src/kvstore/comm_tree.h
  src/kvstore/gpu_topology.h
  src/ndarray/ndarray.cc
  src/nnvm/graph_editor.cc
  src/nnvm/legacy_json_util.cc
  src/nnvm/legacy_op_util.cc
  src/operator/bilinear_sampler-inl.h
  src/operator/custom/custom.cc
  src/operator/custom/native_op-inl.h
  src/operator/custom/ndarray_op-inl.h
  src/operator/grid_generator-inl.h
  src/operator/nn/concat.cc
  src/operator/operator_common.h
  src/operator/operator_util.cc
  src/operator/quantization/quantized_pooling.cc
  src/operator/random/multisample_op.h
  src/operator/spatial_transformer-inl.h
  src/operator/subgraph/partition_graph.cc
  src/operator/tensor/matrix_op-inl.h
  src/profiler/aggregate_stats.cc
Labels: pr-awaiting-merge

#11778 [MXNET-483] C++ tests for mkldnn convolution/deconvolution operator
  src/operator/nn/mkldnn/mkldnn_convolution.cc
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
  tests/cpp/include/test_mkldnn.h
  tests/cpp/operator/mkldnn_operator_test.cc
  tests/cpp/operator/mkldnn_test.cc
Labels: MKLDNN, pr-awaiting-response, pr-awaiting-testing

#12924 Fix ONNX export of keepdims param
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
Labels: pr-awaiting-merge

#13283 [MXNET-1215] Allow dynamic shape exists in imperative mode
  include/mxnet/ndarray.h
  src/imperative/imperative.cc
  src/imperative/imperative_utils.h
  src/operator/contrib/boolean_mask-inl.h
  src/operator/contrib/boolean_mask.cc
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13268 Fix/link to mkl build
  cmake/DownloadMKLML.cmake
Labels: pr-awaiting-review

#13266 Update Requests version to 2.20.0 to handle security risk
  python/setup.py
Labels: pr-awaiting-review

#13323 Fix nightly test issue and add docs build settings for 1.3.x
  docs/settings.ini
Labels: Build, CI, Doc, pr-awaiting-review

#13278 [Example]Refactor alexnet cpp example
  cpp-package/example/alexnet.cpp
Labels: pr-awaiting-review

#13317 [Example] Update C++ tutorials (#13316)
  docs/tutorials/c++/basics.md
Labels: pr-awaiting-merge

#13069 add Volta and Turing arch
  Makefile
  cmake/FirstClassLangCuda.cmake
Labels: CMake, pr-awaiting-merge

#13231 Bumped minor version to 1.4.0 as 1.3.1 will be continued in the v1.3.…
  R-package/DESCRIPTION
  contrib/clojure-package/README.md
  contrib/clojure-package/examples/cnn-text-classification/project.clj
  contrib/clojure-package/examples/gan/project.clj
  contrib/clojure-package/examples/imclassification/project.clj
  contrib/clojure-package/examples/module/project.clj
  contrib/clojure-package/examples/multi-label/project.clj
  contrib/clojure-package/examples/neural-style/project.clj
  contrib/clojure-package/examples/pre-trained-models/project.clj
  contrib/clojure-package/examples/profiler/project.clj
  contrib/clojure-package/examples/rnn/project.clj
  contrib/clojure-package/examples/tutorial/project.clj
  contrib/clojure-package/examples/visualization/project.clj
  contrib/clojure-package/project.clj
  docs/tutorials/scala/mxnet_scala_on_intellij.md
  include/mxnet/base.h
  python/mxnet/libinfo.py
  scala-package/assembly/linux-x86_64-cpu/pom.xml
  scala-package/assembly/linux-x86_64-gpu/pom.xml
  scala-package/assembly/osx-x86_64-cpu/pom.xml
  scala-package/assembly/pom.xml
  scala-package/core/pom.xml
  scala-package/examples/pom.xml
  scala-package/infer/pom.xml
  scala-package/init-native/linux-x86_64/pom.xml
  scala-package/init-native/osx-x86_64/pom.xml
  scala-package/init-native/pom.xml
  scala-package/init/pom.xml
  scala-package/macros/pom.xml
  scala-package/native/linux-x86_64-cpu/pom.xml
  scala-package/native/linux-x86_64-gpu/pom.xml
  scala-package/native/osx-x86_64-cpu/pom.xml
  scala-package/native/pom.xml
  scala-package/pom.xml
  scala-package/spark/pom.xml
  snapcraft.yaml
  tests/nightly/model_backwards_compatibility_check/train_mxnet_legacy_models.sh
Labels: pr-awaiting-merge

#13109 Improve cmake flags
  CMakeLists.txt
Labels: CMake, pr-awaiting-merge

#13315 Fix sphinx docstring warnings.
  python/mxnet/contrib/io.py
  python/mxnet/contrib/svrg_optimization/svrg_module.py
  python/mxnet/contrib/text/embedding.py
  python/mxnet/gluon/data/vision/datasets.py
  python/mxnet/image/image.py
  python/mxnet/optimizer/optimizer.py
  python/mxnet/rnn/rnn_cell.py
  python/mxnet/symbol/contrib.py
  python/mxnet/torch.py
  src/operator/contrib/adaptive_avg_pooling.cc
Labels: Doc, pr-awaiting-review

#12962 fix broken links and reorganize build from source page
  docs/install/build_from_source.md
  docs/tutorials/unsupervised_learning/gan.md
Labels: pr-awaiting-review

#13204 fix formatting for the CentOS installation instructions
  docs/install/centos_setup.md
Labels: pr-awaiting-merge

#13336 GEMM Tensor Core Support
  src/operator/linalg_impl.h
  src/operator/rnn.cc
  src/operator/tensor/la_op.cc
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13355 Replace fileread with reading from stdout
  ci/Jenkinsfile_utils.groovy
Labels: pr-awaiting-review

#13328 adding test for softmax operator for inputs with large magnitude
  tests/python/mkl/test_mkldnn.py
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13260 Support full convention in quantized pooling
  example/quantization/imagenet_gen_qsym_mkldnn.py
  src/operator/quantization/quantized_pooling.cc
  tests/python/quantization/test_quantization.py
Labels: pr-awaiting-review

#13290 A few operators on graphs stored as CSR
  docs/api/python/ndarray/contrib.md
  src/operator/contrib/dgl_graph.cc
  tests/python/unittest/test_contrib_operator.py
  tests/python/unittest/test_dgl_graph.py
Labels: pr-awaiting-review

#13387 Fixes #13386 - Refer Warnings
  contrib/clojure-package/src/dev/generator.clj
  contrib/clojure-package/src/org/apache/clojure_mxnet/ndarray.clj
  contrib/clojure-package/src/org/apache/clojure_mxnet/symbol.clj
  contrib/clojure-package/test/good-test-ndarray.clj
  contrib/clojure-package/test/good-test-symbol.clj
Labels: Clojure

#13361 Updated the paths for images for java tutorial
  docs/tutorials/java/mxnet_java_on_intellij.md
Labels: pr-awaiting-review

#13324 Fix/env disable mkldnn cache map
  docs/faq/env_var.md
  src/common/utils.h
  src/operator/nn/mkldnn/mkldnn_act.cc
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_concat.cc
  src/operator/nn/mkldnn/mkldnn_convolution.cc
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
  src/operator/nn/mkldnn/mkldnn_lrn-inl.h
  src/operator/nn/mkldnn/mkldnn_pooling.cc
Labels: pr-awaiting-review

#13289 Initial website documentation for Java API
  docs/_static/js/sidebar.js
  docs/_static/mxnet-theme/navbar.html
  docs/api/java/index.md
  docs/install/build_from_source.md
  docs/install/java_setup.md
  docs/mxdoc.py
  docs/tutorials/java/index.md
  tests/tutorials/test_sanity_tutorials.py
Labels: pr-awaiting-review

#13402 Replace mxnetci dockcross with public dockcross due to missing image
  Jenkinsfile
  ci/docker/Dockerfile.build.android_armv7
  ci/docker/Dockerfile.build.android_armv8
  ci/docker/Dockerfile.build.armv6
  ci/docker/Dockerfile.build.armv7
  ci/docker/Dockerfile.build.armv8
  ci/docker/Dockerfile.build.jetson
  ci/jenkins/Jenkinsfile_edge
Labels: pr-awaiting-review

#13348 Correct shapes of images in cifar10 and cifar100
  python/mxnet/gluon/data/vision/datasets.py
Labels: pr-awaiting-merge

#13041 Updated recommenders example
  example/recommenders/README.md
  example/recommenders/crossentropy.py
  example/recommenders/demo1-MF.ipynb
  example/recommenders/demo1-MF2-fancy.ipynb
  example/recommenders/demo2-binary.ipynb
  example/recommenders/demo2-dssm.ipynb
  example/recommenders/demo3-dssm.ipynb
  example/recommenders/matrix_fact.py
  example/recommenders/movielens_data.py
  example/recommenders/negativesample.py
  example/recommenders/randomproj.py
  example/recommenders/recotools.py
  example/recommenders/symbol_alexnet.py
Labels: pr-awaiting-merge

#13318 Improving multi-processing reliability for gluon DataLoader
  python/mxnet/gluon/data/dataloader.py
Labels: Data-loading, Gluon, pr-awaiting-review

#13398 Use dynamic omp schedule for sparse dot with large matrix
  src/operator/mxnet_op.h
  src/operator/tensor/dot-inl.h
Labels: pr-awaiting-response

#13393 Fixes #13388 Adds Clojure to MXNet installation docs
  docs/install/index.md
Labels: Clojure, Doc

#13412 Minor fixes to documentation
  docs/tutorials/java/mxnet_java_on_intellij.md
  docs/tutorials/java/ssd_inference.md
Labels: Doc, Java, pr-awaiting-review
