Repository apache/mxnet, pull requests merged in 2018-09, with the labels that each got.

#12462 [MXNET-908] Enable minimal OSX Travis build
  .travis.yml
  ci/travis/install.sh
  tests/travis/is_core_changed.sh
  tests/travis/run_test.sh
  tests/travis/setup.sh
  tests/travis/travis_after_failure.sh
Labels: pr-awaiting-testing

#12475 [MXNET-703] Static linking for libprotobuf with TensorRT
  ci/docker/install/tensorrt.sh
Labels: pr-awaiting-review

#12482 fix website render issue on &lt; and &gt;
  docs/build_version_doc/AddVersion.py
Labels: pr-awaiting-merge

#12376 [MXNET-854] SVRG Optimization in Python Module API
  docs/api/python/contrib/svrg_optimization.md
  docs/api/python/index.md
  docs/api/python/module/module.md
  example/svrg_module/README.md
  example/svrg_module/api_usage_example/example_api_train.py
  example/svrg_module/api_usage_example/example_inference.py
  example/svrg_module/benchmarks/svrg_benchmark.ipynb
  example/svrg_module/linear_regression/common.py
  example/svrg_module/linear_regression/data_reader.py
  example/svrg_module/linear_regression/train.py
  python/mxnet/contrib/svrg_optimization/__init__.py
  python/mxnet/contrib/svrg_optimization/svrg_module.py
  python/mxnet/contrib/svrg_optimization/svrg_optimizer.py
  tests/python/unittest/test_contrib_svrg_module.py
  tests/python/unittest/test_contrib_svrg_optimizer.py
Labels: Python, pr-awaiting-review

#12455 Add Python API docs for test_utils and visualization
  docs/api/python/index.md
  docs/api/python/tools/test_utils.md
  docs/api/python/tools/visualization.md
Labels: pr-awaiting-merge

#12474 fix subscribe links, remove disabled icons
  docs/community/mxnet_channels.md
Labels: pr-awaiting-merge

#12285 Change the way NDArrayIter handle the last batch
  CONTRIBUTORS.md
  python/mxnet/io/__init__.py
  python/mxnet/io/io.py
  python/mxnet/io/utils.py
  tests/python/unittest/test_io.py
Labels: Data-loading, pr-awaiting-review

#12419 [MXNET-580] Add SN-GAN example
  example/README.md
  example/gluon/sn_gan/README.md
  example/gluon/sn_gan/data.py
  example/gluon/sn_gan/model.py
  example/gluon/sn_gan/sn_gan_output.png
  example/gluon/sn_gan/train.py
  example/gluon/sn_gan/utils.py
Labels: Example, Gluon, pr-awaiting-review

#11301 MKLDNN Backward op cache
  src/operator/nn/fully_connected.cc
  src/operator/nn/lrn.cc
  src/operator/nn/mkldnn/mkldnn_act.cc
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_base.cc
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_convolution.cc
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
  src/operator/nn/mkldnn/mkldnn_lrn-inl.h
  src/operator/nn/mkldnn/mkldnn_pooling-inl.h
  src/operator/nn/mkldnn/mkldnn_pooling.cc
Labels: Backend, MKLDNN, pr-awaiting-review

#12548 [MXNET-703] Add a TensorRT walkthrough
  docs/tutorials/tensorrt/index.md
  docs/tutorials/tensorrt/inference_with_trt.md
  docs/tutorials/tensorrt/wavenet_optimized.png
  docs/tutorials/tensorrt/wavenet_optimized.svg
  docs/tutorials/tensorrt/wavenet_unoptimized.png
  docs/tutorials/tensorrt/wavenet_unoptimized.svg
  tests/tutorials/test_sanity_tutorials.py
Labels: pr-awaiting-merge

#12561 Fix error in try/finally block for blc
  tests/nightly/broken_link_checker_test/JenkinsfileForBLC
Labels: pr-awaiting-merge

#12559 Add license headers to R-package
  R-package/LICENSE
  R-package/R/callback.R
  R-package/R/context.R
  R-package/R/executor.R
  R-package/R/initializer.R
  R-package/R/io.R
  R-package/R/kvstore.R
  R-package/R/lr_scheduler.R
  R-package/R/metric.R
  R-package/R/mlp.R
  R-package/R/model.R
  R-package/R/model.rnn.R
  R-package/R/mx.io.bucket.iter.R
  R-package/R/ndarray.R
  R-package/R/optimizer.R
  R-package/R/profiler.R
  R-package/R/random.R
  R-package/R/rnn.graph.R
  R-package/R/rnn.infer.R
  R-package/R/symbol.R
  R-package/R/util.R
  R-package/R/viz.graph.R
  R-package/R/zzz.R
  R-package/demo/basic_bench.R
  R-package/demo/basic_executor.R
  R-package/demo/basic_kvstore.R
  R-package/demo/basic_model.R
  R-package/demo/basic_ndarray.R
  R-package/demo/basic_random.R
  R-package/demo/basic_symbol.R
  R-package/src/base.h
  R-package/src/executor.cc
  R-package/src/executor.h
  R-package/src/export.cc
  R-package/src/export.h
  R-package/src/im2rec.cc
  R-package/src/im2rec.h
  R-package/src/io.cc
  R-package/src/io.h
  R-package/src/kvstore.cc
  R-package/src/kvstore.h
  R-package/src/mxnet.cc
  R-package/src/name.h
  R-package/src/ndarray.cc
  R-package/src/ndarray.h
  R-package/src/symbol.cc
  R-package/src/symbol.h
  R-package/tests/testthat/get_data.R
  R-package/tests/testthat/test_img_seg.R
  R-package/tests/testthat/test_initializer.R
  R-package/tests/testthat/test_io.R
  R-package/tests/testthat/test_model.R
  R-package/tests/testthat/test_ndarray.R
  R-package/tests/testthat/test_optimizer.R
  R-package/tests/testthat/test_random.R
  R-package/tests/testthat/test_symbol.R
Labels: R, pr-awaiting-response

#12180 Make the Ubuntu scripts executable after download.
  docs/install/scala_setup.md
Labels: pr-awaiting-merge

#12534 Fix the installation doc for MKL-DNN backend
  docs/install/build_from_source.md
  docs/install/ubuntu_setup.md
Labels: pr-awaiting-merge

#12525 Updating news, readme files and bumping master version to 1.3.1
  NEWS.md
  R-package/DESCRIPTION
  README.md
  contrib/clojure-package/README.md
  contrib/clojure-package/examples/cnn-text-classification/project.clj
  contrib/clojure-package/examples/gan/project.clj
  contrib/clojure-package/examples/imclassification/project.clj
  contrib/clojure-package/examples/module/project.clj
  contrib/clojure-package/examples/multi-label/project.clj
  contrib/clojure-package/examples/neural-style/project.clj
  contrib/clojure-package/examples/pre-trained-models/project.clj
  contrib/clojure-package/examples/profiler/project.clj
  contrib/clojure-package/examples/rnn/project.clj
  contrib/clojure-package/examples/tutorial/project.clj
  contrib/clojure-package/examples/visualization/project.clj
  contrib/clojure-package/project.clj
  include/mxnet/base.h
  python/mxnet/libinfo.py
  scala-package/assembly/linux-x86_64-cpu/pom.xml
  scala-package/assembly/linux-x86_64-gpu/pom.xml
  scala-package/assembly/osx-x86_64-cpu/pom.xml
  scala-package/assembly/pom.xml
  scala-package/core/pom.xml
  scala-package/examples/pom.xml
  scala-package/infer/pom.xml
  scala-package/init-native/linux-x86_64/pom.xml
  scala-package/init-native/osx-x86_64/pom.xml
  scala-package/init-native/pom.xml
  scala-package/init/pom.xml
  scala-package/macros/pom.xml
  scala-package/native/linux-x86_64-cpu/pom.xml
  scala-package/native/linux-x86_64-gpu/pom.xml
  scala-package/native/osx-x86_64-cpu/pom.xml
  scala-package/native/pom.xml
  scala-package/pom.xml
  scala-package/spark/pom.xml
  snapcraft.yaml
Labels: pr-awaiting-review

#12504 replacing windows setup with newer instructions
  docs/install/windows_setup.md
Labels: pr-work-in-progress

#12549 [MXNET-703] Add TensorRT runtime Dockerfile
  docker/Dockerfiles/Dockerfile.tensorrt
Labels: pr-awaiting-review

#12361 [MXNET-860] - Avoid implicit double conversions in math operations.
  src/io/image_det_aug_default.cc
  src/operator/contrib/adaptive_avg_pooling.cc
  src/operator/contrib/multi_proposal.cc
  src/operator/contrib/multibox_detection.cc
  src/operator/contrib/proposal.cc
  src/operator/contrib/roi_align.cc
  src/operator/correlation-inl.h
  src/operator/image/image_random-inl.h
  src/operator/nn/batch_norm.cc
  src/operator/nn/lrn-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  src/operator/nn/pooling.cc
  src/operator/pooling_v1-inl.h
  src/operator/roi_pooling.cc
  src/operator/spatial_transformer.cc
  src/operator/tensor/elemwise_binary_op-inl.h
  src/operator/tensor/elemwise_binary_op.h
Labels: pr-awaiting-review

#12355 [MXNET-860] Reduce redundant copies, check for regressions with clang-tidy
  .clang-tidy
  src/ndarray/ndarray.cc
  src/operator/contrib/roi_align.cc
Labels: pr-awaiting-review

#12571 Disable installation nightly test
  tests/nightly/Jenkinsfile
Labels: pr-awaiting-review

#12551 Add correct test coverage branch detection
  ci/Jenkinsfile_utils.groovy
Labels: pr-awaiting-merge

#12558 [MXNET-952] Check for correlation kernel size along with unittest
  src/operator/correlation-inl.h
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#12186 Added comment to docs regarding ToTensor transform
  docs/api/python/gluon/data.md
  python/mxnet/gluon/data/vision/transforms.py
Labels: pr-awaiting-review

#12412 Infer dtype in SymbolBlock import from input symbol
  python/mxnet/gluon/block.py
  python/mxnet/gluon/parameter.py
  tests/python/gpu/test_gluon_gpu.py
  tests/python/unittest/test_gluon.py
Labels: Gluon, pr-awaiting-review

#12563 Speed up CI windows builds
  ci/build_windows.py
Labels: pr-awaiting-testing

#12370 [MXNET-953] - Add ASAN sanitizer, Enable in CI
  CMakeLists.txt
  Jenkinsfile
  ci/Jenkinsfile_utils.groovy
  ci/build.py
  ci/docker/Dockerfile.build.ubuntu_cpu
  ci/docker/install/ubuntu_gcc8.sh
  ci/docker/runtime_functions.sh
Labels: pr-awaiting-response

#12550 [MXNET-908] Enable python tests in Travis
  .travis.yml
  ci/travis/install.sh
Labels: pr-work-in-progress

#12588 Pinned dockcross to a tag with fixed ABI for RPi
  ci/docker/Dockerfile.build.armv7
Labels: pr-awaiting-merge

#12587 add TensorRT tutorial to index and fix ToC
  docs/tutorials/control_flow/index.md
  docs/tutorials/index.md
  tests/tutorials/test_sanity_tutorials.py
Labels: pr-awaiting-review

#12182 [MXNET-698] Correct train-metric log to reflect epoch metric
  python/mxnet/callback.py
  python/mxnet/module/base_module.py
Labels: Python, pr-awaiting-review

#12606 Refine the documentation of im2rec
  docs/faq/recordio.md
  docs/tutorials/basic/data.md
Labels: pr-awaiting-review

#12601 Fixed typo in c_predict_api.cc
  src/c_api/c_predict_api.cc
Labels: pr-awaiting-review

#12599 Fix typo in profiler.h
  src/profiler/profiler.h
Labels: pr-awaiting-review

#12600 Tweaked the copy in c_predict_api.h
  include/mxnet/c_predict_api.h
Labels: pr-awaiting-review

#12560 fix test_activation by lowering threshold + validate eps for check_numeric_gradient
  python/mxnet/test_utils.py
  tests/python/mkl/test_mkldnn.py
Labels: pr-awaiting-review

#12190 Updated Symbol tutorial with Gluon
  docs/tutorials/basic/symbol.md
Labels: pr-awaiting-testing

#12596 [v1.3.x] Fix armv7 hard float
  ci/docker/Dockerfile.build.armv7
Labels: pr-awaiting-testing

#12570 review require() usages to add meaningful messages.
  scala-package/core/src/main/scala/org/apache/mxnet/EvalMetric.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Executor.scala
  scala-package/core/src/main/scala/org/apache/mxnet/ExecutorManager.scala
  scala-package/core/src/main/scala/org/apache/mxnet/FeedForward.scala
  scala-package/core/src/main/scala/org/apache/mxnet/IO.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Initializer.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Model.scala
  scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Operator.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Profiler.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Symbol.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Visualization.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/BaseModule.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/BucketingModule.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/DataParallelExecutorGroup.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/Module.scala
  scala-package/core/src/main/scala/org/apache/mxnet/module/SequentialModule.scala
  scala-package/core/src/main/scala/org/apache/mxnet/optimizer/DCASGD.scala
  scala-package/core/src/main/scala/org/apache/mxnet/optimizer/NAG.scala
  scala-package/core/src/main/scala/org/apache/mxnet/optimizer/SGD.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/Classifier.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/MXNetHandler.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/Predictor.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/utils/CToScalaUtils.scala
  scala-package/spark/src/main/scala/org/apache/mxnet/spark/MXNDArray.scala
  scala-package/spark/src/main/scala/org/apache/mxnet/spark/MXNetModel.scala
Labels: Scala, pr-work-in-progress

#12607 [MXNet-970] improve tutorial redirection
  docs/build_version_doc/artifacts/.htaccess
Labels: pr-awaiting-merge

#12604 Remove pip overwrites
  docs/build_version_doc/AddVersion.py
Labels: pr-awaiting-review

#12618 Fixed NoSuchMethodError for Jenkins Job for MBCC
  tests/nightly/model_backwards_compatibility_check/JenkinsfileForMBCC
Labels: pr-awaiting-response

#12617 update download links to apache distros
  docs/install/download.md
Labels: pr-awaiting-merge

#12352 [MXNET-860] Update to modern nullptr usage
  .clang-tidy
  src/c_api/c_api_executor.cc
  src/io/iter_image_det_recordio.cc
  src/io/iter_image_recordio.cc
  src/io/iter_image_recordio_2.cc
  src/io/iter_mnist.cc
  src/ndarray/ndarray.cc
  src/operator/bilinear_sampler.cc
  src/operator/contrib/count_sketch.cc
  src/operator/contrib/deformable_convolution.cc
  src/operator/contrib/deformable_psroi_pooling.cc
  src/operator/contrib/deformable_psroi_pooling.cu
  src/operator/contrib/fft.cc
  src/operator/contrib/ifft.cc
  src/operator/contrib/multibox_detection.cc
  src/operator/contrib/multibox_prior.cc
  src/operator/contrib/multibox_target.cc
  src/operator/contrib/psroi_pooling.cc
  src/operator/contrib/psroi_pooling.cu
  src/operator/convolution_v1.cc
  src/operator/correlation.cc
  src/operator/correlation.cu
  src/operator/custom/custom.cc
  src/operator/grid_generator.cc
  src/operator/l2_normalization.cc
  src/operator/l2_normalization.cu
  src/operator/leaky_relu.cc
  src/operator/leaky_relu.cu
  src/operator/make_loss.cc
  src/operator/pad.cc
  src/operator/pooling_v1.cc
  src/operator/rnn.cc
  src/operator/roi_pooling.cc
  src/operator/roi_pooling.cu
  src/operator/sequence_last.cc
  src/operator/sequence_mask.cc
  src/operator/sequence_reverse.cc
  src/operator/sequence_reverse.cu
  src/operator/softmax_output.cc
  src/operator/spatial_transformer.cc
  src/operator/svm_output.cc
  src/operator/swapaxis.cc
Labels: pr-awaiting-response

#12499 [MXNET-922] Fix memleak in profiler
  src/profiler/profiler.cc
  src/profiler/profiler.h
Labels: pr-awaiting-response

#12315 Enable gluon multi worker data loader test
  tests/python/unittest/test_gluon_data.py
Labels: Test, pr-awaiting-review

#12615 Correct PR branch detection in code coverage
  ci/Jenkinsfile_utils.groovy
Labels: pr-awaiting-merge

#12609 Include missing import in TensorRT tutorial
  docs/tutorials/tensorrt/inference_with_trt.md
Labels: pr-awaiting-review

#12603 [MXNET-969] Fix buffer overflow in RNNOp
  src/operator/rnn-inl.h
Labels: pr-awaiting-review

#10697 [MXNET-360]auto convert str to bytes in img.imdecode when py3
  python/mxnet/image/image.py
Labels: pr-awaiting-merge

#12620 Update and modify Windows docs
  docs/install/windows_setup.md
Labels: pr-awaiting-review

#12626 Fix distributed training doc
  docs/faq/distributed_training.md
Labels: pr-awaiting-review

#12621 Add docstring in im2rec.py
  docs/architecture/note_data_loading.md
  docs/faq/recordio.md
  docs/tutorials/basic/data.md
  tools/im2rec.py
Labels: Doc, pr-awaiting-review

#12047 [MXNET-779]Add DLPack Transformation API
  include/mxnet/c_api.h
  include/mxnet/ndarray.h
  include/mxnet/tensor_blob.h
  python/mxnet/base.py
  python/mxnet/ndarray/ndarray.py
  src/c_api/c_api.cc
  src/ndarray/ndarray.cc
  tests/python/unittest/test_ndarray.py
Labels: Backend, pr-awaiting-merge

#12632 Fix version dropdown behavior
  docs/_static/js/docversion.js
  docs/_static/mxnet-theme/layout.html
  docs/build_version_doc/AddVersion.py
Labels: pr-awaiting-review

#12644 Fix reference to wrong function
  tests/nightly/JenkinsfileForBinaries
Labels: pr-awaiting-review

#11641 [MXNET-876] make CachedOp a normal operator
  src/imperative/cached_op.cc
  src/imperative/cached_op.h
  src/operator/operator_common.h
  src/operator/subgraph/common.h
  src/operator/subgraph/default_subgraph_op.cc
  src/operator/subgraph/default_subgraph_op.cu
  src/operator/subgraph/default_subgraph_property.cc
  tests/python/unittest/test_subgraph.py
Labels: Backend, Operator, pr-work-in-progress

#12642 Enable C++ coverage
  .codecov.yml
  .gitignore
  CMakeLists.txt
  Jenkinsfile
  Makefile
  ci/Jenkinsfile_utils.groovy
  ci/docker/runtime_functions.sh
Labels: pr-awaiting-merge

#12622 Gluon DataLoader: avoid recursionlimit error
  python/mxnet/gluon/data/dataloader.py
  python/mxnet/recordio.py
  tests/python/unittest/test_gluon_data.py
Labels: pr-awaiting-review

#12594 [MXNET-867] Pooling1D with "same" padding
  CONTRIBUTORS.md
  src/operator/nn/pool.h
  src/operator/nn/pooling-inl.h
  src/operator/nn/pooling.cc
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#12584 [Doc] Change the description for pip packages
  docs/install/index.md
  docs/install/windows_setup.md
Labels: pr-awaiting-review

#12654 Change dependencies documentation opencv2-->opencv
  docs/tutorials/scala/mxnet_scala_on_intellij.md
Labels: pr-awaiting-review

#12614 fix bug, issue 12613
  src/executor/graph_executor.cc
  src/executor/graph_executor.h
Labels: pr-awaiting-review

#12051 [MXNET-780] Fix exception handling bug
  src/io/iter_image_det_recordio.cc
  src/io/iter_image_recordio_2.cc
  tests/python/unittest/test_io.py
Labels: Bug, C API, pr-awaiting-review

#12660 fix bug in prelu , issue 12061
  src/operator/leaky_relu-inl.h
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#12667 add mentions of the gluon toolkits and links to resources
  docs/gluon/index.md
Labels: pr-awaiting-review

#12686 Remove fixed seed for test_ctc_loss
  tests/python/unittest/test_loss.py
Labels: pr-awaiting-review

#12695 remove ApacheCon promo
  docs/_static/mxnet-theme/index.html
Labels: pr-awaiting-review

#12633 Onnx version update from 1.2.1 to 1.3 in CI
  ci/docker/install/ubuntu_onnx.sh
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  tests/python-pytest/onnx/export/onnx_backend_test.py
  tests/python-pytest/onnx/import/mxnet_backend_rep.py
  tests/python-pytest/onnx/import/mxnet_backend_test.py
  tests/python-pytest/onnx/import/test_cases.py
Labels: pr-awaiting-review

#12670 [MXNET-833] [R] Char-level RNN tutorial fix
  R-package/vignettes/CharRnnModel.Rmd
  docs/tutorials/r/charRnnModel.md
Labels: pr-awaiting-review

#12668 Add documents for two new environment variables for memory pool.
  docs/faq/env_var.md
Labels: pr-awaiting-response

#12358 Fix flaky test : test_ndarray.test_order
  tests/python/unittest/test_ndarray.py
Labels: pr-awaiting-review

#12556 [MXNET-951] Python dockerfiles built on pip binaries and build/release script
  docker/docker-python/Dockerfile.mxnet.python.cpu
  docker/docker-python/Dockerfile.mxnet.python.cpu.mkl
  docker/docker-python/Dockerfile.mxnet.python.gpu.cu80
  docker/docker-python/Dockerfile.mxnet.python.gpu.cu80.mkl
  docker/docker-python/Dockerfile.mxnet.python.gpu.cu90
  docker/docker-python/Dockerfile.mxnet.python.gpu.cu90.mkl
  docker/docker-python/Dockerfile.mxnet.python.gpu.cu92
  docker/docker-python/Dockerfile.mxnet.python.gpu.cu92.mkl
  docker/docker-python/README.md
  docker/docker-python/build_python_dockerfile.sh
  docker/docker-python/test_mxnet.py
Labels: pr-awaiting-testing
