Repository apache/mxnet, pull requests merged in 2018-10, with the labels that each got.

#12688 Enable test_gluon.test_export
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-review

#12685 Update contribute.md
  docs/community/contribute.md
Labels: pr-awaiting-review

#12709 Update proposal_target.py
  example/rcnn/symnet/proposal_target.py
Labels: Doc, pr-awaiting-review

#12664 [MXNET-637] Multidimensional LSTM example for MXNetR
  R-package/vignettes/MultidimLstm.Rmd
  docs/tutorials/r/MultidimLstm.md
  tests/tutorials/test_sanity_tutorials.py
Labels: pr-awaiting-review

#12714 Fix static / dynamic linking of gperftools and jemalloc
  Makefile
  make/config.mk
Labels: pr-awaiting-merge

#12716 Disable test batchnorm slice
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-merge

#12694 [MXNET-860] Use emplace where helpful
  .clang-tidy
  src/c_api/c_api_executor.cc
  src/c_api/c_api_ndarray.cc
  src/c_api/c_predict_api.cc
  src/io/iter_mnist.cc
  src/kvstore/comm_tree.h
  src/nnvm/legacy_json_util.cc
  src/nnvm/legacy_op_util.cc
  src/operator/control_flow.cc
  src/operator/custom/custom.cc
  src/operator/custom/native_op-inl.h
  src/operator/custom/ndarray_op-inl.h
  src/operator/optimizer_op.cc
  src/operator/rnn-inl.h
Labels: pr-awaiting-review

#12659 [MXNET-953] Correct ASAN cflags flag
  CMakeLists.txt
Labels: pr-awaiting-review

#12730 [MXNET-860] Remove std::moves that have no affect
  .clang-tidy
  src/executor/infer_graph_attr_pass.cc
  src/operator/tensor/elemwise_unary_op.h
Labels: pr-awaiting-review

#12701 Add FListInputNames attribute to softmax_cross_entropy
  src/operator/loss_binary_op.cc
  tests/python/unittest/test_operator.py
Labels: Operator, pr-awaiting-review

#12706 [MXNET-908] Speed up travis builds to avoid timeouts
  .travis.yml
  ci/travis/install.sh
Labels: pr-work-in-progress

#12733 Throw exception if MXSymbolInferShape fails.
  scala-package/native/src/main/native/org_apache_mxnet_native_c_api.cc
Labels: Clojure, Scala, pr-awaiting-review

#12711 change numpy version to 1.15.2 in python install_requires
  ci/docker/install/docs_requirements
  ci/docker/install/ubuntu_python.sh
  docs/install/requirements.txt
  python/setup.py
Labels: Installation, pr-awaiting-review

#12718 Reenable test_gluon.test_conv
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-review

#12726 Fix failing GPU test on single GPU host (kvstore) #10977
  tests/python/gpu/test_kvstore_gpu.py
Labels: pr-awaiting-merge, pr-awaiting-testing

#12722 Add support for CUDNN_TENSOR_OP_MATH_ALLOW_CONVERSION
  docs/faq/env_var.md
  src/common/cuda_utils.h
  src/operator/cudnn_rnn-inl.h
  src/operator/nn/cudnn/cudnn_convolution-inl.h
Labels: pr-awaiting-review

#12693 Fix small bugs in the benchmark of control flow operators.
  benchmark/python/control_flow/rnn.py
Labels: pr-awaiting-review

#12636 [MXNET-982] Provide example to illustrate usage of CSVIter in C++ API
  cpp-package/example/mlp_csv.cpp
  cpp-package/example/mnist_to_csv.py
  cpp-package/example/unittests/unit_test_mlp_csv.sh
Labels: pr-work-in-progress

#12725 [Backport] Fix for test_ndarray.test_order failing on CI (v1.3.x)
  tests/python/unittest/test_ndarray.py
Labels: pr-awaiting-merge, pr-awaiting-testing

#12637 [MXNET-912] Refactoring ctc loss operator
  3rdparty/ctc_include/LICENSE
  3rdparty/ctc_include/contrib/moderngpu/LICENSE
  3rdparty/ctc_include/contrib/moderngpu/include/device/ctaloadbalance.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/ctamerge.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/ctascan.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/ctasearch.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/ctasegreduce.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/ctasegscan.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/ctasegsort.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/ctasortedsearch.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/devicetypes.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/deviceutil.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/intrinsics.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/loadstore.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/serialsets.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/device/sortnetwork.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/mgpudevice.cuh
  3rdparty/ctc_include/contrib/moderngpu/include/mgpuenums.h
  3rdparty/ctc_include/contrib/moderngpu/include/util/static.h
  3rdparty/ctc_include/detail/cpu_ctc.h
  3rdparty/ctc_include/detail/ctc_helper.h
  3rdparty/ctc_include/detail/gpu_ctc.h
  3rdparty/ctc_include/detail/gpu_ctc_kernels.h
  3rdparty/ctc_include/detail/hostdevice.h
  python/mxnet/gluon/loss.py
  src/operator/contrib/ctc_loss-inl.h
  src/operator/nn/ctc_loss-inl.h
  src/operator/nn/ctc_loss.cc
  src/operator/nn/ctc_loss.cu
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#12595 Add resnet50-v1 to benchmark_score
  example/image-classification/benchmark_score.py
  example/image-classification/symbols/resnetv1.py
Labels: pr-awaiting-review

#12758 [MXNET-716][MIRROR #12723] Scala Benchmark Extension pack
  scala-package/examples/scripts/benchmark/run_text_charrnn_bm.sh
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/benchmark/README.md
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/benchmark/ScalaInferenceBenchmark.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/objectdetector/SSDClassifierExample.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/rnn/TestCharRnn.scala
  scala-package/examples/src/test/scala/org/apache/mxnetexamples/benchmark/ScalaInferenceBenchmarkSuite.scala
Labels: Scala, pr-awaiting-review

#12757 [MXNET-915] Java Inference API core wrappers and tests
  scala-package/core/pom.xml
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/Context.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/DType.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/IO.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/Shape.scala
  scala-package/core/src/test/java/org/apache/mxnet/javaapi/ContextTest.java
  scala-package/core/src/test/java/org/apache/mxnet/javaapi/DTypeTest.java
  scala-package/core/src/test/java/org/apache/mxnet/javaapi/IOTest.java
  scala-package/core/src/test/java/org/apache/mxnet/javaapi/ShapeTest.java
Labels: Scala, pr-awaiting-review

#12643 Add mkl-dnn to docker install method
  docs/install/index.md
Labels: pr-awaiting-review

#12663 Improve mkldnn fallback.
  src/executor/attach_op_execs_pass.cc
  src/operator/quantization/dequantize.cc
  src/operator/quantization/mkldnn/mkldnn_quantized_pooling.cc
  src/operator/quantization/quantize.cc
  src/operator/quantization/requantize.cc
Labels: pr-awaiting-review

#12740 Fix regression in MKLDNN caused by PR 12019
  src/operator/tensor/elemwise_binary_op_basic.cc
  src/operator/tensor/matrix_op.cc
Labels: pr-awaiting-review

#12766 Updated CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: pr-awaiting-merge

#12777 Use modern onnx API to load model from file
  docs/tutorials/onnx/export_mxnet_to_onnx.md
  python/mxnet/contrib/onnx/onnx2mx/import_model.py
  python/mxnet/contrib/onnx/onnx2mx/import_to_gluon.py
Labels: ONNX, pr-awaiting-review

#12702 Update env_var.md
  docs/faq/env_var.md
Labels: Doc, pr-awaiting-review

#12719 fix cnn visualization tutorial
  docs/tutorials/vision/cnn_visualization.md
Labels: Example, Gluon, pr-awaiting-response

#12625 [MXNET-979] Add fix_beta support in BatchNorm
  python/mxnet/gluon/nn/basic_layers.py
  src/operator/nn/batch_norm-inl.h
  src/operator/nn/batch_norm.cc
  src/operator/nn/batch_norm.cu
  src/operator/nn/cudnn/cudnn_batch_norm-inl.h
  tests/python/gpu/test_operator_gpu.py
  tests/python/mkl/test_mkldnn.py
  tests/python/unittest/test_operator.py
  tests/python/unittest/test_sparse_operator.py
Labels: Gluon, Operator, pr-awaiting-review

#12639 [MXNET-947] Expand scala imclassification example with resnet
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/README.md
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/TrainModel.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/datasets/MnistIter.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/datasets/SyntheticDataIter.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/models/Lenet.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/models/MultiLayerPerceptron.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/models/Resnet.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/util/Trainer.scala
  scala-package/examples/src/test/scala/org/apache/mxnetexamples/imclassification/IMClassificationExampleSuite.scala
Labels: pr-work-in-progress

#12776 R fix metric shape
  R-package/R/metric.R
Labels: R, pr-awaiting-review

#12365 Adagrad optimizer with row-wise learning rate
  docs/api/python/index.md
  docs/api/python/optimization/contrib.md
  python/mxnet/optimizer/__init__.py
  python/mxnet/optimizer/contrib.py
  python/mxnet/optimizer/optimizer.py
  python/mxnet/test_utils.py
  src/operator/contrib/optimizer_op-inl.h
  src/operator/contrib/optimizer_op.cc
  src/operator/contrib/optimizer_op.cu
  tests/python/unittest/test_contrib_optimizer.py
  tests/python/unittest/test_optimizer.py
Labels: pr-awaiting-response

#12793 Fix mismatch shapes
  python/mxnet/ndarray/ndarray.py
Labels: Operator, pr-work-in-progress

#12572 Make Gluon download function to be atomic
  python/mxnet/gluon/utils.py
  tests/python/unittest/test_gluon_utils.py
Labels: pr-awaiting-review

#12717 Re-enables test_operator.test_dropout
  tests/python/unittest/test_operator.py
Labels: Flaky, pr-awaiting-response

#12697 [MXNET -1004] Poisson NegativeLog Likelihood loss
  docs/api/python/gluon/loss.md
  python/mxnet/gluon/loss.py
  tests/python/unittest/test_loss.py
Labels: Gluon, pr-awaiting-review

#12704 [MXNet-1002] Add GluonCV and NLP tookits, Keras, and developer wiki to navigation
  docs/_static/mxnet-theme/navbar.html
Labels: Doc, pr-awaiting-review

#12794 fixed symbols naming in RNNCell, LSTMCell, GRUCell
  python/mxnet/gluon/rnn/rnn_cell.py
  tests/python/unittest/test_gluon_rnn.py
Labels: Gluon, RNN, pr-work-in-progress

#12816 [MXNET-984] Add Java NDArray and introduce Java Operator Builder class
  Makefile
  scala-package/core/pom.xml
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/Context.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/NDArray.scala
  scala-package/core/src/test/java/org/apache/mxnet/javaapi/NDArrayTest.java
  scala-package/macros/src/main/scala/org/apache/mxnet/javaapi/JavaNDArrayMacro.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/utils/CToScalaUtils.scala
  scala-package/macros/src/test/scala/org/apache/mxnet/MacrosSuite.scala
Labels: Java, pr-awaiting-review

#12724 simplify mac mkldnn build
  MKLDNN_README.md
  Makefile
  docs/install/osx_setup.md
  make/osx.mk
Labels: MKLDNN, pr-awaiting-review

#12545 Change the way NDArrayIter handle the last batch
  python/mxnet/io/__init__.py
  python/mxnet/io/io.py
  python/mxnet/io/utils.py
  tests/python/unittest/test_io.py
Labels: pr-awaiting-review

#11952 [MXNET-707] Add unit test for mxnet to coreml converter
  .travis.yml
  ci/travis/install.sh
  tools/coreml/test/test_mxnet_converter.py
  tools/coreml/test/test_mxnet_image.py
  tools/coreml/test/test_mxnet_models.py
Labels: Build, Converter, Test, pr-awaiting-response

#12796 Add embedding to print_summary
  python/mxnet/visualization.py
  tests/python/unittest/test_viz.py
Labels: Visualization, pr-awaiting-testing

#12759 Scala Docs - Replace old Symbol api usages
  docs/api/scala/model.md
  docs/api/scala/module.md
  docs/api/scala/symbol.md
  docs/tutorials/scala/mnist.md
Labels: Scala, pr-awaiting-review

#12731 [MXNET-892] ONNX export/import: DepthToSpace, SpaceToDepth operators
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/_import_helper.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  tests/python-pytest/onnx/export/mxnet_export_test.py
  tests/python-pytest/onnx/export/onnx_backend_test.py
  tests/python-pytest/onnx/import/test_cases.py
Labels: ONNX, pr-awaiting-review

#12832 R install instructions update for macOS
  docs/install/index.md
  docs/install/osx_setup.md
Labels: Doc, R, pr-awaiting-review

#12811 Fixed __setattr__ method of _MXClassPropertyMetaClass
  python/mxnet/base.py
Labels: Gluon, pr-awaiting-review

#12826 Fixed regex for matching platform type in Scala Benchmark scripts
  scala-package/examples/scripts/benchmark/run_image_inference_bm.sh
  scala-package/examples/scripts/benchmark/run_text_charrnn_bm.sh
Labels: Scala, pr-awaiting-review

#12841 Added context object to run TestCharRnn example
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/rnn/TestCharRnn.scala
Labels: Scala

#12656 [MXNET-703] Show perf info for TensorRT during tests
  ci/docker/runtime_functions.sh
Labels: pr-awaiting-review

#12230 Update Operator Implementation Tutorial
  docs/faq/add_op_in_backend.md
  tests/python/unittest/test_operator.py
Labels: Backend, Doc, pr-awaiting-review

#12798 Fix Flaky Topk
  src/operator/tensor/ordering_op-inl.h
  src/operator/tensor/sort_op-inl.cuh
  src/operator/tensor/sort_op.h
  tests/python/unittest/test_ndarray.py
Labels: Flaky, Operator, pr-awaiting-review

#12738 Add Psroipooling CPU implementation
  src/operator/contrib/psroi_pooling.cc
  tests/python/unittest/test_operator.py
Labels: Operator, pr-awaiting-review

#12646 ONNX export: Fully connected operator w/o bias, ReduceSum, Square
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  tests/python-pytest/onnx/export/mxnet_export_test.py
  tests/python-pytest/onnx/export/onnx_backend_test.py
Labels: pr-awaiting-review

#12867 Undefined name: load_model() --> utils.load_model()
  tools/coreml/test/test_mxnet_image.py
Labels: pr-awaiting-review

#12785 [MXNET-906] ONNX export/import: Selu
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/_import_helper.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  tests/python-pytest/onnx/export/onnx_backend_test.py
  tests/python-pytest/onnx/import/test_cases.py
Labels: ONNX, pr-awaiting-review

#12860 Sparse support for logic ops
  src/operator/tensor/elemwise_binary_scalar_op.h
  src/operator/tensor/elemwise_binary_scalar_op_logic.cc
  src/operator/tensor/elemwise_binary_scalar_op_logic.cu
  tests/python/unittest/test_sparse_ndarray.py
Labels: Operator, pr-work-in-progress

#12698 add a tutorial for the subgraph API.
  docs/tutorials/c++/subgraphAPI.md
  docs/tutorials/index.md
  tests/tutorials/test_tutorials.py
Labels: Doc, pr-awaiting-response

#12808 MKL-DNN Quantization Examples and README
  MKLDNN_README.md
  docs/faq/perf.md
  example/quantization/README.md
  example/quantization/imagenet_gen_qsym_mkldnn.py
  example/quantization/imagenet_inference.py
  example/ssd/benchmark_score.py
  example/ssd/config/config.py
  example/ssd/evaluate.py
  example/ssd/evaluate/evaluate_net.py
  example/ssd/quantization.py
  python/mxnet/initializer.py
  tests/python/mkl/test_subgraph.py
Labels: Doc, Gluon, MKLDNN, pr-awaiting-review

#12840 [MXNET-1033] Fix a bug in MultiboxTarget GPU implementation
  src/operator/contrib/multibox_target.cu
  tests/python/gpu/test_operator_gpu.py
  tests/python/unittest/test_contrib_operator.py
Labels: Operator, pr-awaiting-testing

#12031 [MXNET-1107] Fix CPUPinned unexpected behaviour
  include/mxnet/base.h
  src/common/cuda_utils.h
  src/common/rtc.cc
  src/engine/stream_manager.h
  src/kvstore/comm.h
  src/kvstore/comm_tree.h
  src/kvstore/kvstore_nccl.h
  src/storage/storage.cc
Labels: Backend, Bug, pr-work-in-progress

#12647 NativeResource Management in Scala
  scala-package/core/pom.xml
  scala-package/core/src/main/scala/org/apache/mxnet/Executor.scala
  scala-package/core/src/main/scala/org/apache/mxnet/KVStore.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Model.scala
  scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala
  scala-package/core/src/main/scala/org/apache/mxnet/NativeResource.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Optimizer.scala
  scala-package/core/src/main/scala/org/apache/mxnet/ResourceScope.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Symbol.scala
  scala-package/core/src/main/scala/org/apache/mxnet/io/MXDataIter.scala
  scala-package/core/src/main/scala/org/apache/mxnet/optimizer/SGD.scala
  scala-package/core/src/test/scala/org/apache/mxnet/NativeResourceSuite.scala
  scala-package/core/src/test/scala/org/apache/mxnet/ResourceScopeSuite.scala
  scala-package/examples/scripts/run_train_mnist.sh
Labels: pr-work-in-progress

#12879 add/update infer_range docs
  python/mxnet/ndarray/ndarray.py
  python/mxnet/symbol/symbol.py
  scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala
  scala-package/core/src/main/scala/org/apache/mxnet/Symbol.scala
  src/operator/tensor/init_op.h
Labels: Doc, pr-awaiting-review

#12810 Add index_copy() operator
  src/operator/contrib/index_copy-inl.h
  src/operator/contrib/index_copy.cc
  src/operator/contrib/index_copy.cu
  tests/python/unittest/test_operator.py
Labels: Operator, pr-awaiting-review

#12780 Add more models to benchmark_score
  benchmark/python/gluon/benchmark_gluon.py
  example/image-classification/benchmark_score.py
Labels: Benchmark, Gluon, pr-work-in-progress

#12735 [MXNET-1025] Add Jetpack 3.3 support to Jetson
  ci/docker/Dockerfile.build.jetson
Labels: pr-awaiting-review

#12848 Fix Batch input issue with Scala Benchmark
  scala-package/core/src/test/scala/org/apache/mxnet/ShapeSuite.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/InferBase.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/benchmark/ScalaInferenceBenchmark.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/imageclassifier/ImageClassifierExample.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/infer/objectdetector/SSDClassifierExample.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/rnn/TestCharRnn.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/ImageClassifier.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/ObjectDetector.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/Predictor.scala
  scala-package/infer/src/test/scala/org/apache/mxnet/infer/ImageClassifierSuite.scala
Labels: Scala

#12790 Extending the DCGAN example implemented by gluon API to provide a more straight-forward evaluation on the generated image
  example/gluon/DCGAN/README.md
  example/gluon/DCGAN/__init__.py
  example/gluon/DCGAN/dcgan.py
  example/gluon/DCGAN/inception_score.py
  example/gluon/dcgan.py
  example/gluon/sn_gan/data.py
  example/gluon/sn_gan/model.py
  example/gluon/sn_gan/train.py
  example/gluon/sn_gan/utils.py
Labels: Example, Gluon, pr-awaiting-review

#12782 [MXNET-674] Speed up GPU builds in CI
  ci/docker/runtime_functions.sh
Labels: CI, pr-work-in-progress

#12773 [MXNET-1017] Updating the readme file for cpp-package and adding readme file for example directory.
  cpp-package/README.md
  cpp-package/example/README.md
Labels: C++, Doc

#12905 Fail the broken link job when broken links are found
  tests/nightly/broken_link_checker_test/test_broken_links.py
Labels: CI, pr-awaiting-review

#12896 Fix typo in formula in docstring for GRU cell and layer and add clarification to description (gluon.rnn)
  CONTRIBUTORS.md
  python/mxnet/gluon/rnn/rnn_cell.py
  python/mxnet/gluon/rnn/rnn_layer.py
Labels: pr-awaiting-testing

#12928 Ignore generated scala files.
  scala-package/.gitignore
Labels: pr-awaiting-merge

#12882 use ResourceScope in Model/Trainer/FeedForward.scala
  scala-package/core/src/main/scala/org/apache/mxnet/FeedForward.scala
  scala-package/core/src/main/scala/org/apache/mxnet/NativeResource.scala
  scala-package/core/src/main/scala/org/apache/mxnet/ResourceScope.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/TrainModel.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/util/Trainer.scala
Labels: Scala, pr-awaiting-review

#12942 Fix the operator API documentation
  src/operator/contrib/multibox_target-inl.h
Labels: pr-awaiting-review

#12927 Fix indpt[0] and dtype for take(csr)
  src/operator/tensor/indexing_op.cc
  tests/python/unittest/test_sparse_ndarray.py
Labels: pr-awaiting-review

#12908 getnnz operator
  docs/api/python/ndarray/contrib.md
  src/operator/contrib/nnz.cc
  tests/python/unittest/test_sparse_ndarray.py
Labels: pr-awaiting-review

#12912 Add bytearray support back to imdecode (#12855, #12868)
  python/mxnet/image/image.py
  tests/python/unittest/test_image.py
Labels: pr-awaiting-review

#12960 Update tree lstm example
  example/gluon/tree_lstm/README.md
  example/gluon/tree_lstm/dataset.py
  example/gluon/tree_lstm/fetch_and_preprocess.sh
  example/gluon/tree_lstm/main.py
  example/gluon/tree_lstm/scripts/download.py
Labels: pr-awaiting-review

#12929 Update bilstm integer array sorting example
  example/bi-lstm-sort/README.md
  example/bi-lstm-sort/bi-lstm-sort.ipynb
  example/bi-lstm-sort/gen_data.py
  example/bi-lstm-sort/infer_sort.py
  example/bi-lstm-sort/lstm.py
  example/bi-lstm-sort/lstm_sort.py
  example/bi-lstm-sort/rnn_model.py
  example/bi-lstm-sort/sort_io.py
Labels: pr-awaiting-review

#12921 Fix the bug of assigning large integer to NDArray
  src/operator/tensor/matrix_op-inl.h
  tests/python/unittest/test_ndarray.py
Labels: pr-awaiting-review

#12410 Refactor mkldnn test files
  tests/cpp/include/test_mkldnn.h
  tests/cpp/operator/mkldnn.cc
  tests/cpp/operator/mkldnn_operator_test.cc
  tests/cpp/operator/mkldnn_test.cc
Labels: pr-awaiting-testing

#12804 CudnnFind() usage improvements
  CONTRIBUTORS.md
  docs/faq/env_var.md
  include/mxnet/base.h
  include/mxnet/c_api.h
  perl-package/AI-MXNetCAPI/mxnet.i
  python/mxnet/context.py
  src/c_api/c_api.cc
  src/operator/nn/cudnn/cudnn_algoreg-inl.h
  src/operator/nn/cudnn/cudnn_convolution-inl.h
  src/operator/nn/cudnn/cudnn_deconvolution-inl.h
  src/storage/pooled_storage_manager.h
  tests/python/gpu/test_gluon_gpu.py
Labels: CUDA, pr-awaiting-review

#12835 [MXNET-984] Java NDArray Documentation Generation
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/NDArray.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/APIDocGenerator.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/javaapi/JavaNDArrayMacro.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/utils/CToScalaUtils.scala
Labels: Doc, Java, Scala, pr-awaiting-review

#12919 fix mac r install and windows python build from source docs
  docs/install/index.md
Labels: pr-awaiting-review

#12963 First pass at adding JavaDocs for new java api classes
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/Context.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/IO.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/NDArray.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/javaapi/ObjectDetector.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/javaapi/Predictor.scala
Labels: pr-awaiting-review

#12986 enable batchnorm unit tests
  tests/python/unittest/test_gluon.py
Labels: CUDA, Disabled test, pr-awaiting-review

#12750 [MXNET -1030] Cosine Embedding Loss
  docs/api/python/gluon/loss.md
  python/mxnet/gluon/loss.py
  tests/python/unittest/test_loss.py
Labels: Gluon, pr-awaiting-review

#12969 [MXNET-1160] add Java build/run example
  docs/tutorials/scala/mxnet_java_install_and_run_examples.md
  scala-package/mxnet-demo/java-demo/Makefile
  scala-package/mxnet-demo/java-demo/README.md
  scala-package/mxnet-demo/java-demo/bin/java_sample.sh
  scala-package/mxnet-demo/java-demo/bin/run_od.sh
  scala-package/mxnet-demo/java-demo/pom.xml
  scala-package/mxnet-demo/java-demo/src/main/java/sample/HelloWorld.java
  scala-package/mxnet-demo/java-demo/src/main/java/sample/ObjectDetection.java
  scala-package/mxnet-demo/scala-demo/Makefile
  scala-package/mxnet-demo/scala-demo/README.md
  scala-package/mxnet-demo/scala-demo/bin/demo.sh
  scala-package/mxnet-demo/scala-demo/bin/run_im.sh
  scala-package/mxnet-demo/scala-demo/pom.xml
  scala-package/mxnet-demo/scala-demo/src/main/scala/sample/HelloWorld.scala
  scala-package/mxnet-demo/scala-demo/src/main/scala/sample/ImageClassificationExample.scala
  tests/tutorials/test_sanity_tutorials.py
Labels: Java, pr-awaiting-testing

#13034 sample_like operators
  python/mxnet/base.py
  src/operator/random/sample_op.cc
  src/operator/random/sample_op.cu
  src/operator/random/sample_op.h
  tests/python/unittest/test_random.py
Labels: Operator, pr-awaiting-review

#12992 [MXNET-1179] Enforce deterministic algorithms in convolution layers
  src/operator/nn/cudnn/cudnn_convolution-inl.h
  src/operator/nn/cudnn/cudnn_deconvolution-inl.h
  src/operator/nn/cudnn/cudnn_pooling-inl.h
Labels: Operator, pr-awaiting-review

#13042 Add a deprecate message
  src/operator/nn/ctc_loss.cc
Labels: pr-awaiting-merge

#13045 la_op_inline.h to la_op-inl.h for consistency
  src/operator/linalg_impl.h
  src/operator/tensor/control_flow_op.h
  src/operator/tensor/elemwise_binary_broadcast_op_basic.cc
  src/operator/tensor/elemwise_binary_broadcast_op_basic.cu
  src/operator/tensor/elemwise_binary_broadcast_op_extended.cu
  src/operator/tensor/elemwise_binary_broadcast_op_logic.cu
  src/operator/tensor/elemwise_binary_op_extended.cc
  src/operator/tensor/elemwise_scatter_op.h
  src/operator/tensor/la_op-inl.h
  src/operator/tensor/la_op.cc
  src/operator/tensor/la_op.cu
  src/operator/tensor/ordering_op-inl.h
  src/operator/tensor/ordering_op.cu
Labels: Operator, pr-awaiting-review

#12974 Improve clojure tutorial
  contrib/clojure-package/examples/tutorial/project.clj
  contrib/clojure-package/examples/tutorial/src/tutorial/kvstore.clj
  contrib/clojure-package/examples/tutorial/src/tutorial/module.clj
  contrib/clojure-package/examples/tutorial/src/tutorial/ndarray.clj
  contrib/clojure-package/examples/tutorial/src/tutorial/symbol.clj
  docs/api/clojure/ndarray.md
  docs/api/clojure/symbol.md
Labels: Clojure, pr-awaiting-review

#13066 Remove unused header from engine.h
  include/mxnet/engine.h
Labels: Backend, pr-awaiting-review
