Repository apache/mxnet, pull requests merged in 2019-01, with the labels that each got.

#13725 disable error checking when building old versions
  docs/build_version_doc/build_all_version.sh
Labels: CI, Website, pr-awaiting-merge

#13530 Integrate MKLDNN Conv1d and support 3d layout
  src/ndarray/ndarray.cc
  src/operator/nn/activation.cc
  src/operator/nn/mkldnn/mkldnn_act.cc
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_base.cc
  src/operator/nn/mkldnn/mkldnn_convolution.cc
  src/operator/subgraph/mkldnn/mkldnn_conv.cc
  tests/python/unittest/test_operator.py
Labels: MKLDNN, Operator, pr-awaiting-review

#13681 Making MKL-DNN default on MXNet master
  CMakeLists.txt
  Makefile
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  docs/mxdoc.py
Labels: pr-awaiting-review

#13741 update FAQ index page to use relative links
  docs/faq/index.md
Labels: Website, pr-awaiting-merge

#13619 [MXNET-1231] Allow not using Some in the Scala operators
  scala-package/core/src/main/scala/org/apache/mxnet/util/OptionConversion.scala
  scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/Classifier.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/GeneratorBase.scala
  scala-package/macros/src/main/scala/org/apache/mxnet/utils/CToScalaUtils.scala
  scala-package/macros/src/test/scala/org/apache/mxnet/MacrosSuite.scala
Labels: Scala, pr-awaiting-review

#13695 fix bug in profiler tutorial when using cpu
  docs/tutorials/python/profiler.md
Labels: pr-awaiting-review

#13682 Add a docs build (with error checking) option to the dev_menu.py script
  dev_menu.py
Labels: Build, Doc, pr-awaiting-review

#13088 make ROIAlign support position-sensitive pooling
  src/operator/contrib/roi_align-inl.h
  src/operator/contrib/roi_align.cc
  src/operator/contrib/roi_align.cu
  tests/python/unittest/test_operator.py
Labels: Operator, pr-awaiting-review

#13620 add examples and fix the dependency problem
  ci/docker/runtime_functions.sh
  scala-package/mxnet-demo/java-demo/Makefile
  scala-package/mxnet-demo/java-demo/README.md
  scala-package/mxnet-demo/java-demo/bin/java_sample.sh
  scala-package/mxnet-demo/java-demo/bin/run_od.sh
  scala-package/mxnet-demo/java-demo/src/main/java/mxnet/HelloWorld.java
  tests/nightly/Jenkinsfile
Labels: CI, Scala

#13754 [DOC] Fix Adam optimizer doc with bias correction term
  python/mxnet/optimizer/optimizer.py
Labels: Doc, pr-awaiting-review

#13764 Less cudaGet/SetDevice calls in Gluon execution
  src/common/cuda_utils.h
  src/engine/stream_manager.h
  src/engine/threaded_engine_pooled.cc
  src/kvstore/comm.h
  src/kvstore/comm_tree.h
  src/storage/cpu_device_storage.h
  src/storage/gpu_device_storage.h
  src/storage/naive_storage_manager.h
  src/storage/pinned_memory_storage.h
  src/storage/pooled_storage_manager.h
  src/storage/storage.cc
Labels: Gluon, pr-awaiting-review

#13775 Fix USE_MKLDNN check in Makefile
  Makefile
  make/config.mk
Labels: Build, Makefile

#13778 Fix document for building with MKL-DNN on OS X (Mac)
  MKLDNN_README.md
  docs/install/osx_setup.md
Labels: Installation, MKLDNN

#13766 Fixed mailing list addresses that were swapped (doc change only)
  docs/community/mxnet_channels.md
Labels: pr-awaiting-review

#13597 [MXNET-1255] update hybridize documentation
  docs/tutorials/gluon/hybrid.md
Labels: pr-awaiting-merge

#13535 [MXNET-244] Work around likely compiler bug on nested inlines and temporary acces…
  src/operator/c_lapack_api.cc
  src/operator/c_lapack_api.h
  tests/cpp/operator/krprod_test.cc
Labels: pr-awaiting-review

#13761 Use curl to download sample data instead of wget.
  scala-package/examples/scripts/infer/imageclassifier/get_resnet_18_data.sh
  scala-package/examples/scripts/infer/imageclassifier/get_resnet_data.sh
  scala-package/examples/scripts/infer/objectdetector/get_ssd_data.sh
  scala-package/examples/scripts/rnn/run_test_charrnn.sh
  scala-package/examples/scripts/rnn/run_train_charrnn.sh
Labels: Scala, pr-awaiting-review

#13727 fix memory corruption in gluoncv ssd training
  src/operator/contrib/bounding_box-inl.h
Labels: Backend, pr-awaiting-response

#13703 Remove attributes clear on TRT nodes for GetOptimizedSymbol
  src/executor/trt_graph_executor.cc
Labels: pr-awaiting-review

#13338 [CI] Add CPU C++ test stage
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_unix_cpu
Labels: pr-awaiting-testing

#13793 add license info for js files
  LICENSE
  docs/_static/js/auto_module_index.js
  docs/_static/js/clipboard.js
  docs/_static/js/copycode.js
  docs/_static/js/docversion.js
  docs/_static/js/navbar.js
  docs/_static/js/options.js
  docs/_static/js/page.js
  docs/_static/js/search.js
  docs/_static/js/sidebar.js
Labels: Licenses, Website

#13450 [MXNET-862] Basic maven jenkins pipeline
  Makefile
  ci/Jenkinsfile_utils.groovy
  ci/build.py
  ci/docker/install/ubuntu_scala.sh
  ci/docker/runtime_functions.sh
  ci/docker_cache.py
  ci/publish/Jenkinsfile
  scala-package/.gitignore
  scala-package/dev/build.sh
  scala-package/dev/buildkey.py
  scala-package/dev/compile-mxnet-backend.sh
  scala-package/dev/deploy.sh
  scala-package/dev/test.sh
  scala-package/packageTest/Makefile
Labels: CI, Java, Maven, Scala, pr-awaiting-review

#13797 update license for tvm dependencies
  LICENSE
Labels: Licenses

#13796 fix website redirection issues
  docs/build_version_doc/artifacts/.htaccess
Labels: Website

#13413 fix for params with no dims in onnx
  python/mxnet/contrib/onnx/onnx2mx/import_onnx.py
  tests/python-pytest/onnx/test_models.py
Labels: ONNX, pr-awaiting-review

#13769 Clojure example for fixed label-width captcha recognition
  contrib/clojure-package/examples/captcha/.gitignore
  contrib/clojure-package/examples/captcha/README.md
  contrib/clojure-package/examples/captcha/captcha_example.png
  contrib/clojure-package/examples/captcha/gen_captcha.py
  contrib/clojure-package/examples/captcha/get_data.sh
  contrib/clojure-package/examples/captcha/project.clj
  contrib/clojure-package/examples/captcha/src/captcha/consts.clj
  contrib/clojure-package/examples/captcha/src/captcha/infer_ocr.clj
  contrib/clojure-package/examples/captcha/src/captcha/train_ocr.clj
  contrib/clojure-package/examples/captcha/test/captcha/train_ocr_test.clj
Labels: Clojure, pr-awaiting-review

#13808 Update LICENSE File with subcomponents
  LICENSE
  contrib/clojure-package/examples/infer/imageclassifier/src/infer/imageclassifier_example.clj
  docs/_static/selectlang.js
  perl-package/AI-MXNet-Gluon-Contrib/META.yml
  perl-package/AI-MXNet-Gluon-ModelZoo/META.yml
  perl-package/AI-MXNet/META.yml
  perl-package/AI-MXNetCAPI/META.yml
  perl-package/AI-NNVMCAPI/META.yml
  readthedocs.yml
  snapcraft.yaml
  tests/nightly/apache_rat_license_check/rat-excludes
  tools/license_header.py
  tools/pip/MANIFEST.in
Labels: Licenses

#13819 Add new Maven build for Scala package
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_unix_cpu
  contrib/clojure-package/README.md
  scala-package/examples/src/test/scala/org/apache/mxnetexamples/cnntextclassification/CNNClassifierExampleSuite.scala
  scala-package/examples/src/test/scala/org/apache/mxnetexamples/infer/imageclassifier/ImageClassifierExampleSuite.scala
  scala-package/examples/src/test/scala/org/apache/mxnetexamples/multitask/MultiTaskSuite.scala
  scala-package/examples/src/test/scala/org/apache/mxnetexamples/profiler/ProfilerSuite.scala
  scala-package/spark/README.md
  tests/jenkins/run_test.sh
  tests/jenkins/run_test_amzn_linux_gpu.sh
  tests/jenkins/run_test_ubuntu.sh
Labels: Scala, pr-awaiting-review

#13806 ONNX ops: norm exported and lpnormalization imported
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/_import_helper.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  tests/python-pytest/onnx/test_cases.py
  tests/python-pytest/onnx/test_node.py
Labels: ONNX, pr-awaiting-review

#13777 Remove useless code
  src/operator/nn/mkldnn/mkldnn_base-inl.h
Labels: MKLDNN

#13708 Fixing a symlink issue with R install
  docs/install/index.md
Labels: R, pr-awaiting-response

#13676 [MXNET-880] ONNX export: Random uniform, Random normal, MaxRoiPool
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  tests/python-pytest/onnx/test_node.py
Labels: ONNX, pr-awaiting-review

#13821 onnx export ops
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  tests/python-pytest/onnx/backend_test.py
  tests/python-pytest/onnx/test_node.py
Labels: ONNX, pr-awaiting-review

#13678 [MXNET-1260] Float64 DType computation support in Scala/Java
  CONTRIBUTORS.md
  contrib/clojure-package/src/org/apache/clojure_mxnet/infer.clj
  contrib/clojure-package/src/org/apache/clojure_mxnet/primitives.clj
  contrib/clojure-package/src/org/apache/clojure_mxnet/util.clj
  contrib/clojure-package/test/good-test-ndarray.clj
  contrib/clojure-package/test/org/apache/clojure_mxnet/infer/imageclassifier_test.clj
  contrib/clojure-package/test/org/apache/clojure_mxnet/infer/objectdetector_test.clj
  contrib/clojure-package/test/org/apache/clojure_mxnet/ndarray_test.clj
  contrib/clojure-package/test/org/apache/clojure_mxnet/primitives_test.clj
  contrib/clojure-package/test/org/apache/clojure_mxnet/util_test.clj
  scala-package/core/src/main/scala/org/apache/mxnet/Base.scala
  scala-package/core/src/main/scala/org/apache/mxnet/LibInfo.scala
  scala-package/core/src/main/scala/org/apache/mxnet/MX_PRIMITIVES.scala
  scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala
  scala-package/core/src/main/scala/org/apache/mxnet/io/MXDataIter.scala
  scala-package/core/src/main/scala/org/apache/mxnet/io/NDArrayIter.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/NDArray.scala
  scala-package/core/src/test/java/org/apache/mxnet/javaapi/NDArrayTest.java
  scala-package/core/src/test/scala/org/apache/mxnet/IOSuite.scala
  scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/TrainModel.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/datasets/SyntheticDataIter.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/models/Lenet.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/models/MultiLayerPerceptron.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/models/Resnet.scala
  scala-package/examples/src/test/scala/org/apache/mxnetexamples/imclassification/IMClassificationExampleSuite.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/Classifier.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/ImageClassifier.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/Predictor.scala
  scala-package/infer/src/main/scala/org/apache/mxnet/infer/javaapi/Predictor.scala
  scala-package/infer/src/test/scala/org/apache/mxnet/infer/ClassifierSuite.scala
  scala-package/infer/src/test/scala/org/apache/mxnet/infer/ImageClassifierSuite.scala
  scala-package/infer/src/test/scala/org/apache/mxnet/infer/PredictorSuite.scala
  scala-package/native/src/main/native/org_apache_mxnet_native_c_api.cc
  scala-package/native/src/main/native/org_apache_mxnet_native_c_api.h
Labels: Scala, pr-awaiting-review

#13794 [MXNET-1263] Unit Tests for Java Predictor and Object Detector APIs
  scala-package/core/pom.xml
  scala-package/infer/pom.xml
  scala-package/infer/src/test/java/org/apache/mxnet/infer/javaapi/ObjectDetectorOutputTest.java
  scala-package/infer/src/test/java/org/apache/mxnet/infer/javaapi/ObjectDetectorTest.java
  scala-package/infer/src/test/java/org/apache/mxnet/infer/javaapi/PredictorTest.java
  scala-package/pom.xml
Labels: Java, pr-awaiting-review

#13820 Fix scala doc build break for v1.3.1
  docs/mxdoc.py
Labels: Scala, pr-awaiting-review

#13830 Remove MXNET_STORAGE_FALLBACK_LOG_VERBOSE warning from test_autograd.py
  tests/python/unittest/test_autograd.py
Labels: pr-awaiting-review

#13809 Add Local test stage and option to jump directly to menu item from co…
  dev_menu.py
Labels: pr-awaiting-review

#13814 Removes unnecessary graphics-drivers ppa repository
  ci/docker/install/ubuntu_nvidia.sh
Labels: pr-awaiting-merge

#13803 Improve license_header tool by only traversing files under revision c…
  tools/license_header.py
Labels: pr-awaiting-review

#13758 Disable flaky test: test_softmin
  tests/python/unittest/test_operator.py
Labels: Flaky, Python, Test

#13590 fix Makefile for rpkg
  Makefile
  R-package/DESCRIPTION
Labels: R, pr-awaiting-review

#13818 [CI] Prevent timeouts when rebuilding containers with docker.
  ci/docker_cache.py
  ci/jenkins/Jenkinsfile_centos_cpu
  ci/jenkins/Jenkinsfile_centos_gpu
  ci/jenkins/Jenkinsfile_clang
  ci/jenkins/Jenkinsfile_edge
  ci/jenkins/Jenkinsfile_miscellaneous
  ci/jenkins/Jenkinsfile_sanity
  ci/jenkins/Jenkinsfile_unix_cpu
  ci/jenkins/Jenkinsfile_unix_gpu
  ci/jenkins/Jenkinsfile_website
  ci/jenkins/Jenkinsfile_windows_cpu
  ci/jenkins/Jenkinsfile_windows_gpu
  docs/Jenkinsfile
Labels: Scala, pr-awaiting-review

#12498 Code modification for testcases of various network models in directory example
  example/bayesian-methods/README.md
  example/bayesian-methods/bdk_demo.py
  example/fcn-xs/README.md
  example/fcn-xs/fcn_xs.py
  example/rcnn/README.md
  example/rcnn/demo.py
  example/rcnn/test.py
  example/rcnn/train.py
Labels: Example, pr-awaiting-review

#13852 Fix Tree Reduction on new instance type p3dn.24xlarge
  src/kvstore/comm_tree.h
  src/kvstore/gpu_topology.h
Labels: pr-awaiting-review

#13865 Modifying clojure CNN text classification example
  contrib/clojure-package/examples/cnn-text-classification/README.md
  contrib/clojure-package/examples/cnn-text-classification/src/cnn_text_classification/classifier.clj
  contrib/clojure-package/examples/cnn-text-classification/src/cnn_text_classification/data_helper.clj
  contrib/clojure-package/examples/cnn-text-classification/test/cnn_text_classification/classifier_test.clj
Labels: Clojure

#13850 adding tolerance to flaky test
  tests/python-pytest/onnx/test_node.py
Labels: ONNX, pr-awaiting-review

#13826 Fix cpp examples build on Mac.
  cpp-package/example/Makefile
Labels: pr-awaiting-review

#13188 Fix launch bounds in spatial transformer
  src/operator/spatial_transformer.cu
Labels: Operator, pr-awaiting-merge

#13849 Update example scripts classpath.
  scala-package/examples/scripts/benchmark/run_image_inference_bm.sh
  scala-package/examples/scripts/benchmark/run_java_inference_bm.sh
  scala-package/examples/scripts/benchmark/run_text_charrnn_bm.sh
  scala-package/examples/scripts/customop/run_customop.sh
  scala-package/examples/scripts/customop/run_customopwithrtc.sh
  scala-package/examples/scripts/infer/imageclassifier/run_classifier_example.sh
  scala-package/examples/scripts/infer/objectdetector/run_ssd_example.sh
  scala-package/examples/scripts/infer/objectdetector/run_ssd_java_example.sh
  scala-package/examples/scripts/infer/predictor/run_predictor_java_example.sh
  scala-package/examples/scripts/module/mnist_mlp.sh
  scala-package/examples/scripts/module/run_sequential_module.sh
  scala-package/examples/scripts/neuralstyle_end2end/run_test_end2end.sh
  scala-package/examples/scripts/neuralstyle_end2end/run_train_end2end.sh
  scala-package/examples/scripts/profiler/run_profiler_matmul.sh
  scala-package/examples/scripts/profiler/run_profiler_ndarray.sh
  scala-package/examples/scripts/rnn/run_lstm_bucketing.sh
  scala-package/examples/scripts/rnn/run_test_charrnn.sh
  scala-package/examples/scripts/rnn/run_train_charrnn.sh
  scala-package/examples/scripts/run_cnntextclassification.sh
  scala-package/examples/scripts/run_gan_mnist.sh
  scala-package/examples/scripts/run_multitask.sh
  scala-package/examples/scripts/run_neuralstyle.sh
  scala-package/examples/scripts/run_train_mnist.sh
Labels: pr-awaiting-merge

#13823 [MXNET-1177]Adding Scala Demo to be run as a part of Nightly CI
  ci/docker/runtime_functions.sh
  scala-package/mxnet-demo/java-demo/Makefile
  scala-package/mxnet-demo/java-demo/README.md
  scala-package/mxnet-demo/java-demo/pom.xml
  scala-package/mxnet-demo/scala-demo/Makefile
  scala-package/mxnet-demo/scala-demo/README.md
  scala-package/mxnet-demo/scala-demo/pom.xml
  tests/nightly/Jenkinsfile
Labels: Scala, pr-awaiting-review

#13872 Set CODEOWNERS for Julia package
  CODEOWNERS
Labels: pr-awaiting-merge

#13840 [CI][URGENT] Fix permissions of ci/docker/install/ubuntu_publish.sh
  ci/docker/install/ubuntu_publish.sh
Labels: pr-awaiting-review

#13842 Avoid adding SegfaultLogger if process already has sig handler.
  src/initialize.cc
Labels: pr-awaiting-review

#13889 fix the GPU flavor problem for Scala
  scala-package/deploy/pom.xml
  scala-package/pom.xml
Labels: pr-awaiting-review

#13877 Fix SN-GAN example doc
  example/README.md
  example/gluon/sn_gan/train.py
Labels: pr-awaiting-review

#13868 update Spectral Normalization Code
  example/gluon/sn_gan/model.py
Labels: pr-awaiting-review

#13887 Temporarily disable website builds
  ci/jenkins/Jenkinsfile_website
Labels: pr-awaiting-merge

#13615 Added logging to GitHub commit status publishing
  ci/Jenkinsfile_utils.groovy
Labels: pr-awaiting-merge

#13762 [MXNET-1274] Add a test for SGLD optimizer with comparisons for set noise seeds.
  tests/python/unittest/test_optimizer.py
Labels: pr-awaiting-merge

#13845 [v1.4.x] export exception handling APIs in MXNet
  include/mxnet/c_api_error.h
  src/c_api/c_api_common.h
Labels: pr-awaiting-merge

#13745 Fix the order of error term's operands
  python/mxnet/gluon/loss.py
Labels: Gluon, pr-awaiting-merge

#13882 [v1.4.x] fix ssd quantization script error (#13843)
  example/quantization/README.md
  example/ssd/README.md
  example/ssd/quantization.py
Labels: pr-awaiting-review

#13730 Add mkldnn OP for slice
  src/operator/nn/mkldnn/mkldnn_slice-inl.h
  src/operator/nn/mkldnn/mkldnn_slice.cc
  src/operator/tensor/matrix_op-inl.h
  src/operator/tensor/matrix_op.cc
  src/operator/tensor/slice-inl.h
Labels: MKLDNN, Operator, pr-awaiting-review

#13683 fix bug in nag optimizer
  python/mxnet/optimizer/optimizer.py
  tests/python/unittest/test_optimizer.py
Labels: pr-work-in-progress

#13900 [v1.4.x] fix memory corruption in gluoncv ssd training
  src/operator/contrib/bounding_box-inl.h
Labels: pr-awaiting-review

#13557 Fix BatchNorm converter for CoreML when fix_gamma=True
  tools/coreml/converter/_layers.py
  tools/coreml/test/test_mxnet_converter.py
Labels: Converter, CoreML, pr-awaiting-review

#13860 Doc fixes for beta website.
  R-package/R/context.R
  R-package/R/model.R
  R-package/R/optimizer.R
  R-package/R/rnn.graph.R
  src/operator/optimizer_op.cc
  src/operator/tensor/elemwise_unary_op_basic.cc
Labels: pr-awaiting-review

#13901 Update profiler doc
  src/c_api/c_api_profile.cc
Labels: pr-awaiting-review

#13911 Fix for test always returning true
  tests/python/unittest/test_random.py
Labels: pr-awaiting-merge

#13828 Add error checking for cpp examples.
  cpp-package/example/alexnet.cpp
  cpp-package/example/googlenet.cpp
  cpp-package/example/inception_bn.cpp
  cpp-package/example/lenet_with_mxdataiter.cpp
  cpp-package/example/mlp_cpu.cpp
  cpp-package/example/mlp_gpu.cpp
  cpp-package/example/resnet.cpp
  cpp-package/example/test_score.cpp
  cpp-package/example/utils.h
Labels: pr-awaiting-review

#13832 add ccache to docs build
  ci/docker/runtime_functions.sh
Labels: pr-awaiting-merge

#13912 Java install info update
  docs/install/index.md
Labels: Java, Website, pr-awaiting-review

#13871 Julia: fix `argmax`/`argmin` for NDArray
  julia/src/ndarray.jl
  julia/test/unittest/ndarray.jl
Labels: pr-awaiting-merge

#13922 Support populating errors back to MXNet engine in callback
  include/mxnet/engine.h
  src/engine/naive_engine.cc
  src/engine/threaded_engine.cc
  src/engine/threaded_engine.h
Labels: pr-awaiting-review

#13927 Fix document build
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkinsfile_website
Labels: CI, pr-awaiting-review

#12485 test_ImageRecordIter_seed_augmentation flaky test fix
  src/io/image_aug_default.cc
  src/io/image_iter_common.h
  src/io/iter_image_recordio_2.cc
  tests/python/unittest/test_io.py
Labels: pr-awaiting-merge

#13921 Version switching user experience improvements
  docs/_static/js/docversion.js
  docs/_static/searchtools_custom.js
  docs/build_version_doc/artifacts/.htaccess
Labels: Website

#13932 [v1.4.x] Support populating errors back to MXNet engine in callback
  include/mxnet/engine.h
  src/engine/naive_engine.cc
  src/engine/threaded_engine.cc
  src/engine/threaded_engine.h
Labels: pr-awaiting-merge

#13894 Julia: fix filename quoting in docstring
  julia/src/util.jl
Labels: Julia, pr-awaiting-review

#13893 disable default MKLDNN for cross compilation
  CMakeLists.txt
Labels: Build, CMake, MKLDNN, pr-awaiting-review

#13905 [v1.4.x] mkldnn s8 conv API change for 1.4.x branch
  include/mxnet/ndarray.h
  src/ndarray/ndarray.cc
  src/operator/subgraph/mkldnn/mkldnn_conv.cc
Labels: pr-awaiting-review

#13934 Julia: deprecate `mx.empty`, replace it with `UndefInitializer` constructor
  julia/NEWS.md
  julia/docs/src/user-guide/overview.md
  julia/src/MXNet.jl
  julia/src/deprecated.jl
  julia/src/io.jl
  julia/src/kvstore.jl
  julia/src/model.jl
  julia/src/ndarray.jl
  julia/src/random.jl
  julia/test/unittest/bind.jl
  julia/test/unittest/io.jl
  julia/test/unittest/kvstore.jl
  julia/test/unittest/ndarray.jl
  julia/test/unittest/random.jl
Labels: Julia, NDArray

#13549 Runtime feature detection
  CMakeLists.txt
  Makefile
  cmake/ChooseBlas.cmake
  include/mxnet/base.h
  include/mxnet/c_api.h
  include/mxnet/io.h
  include/mxnet/mxfeatures.h
  python/mxnet/gluon/utils.py
  python/mxnet/mxfeatures.py
  src/c_api/c_api.cc
  src/c_api/c_api_symbolic.cc
  src/mxfeatures.cc
  tests/python/unittest/test_features.py
Labels: pr-awaiting-merge

#13888 Reduce verbosity of container builds (wget output)
  ci/docker/install/ubuntu_clang.sh
  ci/docker/install/ubuntu_julia.sh
  ci/docker/install/ubuntu_llvm.sh
  ci/docker/install/ubuntu_mkl.sh
Labels: pr-awaiting-merge

#13624 Nightly Tests For Clojure
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_unix_cpu
  contrib/clojure-package/examples/infer/imageclassifier/src/infer/imageclassifier_example.clj
  contrib/clojure-package/examples/infer/objectdetector/images/marcel.jpg
  contrib/clojure-package/examples/infer/objectdetector/src/infer/objectdetector_example.clj
  contrib/clojure-package/examples/infer/objectdetector/test/infer/objectdetector_example_test.clj
  contrib/clojure-package/integration-tests.sh
Labels: Clojure, pr-work-in-progress

#13811 Add erfinv operator for calculating inverse error function
  docs/api/python/ndarray/ndarray.md
  docs/api/python/symbol/symbol.md
  src/operator/contrib/erfinv-inl.h
  src/operator/mshadow_op.h
  src/operator/operator_tune.cc
  src/operator/tensor/elemwise_unary_op_basic.cc
  src/operator/tensor/elemwise_unary_op_basic.cu
  tests/nightly/apache_rat_license_check/rat-excludes
  tests/python/unittest/test_operator.py
  tools/license_header.py
Labels: pr-awaiting-review

#13935 [Clojure] Update project.clj file to use the snapshots repo to be able to pull
  contrib/clojure-package/README.md
  contrib/clojure-package/project.clj
Labels: Clojure, pr-awaiting-review

#13937 Julia: add windows-cpu build
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_windows_cpu
  ci/windows/test_jl07_cpu.ps1
  ci/windows/test_jl10_cpu.ps1
  julia/.gitignore
  julia/Project.toml
  julia/REQUIRE
  julia/appveyor.yml
  julia/deps/build.jl
  julia/src/util.jl
  tests/nightly/apache_rat_license_check/rat-excludes
  tools/license_header.py
Labels: CI, Julia, pr-awaiting-review

#13687 split_v2 operator
  python/mxnet/ndarray/ndarray.py
  python/mxnet/symbol/symbol.py
  src/operator/tensor/matrix_op-inl.h
  src/operator/tensor/matrix_op.cc
  src/operator/tensor/matrix_op.cu
  tests/python/unittest/test_ndarray.py
  tests/python/unittest/test_operator.py
Labels: Operator, pr-awaiting-review

#13916 Static build for Python
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_unix_cpu
  ci/publish/README.md
  ci/publish/python/build.sh
  tools/staticbuild/README.md
  tools/staticbuild/build_wheel.sh
Labels: pr-awaiting-review

#13346 Aggregate SGD
  cpp-package/scripts/OpWrapperGenerator.py
  docs/faq/env_var.md
  python/mxnet/gluon/trainer.py
  python/mxnet/model.py
  python/mxnet/optimizer/optimizer.py
  src/operator/optimizer_op-inl.h
  src/operator/optimizer_op.cc
  src/operator/optimizer_op.cu
  tests/python/unittest/test_gluon_trainer.py
  tests/python/unittest/test_module.py
Labels: pr-awaiting-review

#13632 Gradient multiplier (contrib) operator
  include/mxnet/op_attr_types.h
  src/operator/contrib/gradient_multiplier_op.cc
  src/operator/contrib/gradient_multiplier_op.cu
  tests/python/unittest/test_contrib_operator.py
Labels: Operator, pr-awaiting-review

#13411 Gluon end to end tutorial
  docs/tutorial_utils/data/oxford_102_flower_dataset.py
  docs/tutorials/c++/mxnet_cpp_inference_tutorial.md
  docs/tutorials/gluon/gluon_from_experiment_to_deployment.md
  tests/tutorials/test_sanity_tutorials.py
  tests/tutorials/test_tutorials.py
Labels: pr-work-in-progress

#13980 Use CPUPinned context in ImageRecordIOParser2
  src/io/image_iter_common.h
  src/io/iter_image_recordio_2.cc
Labels: pr-awaiting-review

#13990 [v1.4.x] Use CPUPinned context in ImageRecordIOParser2
  src/io/image_iter_common.h
  src/io/iter_image_recordio_2.cc
Labels: pr-awaiting-merge

#13985 Added optional parameters to BilinearResize2D to do relative scaling
  src/operator/contrib/bilinear_resize-inl.h
  tests/python/unittest/test_operator.py
Labels: Operator, pr-awaiting-merge

#12690 [MXNET-1000] get Ndarray real value and form it from a NDArray
  scala-package/core/src/main/scala/org/apache/mxnet/MX_PRIMITIVES.scala
  scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala
  scala-package/core/src/test/scala/org/apache/mxnet/NDArraySuite.scala
Labels: Scala, pr-work-in-progress

#13903 mkldnn s8 conv API change for master
  include/mxnet/ndarray.h
  src/ndarray/ndarray.cc
  src/operator/subgraph/mkldnn/mkldnn_conv.cc
Labels: MKLDNN, pr-awaiting-review

#12399 ONNX export: Add Crop, Deconvolution and fix the default stride of Pooling to 1
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_cases.py
Labels: ONNX, pr-awaiting-testing

#12983 Sample python bilinear initializer at integral points in y-direction
  python/mxnet/initializer.py
  tests/python/unittest/test_init.py
Labels: Python, pr-awaiting-merge

#13311 [MXNET-703] Minor refactor of TensorRT code
  src/executor/onnx_to_tensorrt.cc
  src/executor/trt_graph_executor.cc
  src/operator/contrib/nnvm_to_onnx-inl.h
  src/operator/contrib/nnvm_to_onnx.cc
Labels: pr-awaiting-review

#13984 Python BucketingModule bind() with grad_req = 'add'
  python/mxnet/module/bucketing_module.py
  tests/python/unittest/test_module.py
Labels: Python, pr-awaiting-review

#13880 MXNET-1295 Adding integer index support to Sequence* family of operators.
  python/mxnet/test_utils.py
  src/operator/sequence_last-inl.h
  src/operator/sequence_last.cc
  src/operator/sequence_last.cu
  src/operator/sequence_mask-inl.h
  src/operator/sequence_mask.cc
  src/operator/sequence_mask.cu
  src/operator/sequence_reverse-inl.h
  src/operator/sequence_reverse.cc
  src/operator/sequence_reverse.cu
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#13784 Disable flaky test: test_negative_binomial_generator
  tests/python/unittest/test_random.py
Labels: Flaky, Python, Test, pr-awaiting-merge

#13963 Fix website error pages
  docs/build_version_doc/artifacts/.htaccess
  docs/build_version_doc/artifacts/404.html
  docs/build_version_doc/artifacts/api.html
  docs/build_version_doc/artifacts/index.html
  docs/build_version_doc/update_all_version.sh
  docs/conf.py
  docs/error/404.md
  docs/error/api.md
  docs/mxdoc.py
Labels: Website

#13983 build docs with CPP package
  docs/mxdoc.py
Labels: C++, Website

#13979 [MXNET-1232] fix demo and add Eclipse support
  ci/docker/runtime_functions.sh
  docs/install/java_setup.md
  scala-package/mxnet-demo/java-demo/Makefile
  scala-package/mxnet-demo/java-demo/README.md
  scala-package/mxnet-demo/java-demo/pom.xml
  scala-package/mxnet-demo/scala-demo/Makefile
  scala-package/mxnet-demo/scala-demo/README.md
  scala-package/mxnet-demo/scala-demo/pom.xml
Labels: Java, Scala, pr-awaiting-review

#13873 fix compile error in debug mode
  src/kvstore/kvstore_nccl.h
Labels: KVStore, pr-awaiting-review

#14015 website publish updates
  docs/mxdoc.py
  docs/settings.ini
Labels: Website

#13994 Return value docs for nd.random.* and sym.random.*
  CONTRIBUTORS.md
  python/mxnet/ndarray/random.py
  python/mxnet/symbol/random.py
Labels: Doc, Python, pr-awaiting-review

#13890 Improve bulking in Gluon
  include/mxnet/base.h
  src/engine/stream_manager.h
  src/engine/threaded_engine.h
  src/imperative/cached_op.cc
  src/imperative/imperative_utils.h
Labels: pr-awaiting-review

#14007 Fix inconsistent handling for FResourceRequestEx for imperative and symbolic executor
  include/mxnet/op_attr_types.h
  src/executor/attach_op_resource_pass.cc
Labels: Doc, pr-work-in-progress

#13807 [MXNET-1180] Java Image API
  scala-package/core/pom.xml
  scala-package/core/src/main/scala/org/apache/mxnet/Image.scala
  scala-package/core/src/main/scala/org/apache/mxnet/NDArray.scala
  scala-package/core/src/main/scala/org/apache/mxnet/javaapi/Image.scala
  scala-package/core/src/test/java/org/apache/mxnet/javaapi/ImageTest.java
  scala-package/examples/pom.xml
  scala-package/examples/src/main/java/org/apache/mxnetexamples/javaapi/infer/predictor/PredictorExample.java
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/Util.scala
  scala-package/examples/src/test/java/org/apache/mxnetexamples/javaapi/infer/predictor/PredictorExampleTest.java
  scala-package/infer/pom.xml
  scala-package/macros/src/main/scala/org/apache/mxnet/javaapi/JavaNDArrayMacro.scala
  scala-package/pom.xml
Labels: Java, pr-awaiting-review
