Repository apache/mxnet, pull requests merged in 2020-11, with the labels that each got.

#19455 Enable Numpy support for Gluon Block optimize_for
  python/mxnet/gluon/block.py
  tests/python/unittest/test_numpy_gluon.py
Labels: pr-awaiting-review

#19438 [DOC] Fix community link in readme.md
  README.md
Labels: pr-awaiting-review

#19364 Make RTC compatible with CUDA enhanced compatibility
  include/mxnet/rtc.h
  src/common/cuda/rtc.cc
  src/common/rtc.cc
Labels: pr-awaiting-review

#19470 Support both Gluon 1 and 2 in the hybrid containers
  python/mxnet/gluon/block.py
  python/mxnet/gluon/nn/basic_layers.py
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-review

#19474 Mark test_lstm_clip as flaky
  tests/python/gpu/test_gluon_gpu.py
Labels: pr-awaiting-review

#19471 [BUGFIX] CheckpointHandler verbose behavior in gluon.contrib.estimator
  python/mxnet/gluon/contrib/estimator/event_handler.py
Labels: pr-awaiting-review

#19466 [BUGFIX] Fallback to native implementation of RNN when use_sequence_length=True
  src/operator/nn/mkldnn/mkldnn_rnn-inl.h
  src/operator/rnn.cc
Labels: MKLDNN, pr-awaiting-review

#19381 numpy tril_indices large tensor fix
  src/api/operator/numpy/np_matrix_op.cc
  src/operator/numpy/np_matrix_op-inl.h
  src/operator/numpy/np_matrix_op.cc
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19475 Avoid segfault when calling __repr__ on ndarray or symbol with freed handle
  python/mxnet/_ctypes/ndarray.py
  python/mxnet/_ctypes/symbol.py
  python/mxnet/cython/ndarray.pyx
  python/mxnet/cython/symbol.pyx
  python/mxnet/ndarray/ndarray.py
  python/mxnet/numpy/multiarray.py
  python/mxnet/symbol/numpy/_symbol.py
  python/mxnet/symbol/symbol.py
Labels: pr-awaiting-review

#19346 Skip flaky memory profiler tests
  tests/python/gpu/test_profiler_gpu.py
  tests/python/unittest/test_profiler.py
Labels: pr-awaiting-review

#19478 Update LICENSE
  LICENSE
  NOTICE
  docs/static_site/src/assets/js/clipboard.js
  licenses/BOOST1_0
  licenses/BSD2
  licenses/BSD3-cmake
  licenses/MIT
  licenses/OFL1_1
  tools/license_header.py
Labels: pr-awaiting-merge

#19480 Skip test_bbox_augmenters on windows
  tests/python/unittest/test_numpy_contrib_gluon_data_vision.py
Labels: pr-awaiting-review

#19456 [1.x] Backport Enable Numpy support for Gluon Block optimize_for to v1.x
  ci/docker/install/requirements
  ci/docker/install/ubuntu_publish.sh
  python/mxnet/gluon/block.py
Labels: pr-awaiting-merge

#19482 Mark test_sparse_storage_fallback as flaky
  tests/python/unittest/test_sparse_operator.py
Labels: pr-awaiting-review

#19483 Check if backend memory has been freed in check_leak_ndarray pytest fixture
  tests/python/conftest.py
Labels: pr-awaiting-merge

#19465 Add test case for oneDNN RNN
  tests/python/mkl/test_mkldnn.py
Labels: pr-awaiting-review

#19464 [1.x] Add test case for oneDNN RNN
  tests/python/mkl/test_mkldnn.py
Labels: MKLDNN, pr-work-in-progress

#19340 [FEATURE] Enable large tensor support for insert
  src/api/operator/numpy/np_delete_op.cc
  src/api/operator/numpy/np_insert_op.cc
  src/operator/numpy/np_delete_op-inl.h
  src/operator/numpy/np_insert_op-inl.h
  src/operator/numpy/np_insert_op_scalar-inl.h
  src/operator/numpy/np_insert_op_slice-inl.h
  src/operator/numpy/np_insert_op_slice.cc
  src/operator/numpy/np_insert_op_tensor-inl.h
  src/operator/numpy/np_insert_op_tensor.cc
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19452 [DOC] Fix a typo in dataset.py
  python/mxnet/gluon/data/dataset.py
Labels: pr-awaiting-merge

#19487 [1.x, FEATURE] Allow eliminating common subexpressions when temp space is used
  src/executor/eliminate_common_expr_pass.cc
Labels: pr-awaiting-merge

#19486 [FEATURE]Allow eliminating common subexpressions when temp space is used
  src/imperative/eliminate_common_expr_pass.cc
Labels: pr-awaiting-merge

#19493 Mark test_random_gray as flaky
  tests/python/unittest/test_gluon_data_vision.py
  tests/python/unittest/test_numpy_gluon_data_vision.py
Labels: pr-awaiting-review

#19492 Mark test_batchnorm_with_type as flaky
  tests/python/gpu/test_operator_gpu.py
Labels: pr-awaiting-review

#19497 Add SiLU
  docs/python_docs/python/api/gluon/nn/index.rst
  docs/python_docs/python/tutorials/packages/gluon/blocks/activations/activations.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/activations/images/gelu.png
  docs/python_docs/python/tutorials/packages/gluon/blocks/activations/images/silu.png
  python/mxnet/gluon/nn/activations.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_numpy_gluon.py
Labels: pr-awaiting-review

#19469 Extension bug fixes
  python/mxnet/gluon/block.py
  src/c_api/c_api.cc
  src/operator/subgraph/partitioner/custom_subgraph_property.h
  tests/python/unittest/test_extensions.py
Labels: pr-awaiting-merge

#19491 Update pytest version used on CI
  ci/docker/Dockerfile.test.arm
  ci/docker/install/requirements
  docker/install/python.sh
Labels: pr-awaiting-review

#19507 Disable ENABLE_TESTCOVERAGE on CentOS 7 build
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
Labels: pr-awaiting-merge

#19501 [BUGFIX] Fix to quantization dshape bug
  python/mxnet/contrib/quantization.py
Labels: pr-work-in-progress

#19506 [v1.x] update cudnn version for cu102
  ci/docker/Dockerfile.build.ubuntu_gpu_cu102
Labels: pr-awaiting-merge

#19509 Unique names for nodes in imperative mode
  src/imperative/imperative.cc
Labels: pr-awaiting-review

#19512 [COMMUNITY] add Chaitanya Bapat as a new committer
  CONTRIBUTORS.md
Labels: Community, pr-awaiting-review

#19505 Enable coverage reports for PR diffs
  .codecov.yml
Labels: pr-awaiting-review

#19510 Mark test_gluon_bernoulli_v1 as flaky
  tests/python/unittest/test_gluon_probability_v1.py
Labels: pr-awaiting-review

#19508 Mark test_npx_batch_norm as flaky
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-review

#19514 [v1.x] Backport #19037
  tools/pip/setup.py
Labels: pr-awaiting-merge

#19513 [DOC] Fix markdown syntax for link to community guide
  CONTRIBUTORS.md
Labels: pr-awaiting-review

#18690 Optimize graph execution in presence of dynamic shape op
  include/mxnet/c_api.h
  python/mxnet/gluon/block.py
  python/mxnet/symbol/symbol.py
  src/c_api/c_api_symbolic.cc
  src/imperative/imperative_utils.h
  src/operator/control_flow.cc
  src/operator/subgraph/build_subgraph.cc
  src/operator/subgraph/static_shape_subgraph_property.cc
  src/operator/subgraph_op_common.cc
  src/operator/subgraph_op_common.h
  tests/python/unittest/test_deferred_compute.py
  tests/python/unittest/test_dynamic_shape.py
Labels: Backend, Operator, pr-awaiting-review

#19516 Fix HLS2RGBConvert
  src/operator/image/image_random-inl.h
  tests/python/unittest/test_numpy_contrib_gluon_data_vision.py
Labels: pr-awaiting-review

#19518 [COMMUNITY] Add Zhaoqi Zhu as a new committer
  CONTRIBUTORS.md
Labels: pr-awaiting-merge

#19500 fix msvc C2398 error
  src/common/cuda/rtc/vectorization-inl.h
  src/operator/fusion/fused_op.cu
Labels: pr-awaiting-review

#19522 update libcudnn from 7 to 8 for cu102
  ci/docker/install/ubuntu_cudnn.sh
Labels: pr-awaiting-review

#19525 disable graph partition by default
  python/mxnet/gluon/block.py
Labels: pr-awaiting-review

#19504 [v1.8.x] Backport extension bug fixes to v1.8.x (#19469)
  ci/docker/install/centos7_python.sh
  ci/docker/install/requirements
  ci/docker/install/ubuntu_publish.sh
  python/mxnet/gluon/block.py
  src/c_api/c_api.cc
  src/operator/subgraph/partitioner/custom_subgraph_property.h
  tests/python/unittest/test_extensions.py
Labels: pr-awaiting-merge

#19528 Fix uninitialized variable in RTC path
  src/common/cuda/rtc/half-inl.h
  src/common/cuda/rtc/vectorization-inl.h
Labels: pr-awaiting-merge

#19529 Enable Numpy Large tensor nightly tests
  ci/docker/runtime_functions.sh
  tests/nightly/JenkinsfileForBinaries
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-merge

#19531 change partitioning default to false for hybridize/optimize_for
  python/mxnet/gluon/block.py
Labels: pr-awaiting-review

#19530 Cuda 11 build fixes
  ci/build_windows.py
  src/operator/contrib/multi_lamb.cu
  src/operator/contrib/multi_lans.cu
Labels: pr-awaiting-merge

#19431 External Operators 2
  .github/workflows/os_x_staticbuild.yml
  CMakeLists.txt
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  example/extensions/lib_external_ops/CMakeLists.txt
  example/extensions/lib_external_ops/README.md
  example/extensions/lib_external_ops/init_lib.cc
  example/extensions/lib_external_ops/min_ex-inl.h
  example/extensions/lib_external_ops/min_ex.cc
  example/extensions/lib_external_ops/min_ex.cu
  example/extensions/lib_external_ops/test_loading.py
  tests/python/gpu/test_extensions_gpu.py
  tests/python/unittest/test_extensions.py
Labels: pr-awaiting-merge

#19532 [v1.x] Backport #19530
  ci/build_windows.py
  src/operator/contrib/multi_lamb.cu
Labels: pr-awaiting-review

#19533 [v1.8.x] Backport #19530
  ci/build_windows.py
  src/operator/contrib/multi_lamb.cu
Labels: pr-awaiting-review

#19386 [1.x] Move block.optimize_for backend_opts to kwargs
  example/extensions/lib_pass/README.md
  example/extensions/lib_subgraph/README.md
  example/extensions/lib_subgraph/test_subgraph.py
  python/mxnet/gluon/block.py
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-merge

#19457 [Numpy] Update fallback.py
  python/mxnet/numpy/fallback.py
  python/mxnet/numpy/multiarray.py
  tests/python/unittest/test_numpy_interoperability.py
Labels: pr-awaiting-review

#19549 Update pip.md
  docs/static_site/src/_includes/get_started/linux/python/gpu/pip.md
Labels: pr-awaiting-merge

#18625 Enable Large Tensor Support: Stage 1
  3rdparty/mshadow/mshadow/dot_engine-inl.h
  CMakeLists.txt
  ci/docker/runtime_functions.sh
  config/darwin.cmake
  config/linux.cmake
  config/linux_gpu.cmake
  src/operator/contrib/transformer.cc
  src/operator/numpy/np_insert_op_slice-inl.h
  src/operator/numpy/np_polynomial_op.cc
Labels: pr-awaiting-review

#19526 add bert-adam
  python/mxnet/optimizer/__init__.py
  python/mxnet/optimizer/adamW.py
  tests/python/gpu/test_operator_gpu.py
  tests/python/unittest/test_optimizer.py
Labels: pr-awaiting-review

#19413 [1.x] Backport Faster pointwise fusion graph pass (#19269)
  src/executor/exec_pass.h
  src/executor/graph_executor.cc
  src/executor/pointwise_fusion_pass.cc
  src/executor/simple_partition_pass.cc
  src/executor/simple_partition_pass.h
  src/imperative/cached_op.h
  src/operator/fusion/fused_op.cu
  tests/python/gpu/test_fusion.py
Labels: pr-awaiting-review

#19545 Don't declare/use CheckPvalGPU on CPU builds
  src/operator/numpy/random/np_multinomial_op.h
Labels: pr-awaiting-review

#19325 Numpy take large tensor fix
  src/operator/tensor/indexing_op.cc
  src/operator/tensor/indexing_op.h
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19419 CPU reduce kernel optimization
  src/operator/tensor/broadcast_reduce-inl.h
Labels: pr-awaiting-review

#19538 Mark test_np_average as flaky
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-merge

#19067 Fix compilation for large tensor with MKL
  3rdparty/mshadow/mshadow/base.h
  3rdparty/mshadow/mshadow/tensor.h
  cmake/ChooseBlas.cmake
  include/mxnet/base.h
  src/operator/c_lapack_api.h
  src/operator/linalg.h
  src/operator/linalg_impl.h
  src/operator/numpy/linalg/np_gesvd-inl.h
  src/operator/numpy/linalg/np_lstsq-inl.h
  src/operator/numpy/linalg/np_lstsq.cc
  src/operator/numpy/linalg/np_matrix_rank-inl.h
  src/operator/numpy/linalg/np_pinv-inl.h
  src/operator/numpy/linalg/np_solve-inl.h
  src/operator/numpy/linalg/np_tensorsolve-inl.h
  src/operator/tensor/la_op-inl.h
  src/operator/tensor/la_op.cc
  src/operator/tensor/la_op.h
Labels: MKLDNN, pr-awaiting-review

#19543 Separate backend from hybridize and refactor optimize_for kwargs
  example/extensions/lib_pass/README.md
  example/extensions/lib_pass/test_pass.py
  example/extensions/lib_subgraph/README.md
  example/extensions/lib_subgraph/test_subgraph.py
  python/mxnet/gluon/block.py
  tests/python/unittest/test_extensions.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_subgraph_op.py
Labels: pr-awaiting-review

#19557 [v1.8.x] Backport #19378
  src/engine/naive_engine.cc
  src/engine/threaded_engine_perdevice.cc
Labels: pr-awaiting-review

#19554 Mark test_np_around as flaky
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-merge

#19488 Add AMP patching of npi ops in _api_internal module
  ci/docker/runtime_functions.sh
  python/mxnet/amp/amp.py
  tests/python/gpu/test_amp_init.py
Labels: pr-awaiting-merge

#19570 Fix compilation with USE_LAPACK=0 USE_BLAS=mkl
  3rdparty/mshadow/mshadow/base.h
Labels: pr-awaiting-merge

#19523 Convert symbol to numpy symbol in Symbol class
  python/mxnet/gluon/block.py
  python/mxnet/symbol/numpy/_symbol.py
Labels: pr-awaiting-review

#19573 Update ONNX support to 1.7
  ci/docker/Dockerfile.build.ubuntu
  ci/docker/install/requirements
  ci/docker/runtime_functions.sh
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/mx2onnx/export_model.py
  python/mxnet/contrib/onnx/mx2onnx/export_onnx.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/import_model.py
  python/mxnet/contrib/onnx/onnx2mx/import_onnx.py
  python/mxnet/contrib/onnx/onnx2mx/import_to_gluon.py
  tests/python/unittest/onnx/backend.py
  tests/python/unittest/onnx/test_onnxruntime.py
Labels: pr-awaiting-review

#19553 Mark test_dropout as flaky
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-merge

#19589 Update cmake/BuildTVM.cmake to use system llvm
  cmake/BuildTVM.cmake
  contrib/tvmop/prepare_tvm.sh
Labels: pr-awaiting-review

#19421 Remove einsum overhead
  src/operator/numpy/np_einsum_op-inl.h
  src/operator/numpy/np_einsum_op.cu
Labels: pr-awaiting-review

#19578 [FEATURE] Add BN+ReLU -> BatchNormWithRelu fuse to MKLDNN backend
  src/operator/contrib/batch_norm_relu.cc
  src/operator/subgraph/mkldnn/mkldnn_bn_relu_property.h
  src/operator/subgraph/mkldnn/mkldnn_subgraph_property.cc
  tests/python/mkl/test_subgraph.py
Labels: MKLDNN, pr-awaiting-review

#19590 Mark test_cv_model_inference_onnxruntime_mobilenetv2_1_0 as flaky
  tests/python/unittest/onnx/test_onnxruntime.py
Labels: pr-awaiting-review

#19600 parametrize test_deformable_convolution
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-merge

#19596 Fix serialization bug for writing large arrays to npz
  src/serialization/cnpy.cc
  tests/python/unittest/test_numpy_ndarray.py
Labels: pr-awaiting-merge
