Repository apache/mxnet, pull requests merged in 2020-08, with the labels that each got.

#18836 Add compiled_with_cxx11_abi API
  CMakeLists.txt
  config/darwin.cmake
  config/distribution/darwin_cpu.cmake
  config/distribution/linux_cpu.cmake
  config/distribution/linux_cu100.cmake
  config/distribution/linux_cu101.cmake
  config/distribution/linux_cu102.cmake
  config/distribution/linux_cu92.cmake
  config/distribution/linux_native.cmake
  config/linux.cmake
  config/linux_gpu.cmake
  include/mxnet/c_api.h
  include/mxnet/libinfo.h
  python/mxnet/library.py
  src/c_api/c_api.cc
  src/libinfo.cc
  tests/python/unittest/test_runtime.py
Labels: pr-awaiting-review

#18708 [v1.x Backport] Fix softmax, logsoftmax failed on empty ndarray (#18602)
  src/operator/nn/log_softmax.cc
  src/operator/nn/softmax-inl.h
  src/operator/nn/softmax.cc
  src/operator/numpy/np_boolean_mask_assign.cc
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-review

#18845 Fixed python website double scroller and improve UX
  docs/python_docs/_static/mxnet.css
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css.map
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.js
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.js.map
  docs/python_docs/themes/mx-theme/src/js/sphinx_materialdesign_theme.js
  docs/python_docs/themes/mx-theme/src/scss/_root.scss
  docs/python_docs/themes/mx-theme/src/scss/layout/_layout.scss
Labels: Website

#18797 [v1.x] Mkldnn header fix v1x for nightly binaries
  CMakeLists.txt
  cd/python/pypi/pypi_package.sh
  tools/pip/setup.py
Labels: pr-awaiting-review

#18856 fix set default website version rewrite rule for cdn
  docs/static_site/src/.htaccess
Labels: Website

#18853 Fix edge case when casting gluon Block before export
  python/mxnet/gluon/parameter.py
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-review

#18777 [v1.7.x] ElementWiseSum fix for oneDNN
  src/operator/tensor/elemwise_sum.cc
  tests/python/mkl/test_mkldnn.py
Labels: MKLDNN, pr-awaiting-review

#18863 improve python api website ux - make toc sticky
  docs/python_docs/themes/mx-theme/mxtheme/layout.html
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css.map
  docs/python_docs/themes/mx-theme/src/scss/layout/_layout.scss
Labels: Website, pr-awaiting-merge

#18859 ElementWiseSum fix for oneDNN
  src/operator/tensor/elemwise_sum.cc
  tests/python/mkl/test_mkldnn.py
Labels: MKLDNN

#17815 [WIP] Add SOVERSION when build shared libmxnet.so library
  CMakeLists.txt
  cd/Jenkinsfile_utils.groovy
  cd/mxnet_lib/dynamic/Jenkins_pipeline.groovy
  cd/mxnet_lib/static/Jenkins_pipeline.groovy
  cd/utils/test_artifact_repository.py
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  tests/nightly/Jenkinsfile
  tests/nightly/JenkinsfileForBinaries
  tests/nightly/model_backwards_compatibility_check/JenkinsfileForMBCC
  tools/staticbuild/build_lib.sh
Labels: pr-awaiting-review

#18872 Re-enable the linker version scripts for binary distribution
  CMakeLists.txt
  cmake/libmxnet.sym
  cmake/libmxnet.ver
Labels: pr-awaiting-review

#18529 fix pooling_convention warning when convert model to onnx
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
Labels: ONNX, pr-awaiting-review

#17857 [Numpy] FFI: sort, argsort, vstack etc
  benchmark/python/ffi/benchmark_ffi.py
  python/mxnet/ndarray/numpy/_op.py
  python/mxnet/ndarray/numpy/random.py
  src/api/operator/numpy/np_matrix_op.cc
  src/api/operator/numpy/np_ordering_op.cc
  src/api/operator/numpy/random/np_multinomial_op.cc
  src/operator/numpy/np_matrix_op-inl.h
  src/operator/numpy/random/np_multinomial_op.h
  src/operator/tensor/ordering_op-inl.h
Labels: Numpy

#18676 [v1.7.x] backport Invoke mkldnn and cudnn BatchNorm when axis != 1 to v1.7.x
  src/operator/nn/batch_norm.cc
  src/operator/nn/batch_norm.cu
  src/operator/nn/cudnn/cudnn_batch_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_operator.py
  tests/python/unittest/test_symbol.py
Labels: pr-awaiting-review

#18758 [Gluon] Add VAE demo
  example/probability/VAE/VAE.md
  example/probability/VAE/VAE_11_0.png
  example/probability/VAE/VAE_14_0.png
Labels: pr-awaiting-review

#18857 [Fix Bug] set upper bound infinity for conv, resize, upsampling, etc.
  src/operator/contrib/bilinear_resize-inl.h
  src/operator/contrib/deformable_convolution-inl.h
  src/operator/contrib/modulated_deformable_convolution-inl.h
  src/operator/convolution_v1-inl.h
  src/operator/nn/convolution-inl.h
  src/operator/nn/deconvolution-inl.h
  src/operator/nn/upsampling-inl.h
Labels: Bug, Operator, pr-awaiting-review

#18385 Safe accumulation for computing gradient in Embedding & Take
  3rdparty/mshadow/mshadow/cuda/tensor_gpu-inl.cuh
  3rdparty/mshadow/mshadow/tensor.h
  3rdparty/mshadow/mshadow/tensor_cpu-inl.h
  3rdparty/mshadow/mshadow/tensor_gpu-inl.h
  src/operator/tensor/indexing_op.cu
  src/operator/tensor/indexing_op.h
  tests/python/gpu/test_operator_gpu.py
Labels: Backport 1.x, pr-awaiting-review, v2.0

#18885 Fix default CPU allocator memory alignment
  src/common/utils.h
  src/storage/cpu_device_storage.h
  src/storage/storage_manager_helpers.h
  tests/cpp/storage/storage_test.cc
Labels: MKLDNN

#18440 Fix backward of scalar variants of arctan2 and rarctan2 on GPU
  src/operator/numpy/np_elemwise_broadcast_op_extended.cu
Labels: pr-awaiting-review

#18779 Support extra inputs for subgraph ops
  example/extensions/lib_api/init_lib.cc
  example/extensions/lib_custom_op/gemm_lib.cc
  example/extensions/lib_custom_op/relu_lib.cu
  example/extensions/lib_custom_op/transposecsr_lib.cc
  example/extensions/lib_custom_op/transposerowsp_lib.cc
  example/extensions/lib_pass/README.md
  example/extensions/lib_pass/example_connection.png
  example/extensions/lib_pass/pass_lib.cc
  example/extensions/lib_pass/test_pass.py
  example/extensions/lib_subgraph/README.md
  example/extensions/lib_subgraph/subgraph_lib.cc
  example/extensions/lib_subgraph/test_subgraph.py
  include/mxnet/lib_api.h
  python/mxnet/gluon/block.py
  src/c_api/c_api.cc
  src/operator/subgraph/partitioner/custom_subgraph_property.h
Labels: pr-awaiting-merge

#18929 Change Partition API's options_map to std::unordered_map
  src/c_api/c_api.cc
  src/c_api/c_api_symbolic.cc
  src/operator/subgraph/partitioner/custom_subgraph_property.h
  src/operator/subgraph/subgraph_property.h
  src/operator/subgraph/tensorrt/tensorrt-inl.h
Labels: pr-awaiting-merge

#18945 Cherry-pick #18635 to v1.x (#18935)
  contrib/clojure-package/examples/bert/get_bert_data.sh
Labels: pr-awaiting-merge

#18910 [v1.x] backport remove upper bound (#18857)
  src/operator/contrib/bilinear_resize-inl.h
  src/operator/contrib/deformable_convolution-inl.h
  src/operator/contrib/modulated_deformable_convolution-inl.h
  src/operator/convolution_v1-inl.h
  src/operator/nn/convolution-inl.h
  src/operator/nn/deconvolution-inl.h
  src/operator/nn/upsampling-inl.h
Labels: Backport 1.x, v1.x

#18932 Numpy Ops Large Tensor Tests
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-merge

#18996 Fix LeakyRelu behaviour on empty input (#18934)
  src/operator/leaky_relu-inl.h
  src/operator/leaky_relu.cc
  src/operator/nn/mkldnn/mkldnn_act-inl.h
  src/operator/quantization/mkldnn/mkldnn_quantized_act.cc
  tests/python/unittest/test_smoke.py
Labels: MKLDNN

#18930 Support for fp16 in SpM x DnsM on GPU
  src/operator/tensor/dot-inl.cuh
  tests/python/gpu/test_operator_gpu.py
Labels: pr-awaiting-review
