Repository apache/mxnet, pull requests merged in 2020-05, with the labels that each got.

#18053 [Numpy] New FFIs for Operator: pad, prod
  benchmark/python/ffi/benchmark_ffi.py
  python/mxnet/ndarray/numpy/_op.py
  python/mxnet/numpy/multiarray.py
  python/mxnet/symbol/numpy/_symbol.py
  src/api/operator/numpy/np_broadcast_reduce_op_value.cc
  src/api/operator/numpy/np_pad_op.cc
  src/operator/numpy/np_broadcast_reduce_op_value.cc
  src/operator/numpy/np_broadcast_reduce_op_value.cu
  src/operator/numpy/np_pad_op-inl.h
Labels: Numpy

#18168 Improving performance of broadcast_axis on GPU
  src/operator/numpy/np_matmul_op-inl.h
  src/operator/tensor/broadcast_reduce_op.h
Labels: pr-awaiting-review

#17977 Relaxing type requirements for broadcast_like
  src/operator/tensor/broadcast_reduce_op_value.cc
  tests/python/unittest/test_operator.py
Labels: Operator, pr-awaiting-review

#18220 Cherrypick Fix nightly large_vector test caused by incorrect with_seed path (#18178)
  ci/docker/install/requirements
  tests/nightly/test_large_array.py
  tests/nightly/test_large_vector.py
  tests/python/unittest/common.py
Labels: pr-awaiting-merge, pr-awaiting-review

#18188 update website version select drop down
  docs/static_site/src/_includes/get_started/get_started.html
  docs/static_site/src/_sass/minima/_getting_started.scss
  docs/static_site/src/assets/js/options.js
Labels: pr-awaiting-merge

#18206 [v1.6.x] Backport [MKL-DNN] Integrate Conv3d and Pool3d/1d (#17884) and Fix Sanity pipeline in 1.6.x
  ci/docker/install/requirements
  src/operator/nn/convolution.cc
  src/operator/nn/mkldnn/mkldnn_act.cc
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_base.cc
  src/operator/nn/mkldnn/mkldnn_convolution.cc
  src/operator/nn/mkldnn/mkldnn_pooling-inl.h
  src/operator/nn/mkldnn/mkldnn_pooling.cc
  src/operator/nn/pooling.cc
  src/operator/quantization/mkldnn/mkldnn_quantized_pooling.cc
  src/operator/quantization/quantized_conv.cc
  src/operator/quantization/quantized_pooling.cc
  src/operator/subgraph/mkldnn/mkldnn_conv.cc
  src/operator/subgraph/mkldnn/mkldnn_conv_property.h
  src/operator/subgraph/mkldnn/mkldnn_subgraph_base-inl.h
  tests/cpp/operator/mkldnn_operator_test.cc
  tests/python/mkl/test_mkldnn.py
  tests/python/quantization/test_quantization.py
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-merge

#17846 [numpy] add op tri
  benchmark/python/ffi/benchmark_ffi.py
  python/mxnet/ndarray/numpy/_op.py
  python/mxnet/numpy/fallback.py
  python/mxnet/numpy/multiarray.py
  python/mxnet/symbol/numpy/_symbol.py
  src/api/operator/numpy/np_tri_op.cc
  src/operator/numpy/np_tri_op-inl.h
  src/operator/numpy/np_tri_op.cc
  src/operator/numpy/np_tri_op.cu
  tests/python/unittest/test_numpy_op.py
Labels: Numpy

#18243 Fix gluon link missing
  docs/python_docs/python/api/gluon/index.rst
Labels: pr-awaiting-merge

#18232 fixed overwrite of args/aux variables
  python/mxnet/symbol/symbol.py
Labels: Bug

#18238 fix when clicking version dropdown it jumps to top of the page
  docs/static_site/src/assets/js/options.js
Labels: Website, pr-awaiting-review

#18275 Fix pylint astroid sanity issue
  ci/docker/install/requirements
Labels: pr-awaiting-merge

#18203 Fix LSTM and GRU layers gradient calculations
  src/operator/rnn-inl.h
  src/operator/rnn_impl.h
  tests/python/unittest/test_gluon_rnn.py
Labels: MKLDNN

#18310 Fix MKLDNN headers missing in nightly builds
  tools/pip/setup.py
Labels: MKLDNN

#18358 [1.7.x] Fix memory leaks in Gluon
  python/mxnet/gluon/block.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_thread_local.py
Labels: Backport 1.x, R1.7.0, v1.x

#17824 [Numpy] FFI: max/min/amax/amin
  benchmark/python/ffi/benchmark_ffi.py
  python/mxnet/_numpy_op_doc.py
  python/mxnet/ndarray/numpy/_op.py
  python/mxnet/numpy/multiarray.py
  python/mxnet/symbol/numpy/_symbol.py
  python/mxnet/symbol/numpy/linalg.py
  src/api/operator/numpy/np_broadcast_reduce_op_value.cc
  src/operator/numpy/np_broadcast_reduce_op.h
  src/operator/numpy/np_broadcast_reduce_op_value.cc
  src/operator/numpy/np_broadcast_reduce_op_value.cu
Labels: Numpy

#18355 Include all mkldnn headers in CD builds
  CMakeLists.txt
  cd/python/pypi/pypi_package.sh
  tools/pip/setup.py
Labels: pr-awaiting-review

#18288 Website global search feature
  docs/static_site/src/_config.yml
  docs/static_site/src/_config_beta.yml
  docs/static_site/src/_config_prod.yml
  docs/static_site/src/_includes/head.html
  docs/static_site/src/_includes/header.html
  docs/static_site/src/_sass/globalSearch.scss
  docs/static_site/src/_sass/minima/_layout.scss
  docs/static_site/src/assets/img/search-icon.svg
  docs/static_site/src/assets/js/globalSearch.js
  docs/static_site/src/assets/main.scss
Labels: Website, pr-awaiting-merge

#18369 Replace google CDN with JQuery's own CDN
  docs/static_site/src/_includes/head.html
Labels: Website, pr-awaiting-merge

#18340 [Website 2.0] Artifact URL Adjustment
  docs/static_site/Makefile
Labels: Website, pr-awaiting-review

#18363 Fix reference cycle in gluon.Trainer
  conftest.py
  python/mxnet/gluon/parameter.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_gluon_trainer.py
Labels: pr-awaiting-review

#18326 [R] Fix incorrect website title for Symbol API in R
  docs/static_site/src/pages/api/r/docs/tutorials/symbol.md
Labels: pr-awaiting-merge

#18376 Fix reference leak in Block._children and enable reference leak tests universally
  conftest.py
  pytest.ini
  python/mxnet/gluon/block.py
  python/mxnet/gluon/contrib/nn/basic_layers.py
  python/mxnet/gluon/nn/basic_layers.py
  python/mxnet/gluon/rnn/rnn_cell.py
  tests/python/conftest.py
  tests/python/gpu/test_contrib_amp.py
  tests/python/train/test_bucketing.py
  tests/python/train/test_dtype.py
  tests/python/train/test_resnet_aug.py
  tests/python/unittest/onnx/mxnet_export_test.py
  tests/python/unittest/test_autograd.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_gluon_data.py
  tests/python/unittest/test_module.py
Labels: pr-awaiting-review

#18383 Disable test_composite_embedding_with_one_embedding
  tests/python/unittest/test_contrib_text.py
Labels: pr-awaiting-review

#18359 [1.x] Fix memory leaks in Gluon
  python/mxnet/gluon/block.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_thread_local.py
Labels: v1.x

#18236 [1.x] Pass args fix2
  python/mxnet/symbol/symbol.py
Labels: pr-awaiting-merge

#18431 [website] Redirect Chinese visitors to Apache Chinese CDN provider PART 1
  docs/static_site/src/.htaccess
Labels: Website, pr-awaiting-merge
