Repository apache/mxnet, pull requests merged in 2020-06, with the labels that each got.

#18320 Improve log_softmax op performance by using DNNL support
  src/operator/nn/log_softmax.cc
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_log_softmax.cc
  src/operator/nn/mkldnn/mkldnn_ops-inl.h
  tests/python/unittest/test_loss.py
  tests/python/unittest/test_numpy_gluon.py
  tests/python/unittest/test_operator.py
Labels: MKLDNN

#18089 Add npx op 'index_add'
  python/mxnet/_numpy_op_doc.py
  src/operator/tensor/index_add-inl.h
  src/operator/tensor/index_add_backward.cc
  src/operator/tensor/index_add_backward.cu
  src/operator/tensor/index_add_forward.cc
  src/operator/tensor/index_add_forward.cu
  tests/python/unittest/test_numpy_op.py
Labels: Numpy

#18461 Julia has changed the folder of 7z.exe.
  julia/deps/build.jl
Labels: Julia

#18473 Dynamically Generate Version Dropdown
  docs/static_site/src/_includes/get_started/get_started.html
  docs/static_site/src/_includes/header.html
  docs/static_site/src/assets/js/options.js
Labels: Website, pr-awaiting-review

#18474 Add Developer Guide Docs to MXNet Website
  docs/static_site/src/_sass/minima/_docs.scss
  docs/static_site/src/assets/img/dev_guide_profilling_1.png
  docs/static_site/src/assets/img/dev_guide_profilling_2.png
  docs/static_site/src/assets/img/dev_guide_profilling_3.png
  docs/static_site/src/assets/img/dev_guide_profilling_4.png
  docs/static_site/src/assets/img/dev_guide_profilling_5.png
  docs/static_site/src/assets/img/dev_guide_profilling_6.png
  docs/static_site/src/assets/img/dev_guide_profilling_7.png
  docs/static_site/src/pages/api/api.html
  docs/static_site/src/pages/api/developer_guide/1_github_contribution_and_PR_verification_tips.md
  docs/static_site/src/pages/api/developer_guide/debugging_and_performance_optimization_tips.md
  docs/static_site/src/pages/api/developer_guide/examine_forward_results_with_hooks.md
  docs/static_site/src/pages/api/developer_guide/exception_handing_and_custom_error_types.md
  docs/static_site/src/pages/api/developer_guide/profiling.md
Labels: Website, pr-awaiting-review

#18500 [Bug Fixed] Fix batch norm when grad_req is `add`
  src/operator/nn/batch_norm-inl.h
  src/operator/nn/batch_norm.cc
  src/operator/nn/batch_norm.cu
  src/operator/nn/cudnn/cudnn_batch_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_operator.py
Labels: Bug, Operator

#18483 Drop list support in optimize_for
  example/extensions/lib_pass/test_pass.py
  example/extensions/lib_subgraph/test_subgraph.py
  python/mxnet/gluon/block.py
  python/mxnet/symbol/symbol.py
  tests/python/unittest/test_extensions.py
  tests/python/unittest/test_subgraph_op.py
Labels: pr-awaiting-merge

#18518 [v1.x] backport #18500 - [Bug Fixed] Fix batch norm when grad_req is `add`
  src/operator/nn/batch_norm-inl.h
  src/operator/nn/batch_norm.cc
  src/operator/nn/batch_norm.cu
  src/operator/nn/cudnn/cudnn_batch_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_operator.py
Labels: Backport 1.x

#18517 [v1.7.x] backport #18500 - [Bug Fixed] Fix batch norm when grad_req is `add`
  src/operator/nn/batch_norm-inl.h
  src/operator/nn/batch_norm.cc
  src/operator/nn/batch_norm.cu
  src/operator/nn/cudnn/cudnn_batch_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_operator.py
Labels: R1.7.0

#18512 Fix Slow Site Loading Speed part2
  docs/static_site/Makefile
  docs/static_site/src/.htaccess
  docs/static_site/src/_includes/head.html
  docs/static_site/src/_sass/generalVersionDropdown.scss
  docs/static_site/src/assets/main.scss
Labels: Website, pr-awaiting-review

#18553 Create config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: pr-awaiting-review

#18324 [OpPerf] Add example of using opperf with internal op locally
  benchmark/opperf/README.md
  docs/static_site/src/pages/api/r/docs/tutorials/symbol.md
Labels: pr-awaiting-merge

#18327 update init.py with appropriate comments
  python/mxnet/__init__.py
Labels: pr-awaiting-merge

#18515 Update visualize.jl
  julia/src/visualize.jl
Labels: Julia

#18571 fix contribute page anchor position shifted
  docs/static_site/src/_sass/minima/_layout.scss
Labels: Website, pr-awaiting-review

#17734 [MXNET-889] Implement ONNX export for gluon LSTM.
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python/unittest/onnx/test_node.py
Labels: pr-awaiting-review

#18607 redirect api reference on v-master to v1.6
  docs/static_site/src/.htaccess
Labels: Website

#18587 prevent master version for installation widget
  docs/static_site/src/assets/js/options.js
Labels: Website, pr-awaiting-review

#18613 Fix Julia API reference and tutorials redirect on master
  docs/static_site/src/.htaccess
  docs/static_site/src/pages/api/api.html
Labels: Website

#18621 fix contrib ops do not render correctly
  src/operator/contrib/transformer.cc
Labels: Website, pr-awaiting-review

#17882 Improve performance of broadcast_axis on CPU
  src/operator/numpy/np_matmul_op-inl.h
  src/operator/tensor/broadcast_reduce_op.h
Labels: pr-awaiting-merge
