Repository apache/mxnet, pull requests merged in 2020-09, with the labels that each got.

#19054 [DOC][v1.7.x] Fix pip cu102link
  ci/docker/install/requirements
  tools/pip/doc/CPU_ADDITIONAL.md
Labels: pr-awaiting-merge

#19063 [FEATURE]Enable large tensor support for batch flatten
  src/operator/tensor/matrix_op-inl.h
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-merge

#19069 [1.x] Backporting #19016
  CMakeLists.txt
  Makefile
  example/extensions/lib_api/Makefile
  example/extensions/lib_api/init_lib.cc
  example/extensions/lib_custom_op/Makefile
  example/extensions/lib_custom_op/gemm_lib.cc
  example/extensions/lib_custom_op/relu_lib.cu
  example/extensions/lib_custom_op/transposecsr_lib.cc
  example/extensions/lib_custom_op/transposerowsp_lib.cc
  example/extensions/lib_pass/Makefile
  example/extensions/lib_pass/pass_lib.cc
  example/extensions/lib_subgraph/Makefile
  example/extensions/lib_subgraph/subgraph_lib.cc
  include/mxnet/lib_api.h
  src/lib_api.cc
Labels: v1.x

#19093 Fix typo in ISSUE_TEMPLATE config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: pr-awaiting-merge

#18606 Use chain.from_iterable in 2 modules
  ci/build.py
  tools/license_header.py
Labels: pr-awaiting-review

#19092 [COMMUNITY] Add mention of mirroring of RFC issues to dev@
  .github/ISSUE_TEMPLATE/rfc.md
Labels: pr-awaiting-merge

#15872 Add a contrib operator for dynamic reshape
  src/operator/contrib/dynamic_shape_ops-inl.h
  src/operator/contrib/dynamic_shape_ops.cc
  tests/python/unittest/test_contrib_operator.py
Labels: Operator, pr-awaiting-review

#14882 empty list cannot be cleared issue fixed.
  example/ctc/multiproc_data.py
Labels: pr-awaiting-review

#16131 Fix for duplicate subgraph inputs/outputs
  src/operator/subgraph/build_subgraph.cc
  src/operator/subgraph/subgraph_property.h
  tests/python/unittest/test_subgraph_op.py
Labels: pr-awaiting-review

#19103 Improve createOpState for custom ops
  example/extensions/lib_custom_op/gemm_lib.cc
  example/extensions/lib_custom_op/relu_lib.cc
  example/extensions/lib_custom_op/test_gemm.py
  example/extensions/lib_custom_op/test_relu.py
  example/extensions/lib_custom_op/transposecsr_lib.cc
  example/extensions/lib_custom_op/transposerowsp_lib.cc
  example/extensions/lib_subgraph/subgraph_lib.cc
  include/mxnet/lib_api.h
  src/c_api/c_api.cc
  src/lib_api.cc
Labels: pr-awaiting-review

#19120 [DOC] 4. set v1.7 website as default version
  docs/static_site/src/.htaccess
Labels: Website

#19115 [Community] add @ciyongch as a new committer
  CONTRIBUTORS.md
Labels: Community

#19106 Elemwise binary op backward fix
  src/operator/tensor/elemwise_binary_op.h
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19136 [COMMUNITY] add Jackie Wu as a new PPMC member
  CONTRIBUTORS.md
Labels: Community, pr-awaiting-review

#19134 Updated lib_api.h version
  include/mxnet/lib_api.h
Labels: pr-awaiting-merge

#19117 [1.x] Backport #19103
  example/extensions/lib_custom_op/gemm_lib.cc
  example/extensions/lib_custom_op/relu_lib.cu
  example/extensions/lib_custom_op/transposecsr_lib.cc
  example/extensions/lib_custom_op/transposerowsp_lib.cc
  example/extensions/lib_subgraph/subgraph_lib.cc
  include/mxnet/lib_api.h
  src/c_api/c_api.cc
  src/lib_api.cc
Labels: pr-awaiting-review

#19112 [1.x] Backport Fix for duplicate subgraph inputs/outputs (#16131)
  example/extensions/lib_subgraph/test_subgraph.py
  src/c_api/c_api_symbolic.cc
  src/operator/subgraph/build_subgraph.cc
  src/operator/subgraph/partitioner/custom_subgraph_property.h
  src/operator/subgraph/subgraph_property.h
  tests/python/unittest/test_subgraph_op.py
Labels: pr-awaiting-merge

#19099 [1.x] Backport of intgemm #17559
  CMakeLists.txt
  LICENSE
  Makefile
  include/mxnet/base.h
  src/operator/contrib/intgemm/intgemm_fully_connected_op.cc
  src/operator/contrib/intgemm/max_absolute_op.cc
  src/operator/contrib/intgemm/prepare_data_op.cc
  src/operator/contrib/intgemm/prepare_weight_op.cc
  src/operator/contrib/intgemm/take_weight_op.cc
  src/storage/cpu_device_storage.h
  tests/python/unittest/test_contrib_intgemm.py
Labels: pr-awaiting-merge

#19034 Switch to GCC 9 for static build
  cd/mxnet_lib/static/Jenkins_pipeline.groovy
  ci/docker/Dockerfile.build.centos7
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  docs/static_site/src/pages/get_started/build_from_source.md
  tools/dependencies/protobuf.sh
  tools/pip/setup.py
Labels: pr-awaiting-review

#19142 [1.x][FEATURE] CUDA graphs support
  docs/static_site/src/pages/api/faq/env_var.md
  include/mxnet/op_attr_types.h
  src/executor/attach_op_execs_pass.cc
  src/executor/cuda_graphs.h
  src/executor/exec_pass.h
  src/executor/graph_executor.cc
  src/imperative/imperative_utils.h
  src/operator/contrib/adamw.cu
  src/operator/nn/dropout.cu
  src/operator/numpy/linalg/np_eig.cu
  src/operator/numpy/linalg/np_eigvals.cu
  src/operator/numpy/linalg/np_norm_backward.cu
  src/operator/numpy/linalg/np_norm_forward.cu
  src/operator/numpy/np_boolean_mask_assign.cu
  src/operator/numpy/np_constraint_check.cu
  src/operator/numpy/np_percentile_op.cu
  src/operator/numpy/random/np_bernoulli_op.cu
  src/operator/numpy/random/np_exponential_op.cu
  src/operator/numpy/random/np_gamma_op.cu
  src/operator/numpy/random/np_multinomial_op.cu
  src/operator/numpy/random/np_normal_op.cu
  src/operator/numpy/random/np_pareto_op.cu
  src/operator/numpy/random/np_power_op.cu
  src/operator/numpy/random/np_rayleigh_op.cu
  src/operator/numpy/random/np_weibull_op.cu
  src/operator/tensor/indexing_op.cu
  tests/python/gpu/test_gluon_gpu.py
Labels: pr-awaiting-review

#19191 [COMMUNITY] add Manu Seth as a new committer
  CONTRIBUTORS.md
Labels: Community

#19196 Updated v1.x to version 1.9 after branching v1.8.x
  R-package/DESCRIPTION
  contrib/clojure-package/examples/bert/project.clj
  contrib/clojure-package/examples/captcha/project.clj
  contrib/clojure-package/examples/cnn-text-classification/project.clj
  contrib/clojure-package/examples/gan/project.clj
  contrib/clojure-package/examples/imclassification/project.clj
  contrib/clojure-package/examples/infer/imageclassifier/project.clj
  contrib/clojure-package/examples/infer/objectdetector/project.clj
  contrib/clojure-package/examples/infer/predictor/project.clj
  contrib/clojure-package/examples/module/project.clj
  contrib/clojure-package/examples/multi-label/project.clj
  contrib/clojure-package/examples/neural-style/project.clj
  contrib/clojure-package/examples/pre-trained-models/project.clj
  contrib/clojure-package/examples/profiler/project.clj
  contrib/clojure-package/examples/rnn/project.clj
  contrib/clojure-package/examples/tutorial/project.clj
  contrib/clojure-package/examples/visualization/project.clj
  contrib/clojure-package/project.clj
  docs/static_site/src/pages/api/scala/docs/tutorials/mxnet_scala_on_intellij.md
  example/extensions/lib_api/init_lib.cc
  example/extensions/lib_custom_op/gemm_lib.cc
  example/extensions/lib_custom_op/relu_lib.cu
  example/extensions/lib_custom_op/transposecsr_lib.cc
  example/extensions/lib_custom_op/transposerowsp_lib.cc
  example/extensions/lib_pass/pass_lib.cc
  example/extensions/lib_subgraph/subgraph_lib.cc
  include/mxnet/base.h
  julia/NEWS.md
  python/mxnet/libinfo.py
  scala-package/README.md
  scala-package/mxnet-demo/java-demo/README.md
  scala-package/mxnet-demo/java-demo/pom.xml
  scala-package/mxnet-demo/scala-demo/pom.xml
  scala-package/pom.xml
  snapcraft.yaml
Labels: pr-awaiting-merge

#19220 Python level HybridBlock export API
  python/mxnet/gluon/block.py
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-merge

#19209 [BUGFIX]Fix cuDNN dropout reproducibility
  include/mxnet/resource.h
  src/operator/nn/dropout-inl.h
  src/operator/rnn-inl.h
  src/resource.cc
  tests/python/gpu/test_gluon_gpu.py
Labels: Backport 1.x
