Repository apache/mxnet, pull requests merged in 2020-12, with the labels that each got.

#19576 Fix large tensor nightly tests by running each test as subprocess
  ci/docker/runtime_functions.sh
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19604 Remove six in ci docker
  ci/docker/install/requirements
Labels: pr-awaiting-review

#19618 Fix flaky onnxruntime tests.
  tests/python/unittest/onnx/test_onnxruntime.py
Labels: pr-awaiting-merge

#19382 Numpy unique repeat indices large tensor checks
  src/operator/numpy/np_init_op.cc
  src/operator/numpy/np_repeat_op-inl.h
  src/operator/numpy/np_unique_op.cc
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19620 [1.x] Remove six from docker dependencies
  ci/docker/install/requirements
Labels: pr-awaiting-review

#19588 Update Ubuntu images used on CI to 20.04
  3rdparty/mshadow/mshadow/tensor.h
  CMakeLists.txt
  ci/docker/Dockerfile.build.ubuntu
  ci/docker/docker-compose.yml
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_unix_gpu
  python/mxnet/contrib/text/utils.py
  python/mxnet/numpy/multiarray.py
  src/profiler/profiler.h
Labels: pr-awaiting-review

#19460 Masked softmax (& log-softmax)
  python/mxnet/amp/lists/symbol_bf16.py
  python/mxnet/amp/lists/symbol_fp16.py
  src/operator/nn/log_softmax.cc
  src/operator/nn/log_softmax.cu
  src/operator/nn/softmax-inl.h
  src/operator/nn/softmax.cc
  src/operator/nn/softmax.cu
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#19627 Skip test_sparse_mathematical_core
  tests/python/unittest/test_sparse_operator.py
Labels: pr-awaiting-review

#19174 Force static link to openblas on ci + add lapacke option for lapack
  3rdparty/mshadow/mshadow/base.h
  CMakeLists.txt
  ci/docker/Dockerfile.build.centos7
  ci/docker/Dockerfile.build.ubuntu
  ci/docker/runtime_functions.sh
  cmake/ChooseBlas.cmake
  cmake/Modules/FindOpenBLAS.cmake
  config/distribution/linux_cu100.cmake
  config/distribution/linux_cu101.cmake
  config/distribution/linux_cu102.cmake
  config/distribution/linux_cu110.cmake
  config/distribution/linux_cu92.cmake
  src/operator/c_lapack_api.cc
  src/operator/c_lapack_api.h
  tools/dependencies/openblas.sh
  tools/staticbuild/build_lib.sh
Labels: pr-awaiting-review

#19632 Forward port Support destructors for custom stateful ops (#19607)
  example/extensions/lib_custom_op/gemm_lib.cc
  example/extensions/lib_custom_op/transposerowsp_lib.cc
  include/mxnet/lib_api.h
  src/c_api/c_api.cc
  src/lib_api.cc
Labels: pr-awaiting-review

#19637 Fix CI README unittest_ubuntu_python3_armv7 -> unittest_ubuntu_python3_arm
  ci/README.md
Labels: pr-awaiting-merge

#19629 [BUGFIX] Fix Mxnet2.0 crashcourse format
  docs/python_docs/python/tutorials/getting-started/crash-course/2-create-nn.md
  docs/python_docs/python/tutorials/getting-started/crash-course/4-components.md
  docs/python_docs/python/tutorials/getting-started/crash-course/5-datasets.md
  docs/python_docs/python/tutorials/getting-started/crash-course/6-train-nn.md
Labels: pr-awaiting-review

#19271 Added tests for convolution layer with large inputs
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-merge

#19638 [v1.x] Change gcc 8 PPA to ppa:jonathonf/gcc
  ci/docker/install/ubuntu_gcc8.sh
Labels: pr-awaiting-review

#19641 Update Nightly test Ubuntu Image
  tests/nightly/JenkinsfileForBinaries
Labels: pr-awaiting-merge

#19626 Enable large tensor inputs for Deconvolution layer
  src/operator/nn/deconvolution-inl.h
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-merge

#19612 Added tests for DL layers with large inputs
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19614 [BUGFIX] Fix backward pass for nested CachedOp
  python/mxnet/gluon/block.py
  src/imperative/imperative_utils.cc
  src/operator/subgraph/static_shape_subgraph_property.cc
  tests/python/unittest/test_dynamic_shape.py
Labels: pr-awaiting-review

#19294 Numpy large tensor test batch 4
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19656 [v1.x] Fix r builds
  ci/docker/install/ubuntu_r.sh
Labels: pr-awaiting-review

#19658 [v1.8.x] Backport #19656 - fix R builds
  ci/docker/install/requirements
  ci/docker/install/ubuntu_gcc8.sh
  ci/docker/install/ubuntu_r.sh
Labels: pr-awaiting-merge

#19625 [v1.x] Add more ONNX export support to operators
  ci/docker/runtime_functions.sh
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19541 NP Large tensor tests batch 5
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19608 Change __str__ representation of bfloat16 NDArray from uints to floats.
  CONTRIBUTORS.md
  python/mxnet/ndarray/ndarray.py
  tests/python/unittest/test_ndarray.py
Labels: pr-awaiting-review

#19564 Save/Load Gluon Blocks & HybridBlocks
  python/mxnet/gluon/block.py
  python/mxnet/symbol/symbol.py
  tests/python/unittest/test_contrib_control_flow.py
  tests/python/unittest/test_contrib_operator.py
  tests/python/unittest/test_gluon_save.py
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#19662 Improve onnx test suite
  ci/docker/install/ubuntu_onnx.sh
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19666 [V1.x] Fix local variable 'optimizer' referenced before assignment
  CONTRIBUTORS.md
  python/mxnet/model.py
Labels: pr-awaiting-review

#19565 [v1.x] Save/Load Gluon Blocks & HybridBlocks
  python/mxnet/gluon/block.py
  tests/python/unittest/test_gluon_save.py
Labels: pr-awaiting-merge

#19668 Extensions naming macros fix
  include/mxnet/lib_api.h
Labels: pr-awaiting-merge

#19669 [v1.x] Backport #19668 Extensions naming macros fix
  include/mxnet/lib_api.h
Labels: pr-awaiting-merge

#19653 [wip] onnx support more ops
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19676 [v1.x] Make ONNX export operators work properly with the node input shape
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-merge

#19617 large tensor tests batch 6
  src/operator/numpy/np_matmul_op-inl.h
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#19680 Fix typo in adamw
  python/mxnet/optimizer/adamW.py
Labels: pr-awaiting-review

#19679 [v1.x] Update onnx export support for FullyConnected and add unit tests
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19661 [WIP] ONNX _contrib_interleaved_matmul_selfatt_valatt and LayerNorm
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-work-in-progress

#19682 [v1.x] Add coverage to onnx test pipeline.
  ci/docker/runtime_functions.sh
Labels: pr-awaiting-review

#19677 [v1.x] Onnx fix slice_axis and embedding and reshape
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19689 [v1.x] Add more onnx export unit tests, refactor onnxruntime tests.
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_onnxruntime.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19687 test coverage for leakyrelu elemwise_add concat activation
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19692 [v1.x] More onnx export updates
  ci/docker/runtime_functions.sh
  python/mxnet/contrib/onnx/mx2onnx/export_onnx.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19678 [Doc] prompt users to install gfortran as dependency of openblas
  docs/static_site/src/pages/get_started/build_from_source.md
Labels: pr-awaiting-review

#19694 Update tools/pip/setup.py for oneDNN v2
  tools/pip/setup.py
Labels: pr-awaiting-review

#19695 [v1.x] ONNX fix embedding and slice
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19693 [v1.x] onnx fix fullyconnected
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_node.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19696 CI: switch to cudnn8 devel docker as it is now available
  ci/docker/Dockerfile.build.ubuntu
  ci/docker/docker-compose.yml
Labels: pr-awaiting-merge

#19691 [v1.x] ONNX fix softmax
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/onnx2mx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19663 Fix spelling
  python/mxnet/gluon/loss.py
Labels: pr-awaiting-merge

#19704 [1.x] Update LICENSE
  LICENSE
  R-package/LICENSE
  contrib/clojure-package/LICENSE
  cpp-package/LICENSE
  example/rcnn/LICENSE
  julia/LICENSE.md
  licenses/BOOST1_0
  licenses/BSD2
  licenses/BSD3-cmake
  licenses/MIT
  licenses/OFL1_1
  scala-package/LICENSE
  tests/nightly/apache_rat_license_check/rat-excludes
Labels: pr-awaiting-review

#19701 use CC=gcc-7 CXX=g++-7 for all unix CI builds
  ci/docker/Dockerfile.build.ubuntu
  ci/docker/runtime_functions.sh
Labels: pr-awaiting-review

#19707 [1.8] Update LICENSE
  LICENSE
  R-package/LICENSE
  contrib/clojure-package/LICENSE
  cpp-package/LICENSE
  example/rcnn/LICENSE
  julia/LICENSE.md
  licenses/BOOST1_0
  licenses/BSD2
  licenses/BSD3-cmake
  licenses/MIT
  licenses/OFL1_1
  scala-package/LICENSE
  tests/nightly/apache_rat_license_check/rat-excludes
Labels: pr-awaiting-review

#19711 Fix test_rat_check
  ci/docker/Dockerfile.build.ubuntu
  ci/docker/runtime_functions.sh
  cmake/libmxnet.sym
  cmake/libmxnet.ver
  example/automatic-mixed-precision/common
  tests/nightly/apache_rat_license_check/rat-excludes
Labels: pr-awaiting-merge

#19697 [v1.x] Add more CV models to onnxruntime inference test, add bert model test.
  ci/docker/install/ubuntu_onnx.sh
  tests/python-pytest/onnx/common.py
  tests/python-pytest/onnx/test_onnxruntime.py
Labels: pr-awaiting-merge

#19706 Fix build problems with oneDNN v2.0 #19690
  .gitignore
  CMakeLists.txt
  cd/python/pypi/pypi_package.sh
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  include/mkldnn/dnnl_config.h
  include/mkldnn/dnnl_debug.h
  include/mkldnn/dnnl_ocl.h
  include/mkldnn/dnnl_ocl.hpp
  include/mkldnn/dnnl_sycl.h
  include/mkldnn/dnnl_sycl.hpp
  include/mkldnn/dnnl_sycl_types.h
  include/mkldnn/dnnl_threadpool.h
  include/mkldnn/dnnl_threadpool.hpp
  include/mkldnn/dnnl_threadpool_iface.hpp
  include/mkldnn/dnnl_version.h
  include/mkldnn/mkldnn_config.h
  include/mkldnn/mkldnn_debug.h
  include/mkldnn/oneapi/dnnl/dnnl.h
  include/mkldnn/oneapi/dnnl/dnnl.hpp
  include/mkldnn/oneapi/dnnl/dnnl_debug.h
  include/mkldnn/oneapi/dnnl/dnnl_ocl.h
  include/mkldnn/oneapi/dnnl/dnnl_ocl.hpp
  include/mkldnn/oneapi/dnnl/dnnl_sycl.h
  include/mkldnn/oneapi/dnnl/dnnl_sycl.hpp
  include/mkldnn/oneapi/dnnl/dnnl_sycl_types.h
  include/mkldnn/oneapi/dnnl/dnnl_threadpool.h
  include/mkldnn/oneapi/dnnl/dnnl_threadpool.hpp
  include/mkldnn/oneapi/dnnl/dnnl_threadpool_iface.hpp
  include/mkldnn/oneapi/dnnl/dnnl_types.h
  tools/pip/setup.py
Labels: pr-awaiting-review

#19703 masked_log_softmax -inf for masked values
  src/operator/nn/log_softmax.cc
  src/operator/nn/log_softmax.cu
  src/operator/nn/softmax-inl.h
  src/operator/nn/softmax.cc
  src/operator/nn/softmax.cu
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#19725 Update CD Jenkins config for include/mkldnn/oneapi/dnnl
  cd/mxnet_lib/static/Jenkins_pipeline.groovy
Labels: pr-awaiting-review
