Repository apache/mxnet, pull requests merged in 2020-07, with the labels that each got.

#18597 [CI][v1.6.x] Fix failing CI pipelines
  ci/docker/Dockerfile.build.jetson
  ci/docker/install/requirements
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_unix_gpu
Labels: pr-awaiting-review

#18605 Clipboard refactor
  docs/static_site/src/assets/js/clipboard.js
  docs/static_site/src/assets/js/copycode.js
Labels: Website, pr-awaiting-review

#18589 ci/build.py --no-pull
  ci/build.py
Labels: pr-awaiting-review

#18595 Mark test_get_symbol as garbage_expected
  tests/python/unittest/test_autograd.py
Labels: pr-awaiting-review

#18639 User Feedback Widget
  docs/python_docs/_static/feedback.css
  docs/python_docs/_static/feedback.js
  docs/python_docs/themes/mx-theme/mxtheme/feedback.html
  docs/python_docs/themes/mx-theme/mxtheme/layout.html
  docs/static_site/src/_includes/feedback.html
  docs/static_site/src/_includes/head.html
  docs/static_site/src/_layouts/page_api.html
  docs/static_site/src/_sass/feedback.scss
  docs/static_site/src/assets/js/feedback.js
  docs/static_site/src/assets/main.scss
Labels: Website, pr-awaiting-review

#18661 fix broken installation widget - remove empty entries for better UX
  docs/static_site/src/_includes/get_started/get_started.html
  docs/static_site/src/_sass/minima/_getting_started.scss
Labels: Website, pr-awaiting-review

#18504 [Improvement] Invoke mkldnn and cudnn BatchNorm when axis != 1
  src/operator/nn/batch_norm.cc
  src/operator/nn/batch_norm.cu
  src/operator/nn/cudnn/cudnn_batch_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
Labels: Operator, Performance

#18664 Fix python micro-site table of content bugs
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css.map
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.js
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.js.map
  docs/python_docs/themes/mx-theme/src/js/scrollspy.js
  docs/python_docs/themes/mx-theme/src/scss/footer/_footer.scss
Labels: Website

#18700 [v1.7] Backport Gluon Activations Fix #18370
  python/mxnet/gluon/nn/activations.py
  tests/python/unittest/test_numpy_gluon.py
Labels: R1.7.0

#18691 Merge numpy.mxnet.io into mxnet official website
  docs/python_docs/python/tutorials/getting-started/crash-course/1-ndarray.md
  docs/python_docs/python/tutorials/getting-started/crash-course/2-nn.md
  docs/python_docs/python/tutorials/getting-started/crash-course/3-autograd.md
  docs/python_docs/python/tutorials/getting-started/crash-course/4-train.md
  docs/python_docs/python/tutorials/getting-started/crash-course/5-predict.md
  docs/python_docs/python/tutorials/getting-started/crash-course/6-use_gpus.md
  docs/python_docs/python/tutorials/getting-started/crash-course/index.rst
  docs/python_docs/python/tutorials/getting-started/deepnumpy/cheat-sheet.md
  docs/python_docs/python/tutorials/getting-started/deepnumpy/deepnumpy-vs-numpy.md
  docs/python_docs/python/tutorials/getting-started/deepnumpy/index.rst
  docs/python_docs/python/tutorials/getting-started/index.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/arrays.indexing.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/arrays.ndarray.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/arrays.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/index.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/npx.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/random/index.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/routines.array-creation.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/routines.array-manipulation.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/routines.io.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/routines.linalg.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/routines.math.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/routines.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/routines.sort.rst
  docs/python_docs/python/tutorials/packages/ndarray/deepnumpy/routines.statistics.rst
  docs/python_docs/python/tutorials/packages/ndarray/index.rst
Labels: Website, pr-awaiting-review

#18674 fix anchors shift on all main website pages
  docs/static_site/src/_sass/minima/_layout.scss
Labels: Website, pr-awaiting-review

#18443 Disable test coverage in MKL builds
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
Labels: pr-awaiting-review

#18701 Enable GPU Memory profiler tests
  tests/python/gpu/test_profiler_gpu.py
  tests/python/unittest/test_profiler.py
Labels: pr-awaiting-review

#18677 Migrate from private jetpack files to public
  ci/docker/Dockerfile.build.jetson
Labels: pr-awaiting-review

#18197 [Numpy] Add qr backward part 2 for wide matrices with m < n
  src/operator/numpy/linalg/np_qr-inl.h
  tests/python/unittest/test_numpy_op.py
Labels: Numpy

#18771 CI: Migrate remaining Dockerfiles to docker-compose.yml and remove unused code
  ci/Jenkinsfile_docker_cache
  ci/build.py
  ci/dev_menu.py
  ci/docker/Dockerfile.build.ubuntu
  ci/docker/Dockerfile.build.ubuntu_cpu_c
  ci/docker/Dockerfile.build.ubuntu_cpu_jekyll
  ci/docker/Dockerfile.build.ubuntu_cpu_julia
  ci/docker/Dockerfile.build.ubuntu_cpu_r
  ci/docker/Dockerfile.build.ubuntu_cpu_scala
  ci/docker/Dockerfile.build.ubuntu_gpu_tensorrt
  ci/docker/Dockerfile.build.ubuntu_rat
  ci/docker/Dockerfile.publish.test.ubuntu1604_cpu
  ci/docker/Dockerfile.publish.test.ubuntu1604_gpu
  ci/docker/Dockerfile.publish.test.ubuntu1804_cpu
  ci/docker/Dockerfile.publish.test.ubuntu1804_gpu
  ci/docker/Dockerfile.publish.ubuntu1604_cpu
  ci/docker/Dockerfile.publish.ubuntu1604_gpu
  ci/docker/docker-compose.yml
  ci/docker/install/export_gpg_keys.sh
  ci/docker/install/r.gpg
  ci/docker/install/sbt.gpg
  ci/docker/install/tensorrt.sh
  ci/docker/install/ubuntu_base.sh
  ci/docker/install/ubuntu_clang.sh
  ci/docker/install/ubuntu_clojure.sh
  ci/docker/install/ubuntu_cudnn.sh
  ci/docker/install/ubuntu_emscripten.sh
  ci/docker/install/ubuntu_gcc8.sh
  ci/docker/install/ubuntu_julia.sh
  ci/docker/install/ubuntu_nightly_tests.sh
  ci/docker/install/ubuntu_r.sh
  ci/docker/install/ubuntu_rat.sh
  ci/docker/install/ubuntu_scala.sh
  ci/docker/runtime_functions.sh
  ci/docker_cache.py
  ci/docker_cache_requirements
  ci/jenkins/Jenkins_steps.groovy
  ci/test_docker_cache.py
  ci/windows/test_jl07_cpu.ps1
  ci/windows/test_jl10_cpu.ps1
  tests/nightly/apache_rat_license_check/README.md
Labels: pr-awaiting-review

#18424 environment variable handling in unittests
  include/mxnet/c_api_test.h
  python/mxnet/test_utils.py
  python/mxnet/util.py
  src/c_api/c_api_test.cc
  tests/python/gpu/test_device.py
  tests/python/gpu/test_fusion.py
  tests/python/gpu/test_gluon_gpu.py
  tests/python/gpu/test_kvstore_gpu.py
  tests/python/gpu/test_operator_gpu.py
  tests/python/unittest/common.py
  tests/python/unittest/test_autograd.py
  tests/python/unittest/test_base.py
  tests/python/unittest/test_engine.py
  tests/python/unittest/test_engine_import.py
  tests/python/unittest/test_executor.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_gluon_probability_v1.py
  tests/python/unittest/test_gluon_probability_v2.py
  tests/python/unittest/test_memory_opt.py
  tests/python/unittest/test_operator.py
  tests/python/unittest/test_subgraph_op.py
  tests/python/unittest/test_symbol.py
Labels: pr-awaiting-review

#18738 set website default version to current stable (1.6) version
  docs/static_site/src/.htaccess
Labels: Website

#18790 [NumPy] add support for np.ndarray in autograd.function
  python/mxnet/autograd.py
  tests/python/unittest/test_autograd.py
Labels: Backport 1.x, v2.0

#18744 [v1.x] add large matrix tests for linalg ops: det, inverse, trsm, trmm
  python/mxnet/test_utils.py
  tests/nightly/test_large_array.py
Labels: pr-awaiting-review

#18784 [1.x][LT] Add forward, backward test for linalg.gemm2
  tests/nightly/test_large_array.py
Labels: pr-awaiting-merge

#18660 [numpy] fix flaky mixed precision binary error
  src/operator/numpy/np_elemwise_broadcast_logic_op.cc
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-review

#18802 remove executor manager from API doc
  docs/python_docs/python/api/index.rst
  docs/python_docs/python/api/mxnet/executor_manager/index.rst
  docs/python_docs/python/api/mxnet/index.rst
Labels: pr-awaiting-review

#18773 Back port optimization to broadcast_axis to MXNet1.x
  src/operator/numpy/np_matmul_op-inl.h
  src/operator/tensor/broadcast_reduce_op.h
Labels: pr-awaiting-review

#18804 Cherry-pick large tensor support from #18752.
  CONTRIBUTORS.md
  src/operator/tensor/la_op-inl.h
Labels: pr-awaiting-merge

#18798 Remove deepnumpy reference and move Numpy tutorials to top level
  docs/python_docs/_static/mxnet.css
  docs/python_docs/python/tutorials/getting-started/crash-course/1-ndarray.md
  docs/python_docs/python/tutorials/getting-started/crash-course/6-use_gpus.md
  docs/python_docs/python/tutorials/getting-started/index.rst
  docs/python_docs/python/tutorials/getting-started/np/cheat-sheet.md
  docs/python_docs/python/tutorials/getting-started/np/index.rst
  docs/python_docs/python/tutorials/getting-started/np/np-vs-numpy.md
  docs/python_docs/python/tutorials/index.rst
  docs/python_docs/python/tutorials/packages/index.rst
  docs/python_docs/python/tutorials/packages/ndarray/index.rst
  docs/python_docs/python/tutorials/packages/np/arrays.indexing.rst
  docs/python_docs/python/tutorials/packages/np/arrays.ndarray.rst
  docs/python_docs/python/tutorials/packages/np/arrays.rst
  docs/python_docs/python/tutorials/packages/np/index.rst
  docs/python_docs/python/tutorials/packages/np/npx.rst
  docs/python_docs/python/tutorials/packages/np/random/index.rst
  docs/python_docs/python/tutorials/packages/np/routines.array-creation.rst
  docs/python_docs/python/tutorials/packages/np/routines.array-manipulation.rst
  docs/python_docs/python/tutorials/packages/np/routines.io.rst
  docs/python_docs/python/tutorials/packages/np/routines.linalg.rst
  docs/python_docs/python/tutorials/packages/np/routines.math.rst
  docs/python_docs/python/tutorials/packages/np/routines.rst
  docs/python_docs/python/tutorials/packages/np/routines.sort.rst
  docs/python_docs/python/tutorials/packages/np/routines.statistics.rst
  docs/python_docs/themes/mx-theme/mxtheme/layout.html
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css.map
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.js
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.js.map
  docs/python_docs/themes/mx-theme/src/js/feedback.js
  docs/python_docs/themes/mx-theme/src/js/sphinx_materialdesign_theme.js
  docs/python_docs/themes/mx-theme/src/scss/_root.scss
  docs/python_docs/themes/mx-theme/src/scss/grid/_simplegrid.scss
  docs/python_docs/themes/mx-theme/src/scss/layout/_layout.scss
Labels: Website, pr-awaiting-review

#18783 remove other language bindings section from website api page
  docs/static_site/src/.htaccess
  docs/static_site/src/_sass/minima/_docs.scss
  docs/static_site/src/pages/api/api.html
Labels: Website, pr-awaiting-merge, pr-awaiting-review

#18811 website clipcoard patch - use regex that is supported by all browsers
  docs/static_site/src/assets/js/copycode.js
Labels: pr-awaiting-review

#18656 [NumPy] DLPack refactor and npx.from_numpy
  CMakeLists.txt
  python/mxnet/base.py
  python/mxnet/dlpack.py
  python/mxnet/ndarray/ndarray.py
  python/mxnet/ndarray/numpy/_op.py
  python/mxnet/ndarray/numpy/random.py
  python/mxnet/numpy/multiarray.py
  python/mxnet/numpy/random.py
  python/mxnet/numpy_extension/utils.py
  python/mxnet/symbol/numpy/random.py
  tests/python/unittest/test_base.py
  tests/python/unittest/test_gluon_probability_v1.py
  tests/python/unittest/test_numpy_ndarray.py
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#18828 add adaptive left margin for python site document body
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css
  docs/python_docs/themes/mx-theme/mxtheme/static/sphinx_materialdesign_theme.css.map
  docs/python_docs/themes/mx-theme/src/scss/_root.scss
Labels: Website

#18796 Enable DIST_KVSTORE by default in staticbuild
  CMakeLists.txt
  config/distribution/darwin_cpu.cmake
  config/distribution/linux_cpu.cmake
  config/distribution/linux_cu100.cmake
  config/distribution/linux_cu101.cmake
  config/distribution/linux_cu102.cmake
  tools/dependencies/cityhash.sh
  tools/dependencies/libpng.sh
  tools/dependencies/libturbojpeg.sh
  tools/dependencies/lz4.sh
  tools/dependencies/openssl.sh
  tools/dependencies/protobuf.sh
  tools/dependencies/zmq.sh
Labels: pr-awaiting-response

#18748 Fixup move gluon.metric api docs
  docs/python_docs/python/api/gluon/index.rst
  docs/python_docs/python/api/gluon/metric/index.rst
Labels: pr-awaiting-review
