Repository apache/mxnet, pull requests merged in 2021-07, with the labels that each got.

#20404 Fix qunatization doc formatting
  python/mxnet/contrib/quantization.py
Labels: pr-awaiting-review

#20413 [2.0] Tweak the argument order for softmax
  python/mxnet/numpy_extension/_op.py
Labels: pr-awaiting-review

#20302 [FEATURE] Performance improvement by asymmetric quantization Quantize+FC
  python/mxnet/contrib/quantization.py
  src/operator/quantization/mkldnn/mkldnn_quantize_v2-inl.h
  src/operator/quantization/quantization_utils.h
  src/operator/quantization/quantize_graph_pass.cc
  src/operator/quantization/quantize_v2-inl.h
  src/operator/quantization/requantize-inl.h
  src/operator/subgraph/mkldnn/mkldnn_fc.cc
  tests/python/quantization/test_quantization.py
Labels: pr-awaiting-review

#20375 [2.0] Adopt interleaved_matmul_* into npx namespace
  src/operator/contrib/transformer.cc
  src/operator/tensor/elemwise_sum.cc
  src/operator/tensor/matrix_op.cc
  tests/python/gpu/test_numpy_op.py
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_subgraph_op.py
Labels: pr-awaiting-review

#20415 [BUGFIX] Add checks in BatchNorm's infer shape
  src/operator/nn/batch_norm.cc
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
Labels: pr-awaiting-review

#20408 Update centos cu101 docker image to use cudnn8
  ci/docker/docker-compose.yml
Labels: pr-awaiting-review

#20392 [v1.x] use centos7 base image for aarch64 build
  cd/mxnet_lib/Jenkins_pipeline.groovy
  cd/mxnet_lib/mxnet_lib_pipeline.groovy
  cd/python/docker/Dockerfile
  cd/python/docker/Jenkins_pipeline.groovy
  cd/python/pypi/Jenkins_pipeline.groovy
  ci/docker/Dockerfile.build.centos7_aarch64_cpu
  ci/docker/Dockerfile.publish.ubuntu1804_aarch64_cpu
  ci/docker/install/requirements_aarch64
  ci/docker/install/ubuntu_aarch64_publish.sh
  ci/docker/runtime_functions.sh
  cmake/Modules/FindArmPL.cmake
  tests/python/unittest/test_ndarray.py
  tests/python/unittest/test_numpy_interoperability.py
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_profiler.py
  tools/dependencies/curl.sh
  tools/dependencies/openssl.sh
  tools/staticbuild/build_lib_cmake.sh
Labels: pr-awaiting-merge

#20409 [v1.x] Update CD pipeline to build with centos7
  cd/mxnet_lib/Jenkins_pipeline.groovy
  cd/mxnet_lib/mxnet_lib_pipeline.groovy
  cd/python/docker/Jenkins_pipeline.groovy
  cd/python/pypi/Jenkins_pipeline.groovy
  ci/Jenkinsfile_docker_cache
  ci/Jenkinsfile_utils.groovy
  ci/build.py
  ci/docker/Dockerfile.build.centos7
  ci/docker/Dockerfile.build.centos7_gpu
  ci/docker/docker-compose.yml
  ci/docker/install/centos7_core.sh
  ci/docker/install/requirements
  ci/docker/runtime_functions.sh
  ci/docker_cache.py
  ci/jenkins/Jenkins_steps.groovy
  tests/README.md
Labels: pr-awaiting-merge

#20400 [FEATURE] Fuse FC + sum for quantization
  src/operator/nn/mkldnn/mkldnn_fully_connected-inl.h
  src/operator/nn/mkldnn/mkldnn_fully_connected.cc
  src/operator/quantization/quantize_graph_pass.cc
  src/operator/subgraph/mkldnn/mkldnn_fc.cc
  src/operator/subgraph/mkldnn/mkldnn_fc_sum_fuse.h
  src/operator/subgraph/mkldnn/mkldnn_subgraph_property.cc
  tests/python/mkl/test_subgraph.py
Labels: pr-awaiting-review

#20423 [v1.9.x] Use centos7 base image for CD pipeline and aarch64 build
  cd/mxnet_lib/Jenkins_pipeline.groovy
  cd/mxnet_lib/mxnet_lib_pipeline.groovy
  cd/python/docker/Dockerfile
  cd/python/docker/Jenkins_pipeline.groovy
  cd/python/pypi/Jenkins_pipeline.groovy
  ci/Jenkinsfile_docker_cache
  ci/Jenkinsfile_utils.groovy
  ci/build.py
  ci/docker/Dockerfile.build.centos7
  ci/docker/Dockerfile.build.centos7_aarch64_cpu
  ci/docker/Dockerfile.build.centos7_gpu
  ci/docker/Dockerfile.publish.ubuntu1804_aarch64_cpu
  ci/docker/docker-compose.yml
  ci/docker/install/centos7_core.sh
  ci/docker/install/requirements
  ci/docker/install/requirements_aarch64
  ci/docker/install/ubuntu_aarch64_publish.sh
  ci/docker/runtime_functions.sh
  ci/docker_cache.py
  ci/jenkins/Jenkins_steps.groovy
  cmake/Modules/FindArmPL.cmake
  tests/README.md
  tests/python/unittest/test_ndarray.py
  tests/python/unittest/test_numpy_interoperability.py
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_profiler.py
  tools/dependencies/curl.sh
  tools/dependencies/openssl.sh
  tools/staticbuild/build_lib_cmake.sh
Labels: pr-awaiting-merge

#20421 [BUGFIX] Fix Precision
  src/operator/tensor/elemwise_binary_scalar_op.h
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-merge

#20428 [v1.9.x] License updates per feedback
  ci/docker/install/ubuntu_caffe.sh
  rat-excludes
  src/operator/contrib/nn/modulated_deformable_im2col.cuh
  src/operator/contrib/nn/modulated_deformable_im2col.h
  src/operator/nn/pool.cuh
  tests/requirements.txt
  tools/license_header.py
Labels: pr-awaiting-review

#20434 [v1.x] Backport #20428 from v1.9.x
  ci/docker/install/requirements
  ci/docker/install/ubuntu_caffe.sh
  rat-excludes
  src/operator/contrib/nn/modulated_deformable_im2col.cuh
  src/operator/contrib/nn/modulated_deformable_im2col.h
  src/operator/nn/pool.cuh
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_random.py
  tests/requirements.txt
  tools/license_header.py
Labels: pr-awaiting-review

#20350 [v1.x][backport] Consider MXNET_BUILD_SHARED_LIBS flag
  CMakeLists.txt
  example/image-classification/predict-cpp/CMakeLists.txt
  tests/CMakeLists.txt
Labels: pr-work-in-progress

#20427 [wip] Re-enable code cov
  ci/Jenkinsfile_utils.groovy
Labels: pr-awaiting-merge

#20382 [1.x][backport] Integrate matmul primitive from oneDNN in batch dot
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_dot-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_dot.cc
  src/operator/nn/mkldnn/mkldnn_ops-inl.h
  src/operator/tensor/dot-inl.h
  src/operator/tensor/dot.cc
Labels: pr-awaiting-review

#20443 [FEATURE] Add backend MXGetMaxSupportedArch() and frontend get_rtc_compile_opts() for CUDA enhanced compatibility
  include/mxnet/c_api_test.h
  python/mxnet/test_utils.py
  python/mxnet/util.py
  src/c_api/c_api_test.cc
  src/common/cuda/rtc.cc
  src/common/cuda/rtc.h
  src/common/rtc.cc
  tests/python/gpu/test_operator_gpu.py
Labels: pr-awaiting-merge

#20385 [v1.x] Fix docker cache build pipeline
  ci/Jenkinsfile_docker_cache
  ci/Jenkinsfile_utils.groovy
  ci/build.py
  ci/docker/docker-compose.yml
  ci/docker/install/ubuntu_core.sh
  ci/docker_cache.py
Labels: pr-awaiting-review

#20450 [v1.x][Feature] Add flag for disabling oneDNN BRGEMM implementation of FC
  docs/static_site/src/pages/api/faq/env_var.md
  src/operator/nn/mkldnn/mkldnn_base-inl.h
Labels: pr-awaiting-merge

#20458 [v1.x] More docker cache fixes
  ci/Jenkinsfile_docker_cache
  ci/docker_cache.py
Labels: pr-awaiting-review

#20426 [v2.0] Add Optim Warning
  python/mxnet/optimizer/adagrad.py
  python/mxnet/optimizer/rmsprop.py
Labels: pr-awaiting-review

#20338 [1.x] [FEATURE] Add API to control denormalized computations
  include/mxnet/c_api.h
  python/mxnet/base.py
  python/mxnet/util.py
  src/c_api/c_api.cc
  tests/python/unittest/test_numpy_interoperability.py
Labels: pr-awaiting-review

#20388 [FEATURE] Add new benchmark function for single operator comparison
  benchmark/opperf/README.md
  benchmark/opperf/rules/default_params.py
  benchmark/opperf/utils/benchmark_utils.py
Labels: pr-awaiting-review

#20387 [BACKPORT] [FEATURE] Add API to control denormalized computations
  include/mxnet/c_api.h
  python/mxnet/base.py
  python/mxnet/util.py
  src/c_api/c_api.cc
  tests/python/unittest/test_numpy_interoperability.py
Labels: pr-awaiting-review
