Repository apache/mxnet, pull requests merged in 2021-03, with the labels that each got.

#19970 [Website] Add DJL to ecosystem
  docs/static_site/src/assets/img/djl.png
  docs/static_site/src/pages/ecosystem.html
Labels: pr-awaiting-testing

#19947 [V1.8.x] Attemp to fix cd for v1.8.x
  cd/python/docker/Dockerfile
  ci/Jenkinsfile_docker_cache
  ci/Jenkinsfile_utils.groovy
  ci/build.py
  ci/docker/Dockerfile.build.ubuntu_gpu_cu102
  ci/docker/Dockerfile.build.ubuntu_gpu_cu110
  ci/docker/install/ubuntu_python.sh
  ci/docker/runtime_functions.sh
  ci/docker_cache.py
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_full
  ci/safe_docker_run.py
  ci/test_safe_docker_run.py
  python/mxnet/gluon/data/dataloader.py
  tests/python/unittest/test_numpy_interoperability.py
  tests/python/unittest/test_numpy_op.py
  tools/setup_gpu_build_tools.sh
Labels: pr-awaiting-review

#19774 [v1.x] Fix nightly CD for python docker image releases
  cd/Jenkinsfile_cd_pipeline
  cd/Jenkinsfile_release_job
  cd/Jenkinsfile_utils.groovy
  cd/README.md
  cd/mxnet_lib/Jenkins_pipeline.groovy
  cd/mxnet_lib/dynamic/Jenkins_pipeline.groovy
  cd/python/docker/Dockerfile
  cd/python/docker/Dockerfile.test
  cd/python/docker/python_images.sh
  cd/utils/docker_tag.sh
  cd/utils/mxnet_base_image.sh
Labels: pr-awaiting-review

#19952 [v1.x] Add onnx export support for one_hot and random_uniform_like and unit tests for one_hot.
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-merge

#19958 [v1.x] ONNX export support for RNN
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/mx2onnx/export_onnx.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19973 [v1.x] ONNX Fixes for some NLP models
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/mx2onnx/export_onnx.py
Labels: pr-awaiting-review

#19972 [WIP] [v1.x] Create tool for building source archives
  LICENSE
  rat-excludes
  tools/create_source_archive.sh
  tools/source-exclude-artifacts.txt
Labels: pr-work-in-progress

#19981 [v1.8.x] add djl and autogluon to website
  docs/static_site/src/assets/img/autogluon.png
  docs/static_site/src/assets/img/djl.png
  docs/static_site/src/pages/ecosystem.html
Labels: pr-awaiting-review

#19983 Backport TRT fixes to 1.8
  docs/python_docs/python/tutorials/performance/backend/tensorrt/tensorrt.md
  example/extensions/lib_pass/README.md
  example/extensions/lib_subgraph/README.md
  example/extensions/lib_subgraph/test_subgraph.py
  python/mxnet/gluon/block.py
  src/operator/subgraph/tensorrt/nnvm_to_onnx-inl.h
  src/operator/subgraph/tensorrt/nnvm_to_onnx.cc
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-review

#19982 [v1.x] pass version param
  cd/Jenkinsfile_release_job
  cd/Jenkinsfile_utils.groovy
  cd/python/docker/python_images.sh
  cd/utils/docker_tag.sh
Labels: pr-awaiting-review

#19984 pass version param
  cd/Jenkinsfile_release_job
  cd/Jenkinsfile_utils.groovy
  cd/python/docker/python_images.sh
  cd/utils/docker_tag.sh
Labels: pr-awaiting-review

#19796 [v1.x] ONNX export support for multiple input data types
  python/mxnet/contrib/onnx/mx2onnx/export_model.py
  python/mxnet/contrib/onnx/mx2onnx/export_onnx.py
  python/mxnet/contrib/onnx/onnx2mx/import_onnx.py
  tests/python-pytest/onnx/backend.py
  tests/python-pytest/onnx/mxnet_export_test.py
  tests/python-pytest/onnx/test_node.py
  tests/python-pytest/onnx/test_onnxruntime.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19989 [v1.8.x] Cherry-pick CD pipelines refactor with fix for docker images pipeline
  cd/Jenkinsfile_cd_pipeline
  cd/Jenkinsfile_release_job
  cd/Jenkinsfile_utils.groovy
  cd/README.md
  cd/mxnet_lib/Jenkins_pipeline.groovy
  cd/mxnet_lib/dynamic/Jenkins_pipeline.groovy
  cd/python/docker/Dockerfile
  cd/python/docker/Dockerfile.test
  cd/python/docker/python_images.sh
  cd/utils/docker_tag.sh
  cd/utils/mxnet_base_image.sh
Labels: pr-awaiting-merge

#19990 [v1.x] ONNX Type inference support
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/mx2onnx/export_onnx.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#19977 [v1.8.x] fix cu110 docker image for cd
  ci/docker/Dockerfile.build.ubuntu_gpu_cu110
Labels: pr-awaiting-merge

#19995 [v1.x] [Website] Add DJL and AutoGluon to Ecosystem
  docs/static_site/src/assets/img/autogluon.png
  docs/static_site/src/assets/img/djl.png
  docs/static_site/src/pages/ecosystem.html
Labels: pr-awaiting-review

#19999 [v1.x] add ONNX DistilBERT tests
  tests/python-pytest/onnx/test_onnxruntime.py
Labels: pr-awaiting-review

#17952 [v1.x][KVStore]1Bit gradient compression
  ci/docker/runtime_functions.sh
  python/mxnet/kvstore/kvstore.py
  src/kvstore/gradient_compression-inl.h
  src/kvstore/gradient_compression.cc
  src/kvstore/gradient_compression.cu
  src/kvstore/gradient_compression.h
  tests/nightly/dist_sync_kvstore.py
  tests/nightly/test_kvstore.py
Labels: Distributed, KVStore, pr-awaiting-merge

#19988 [v1.8.x] Update for MXNet 1.8.0 website release
  docs/static_site/src/_config.yml
  docs/static_site/src/_config_beta.yml
  docs/static_site/src/_config_prod.yml
  docs/static_site/src/_includes/get_started/get_started.html
  docs/static_site/src/_includes/get_started/gpu_snippet.md
  docs/static_site/src/_includes/get_started/linux/python/cpu/pip.md
  docs/static_site/src/_includes/get_started/linux/python/gpu/pip.md
  docs/static_site/src/_includes/get_started/pip_snippet.md
  docs/static_site/src/_includes/header.html
  docs/static_site/src/pages/get_started/download.md
Labels: pr-awaiting-review

#19955 [website] Automate website artifacts uploading
  ci/docker/Dockerfile.build.ubuntu
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_website_version_artifacts
Labels: pr-awaiting-review

#20001 Onnx Dynamic Shapes Support
  ci/docker/runtime_functions.sh
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  python/mxnet/contrib/onnx/mx2onnx/export_model.py
  python/mxnet/contrib/onnx/mx2onnx/export_onnx.py
  tests/python-pytest/onnx/test_onnxruntime.py
Labels: pr-awaiting-review

#20014 [BUGFIX][CD] fix failing MNIST tests
  example/image-classification/train_mnist.py
Labels: pr-awaiting-merge

#20003 [BUGFIX] Fix AmpCast for float16
  CONTRIBUTORS.md
  src/operator/tensor/amp_cast.cc
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#20004 Remove USE_MKL_IF_AVAILABLE flag
  CMakeLists.txt
  ci/build_windows.py
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  cmake/ChooseBlas.cmake
  config/darwin.cmake
  config/distribution/darwin_cpu.cmake
  config/distribution/darwin_native.cmake
  config/distribution/linux_cpu.cmake
  config/distribution/linux_cu100.cmake
  config/distribution/linux_cu101.cmake
  config/distribution/linux_cu102.cmake
  config/distribution/linux_cu110.cmake
  config/distribution/linux_cu112.cmake
  config/distribution/linux_cu92.cmake
  config/distribution/linux_native.cmake
  config/linux.cmake
  config/linux_gpu.cmake
  docs/python_docs/python/tutorials/performance/backend/mkldnn/mkldnn_readme.md
  docs/static_site/src/_includes/get_started/devices/raspberry_pi.md
  tests/README.md
Labels: pr-awaiting-review

#20013 [website] Update for MXNet 1.8.0 website release
  docs/static_site/src/.htaccess
  docs/static_site/src/_config.yml
  docs/static_site/src/_config_beta.yml
  docs/static_site/src/_config_prod.yml
  docs/static_site/src/_includes/get_started/get_started.html
  docs/static_site/src/_includes/get_started/gpu_snippet.md
  docs/static_site/src/_includes/get_started/linux/python/cpu/pip.md
  docs/static_site/src/_includes/get_started/linux/python/gpu/pip.md
  docs/static_site/src/_includes/get_started/pip_snippet.md
  docs/static_site/src/pages/get_started/download.md
Labels: pr-awaiting-review

#20007 [BUGFIX][v1.x] Fix a bug for 1bit quantizer
  src/kvstore/gradient_compression.cc
Labels: pr-awaiting-review

#20022 [DOC] Fix format issue in the document of mxnet.gluon.contrib.estimator.GradientUpdateHandler
  CONTRIBUTORS.md
  python/mxnet/gluon/contrib/estimator/event_handler.py
Labels: pr-awaiting-review

#20020 [v1.x] ONNX Fix Squeeze Axes
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
Labels: pr-awaiting-review

#20017 [v1.x] ONNX Support for pretrained StandardRNN models
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_onnxruntime.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20019 [v1.x]Fix Nightly CI
  ci/docker/Dockerfile.build.ubuntu_gpu_tensorrt
  ci/docker/Dockerfile.build.ubuntu_nightly_cpu
  ci/docker/Dockerfile.build.ubuntu_nightly_gpu
  ci/docker/Dockerfile.build.ubuntu_rat
  ci/docker/install/ubuntu_rat.sh
  cpp-package/example/get_data.sh
Labels: pr-awaiting-review

#20036 [BUGFIX] Fix for test_lans failure
  src/operator/contrib/multi_lamb.cc
  src/operator/contrib/multi_lans.cc
Labels: pr-awaiting-merge

#20031 Change MXNET_MKLDNN_DEBUG define name to MXNET_ONEDNN_DEBUG
  ci/docker/runtime_functions.sh
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_base.cc
Labels: pr-awaiting-review

#20030 [v1.x] Add ERNIE model test
  tests/python-pytest/onnx/test_onnxruntime.py
Labels: pr-awaiting-review

#20035 Change mx_mkldnn_lib to mx_onednn_lib in Jenkins_steps.groovy file
  ci/jenkins/Jenkins_steps.groovy
Labels: pr-awaiting-review

#20018 [v1.x] Add AWDRNN Pratrained model test
  python/mxnet/contrib/onnx/mx2onnx/export_model.py
  tests/python-pytest/onnx/test_onnxruntime.py
Labels: pr-awaiting-review

#20053 Update ci/dev_menu.py file
  ci/dev_menu.py
Labels: pr-awaiting-review

#19986 [DOC]Disabling hybridization steps added
  docs/python_docs/python/tutorials/packages/gluon/blocks/hybridize.md
Labels: pr-awaiting-merge

#20038 [DOC] Add Flower to MXNet ecosystem
  CONTRIBUTORS.md
  docs/static_site/src/assets/img/flower_icon.png
  docs/static_site/src/pages/ecosystem.html
Labels: pr-awaiting-merge

#20058 [operator] Fix reshape and mean
  python/mxnet/base.py
  python/mxnet/ndarray/numpy/_op.py
  python/mxnet/numpy/multiarray.py
  src/api/operator/numpy/np_broadcast_reduce_op_value.cc
Labels: pr-awaiting-review

#20074 [BACKPORT] Fixes openblas error (#19037)(#19514)
  tools/pip/setup.py
Labels: pr-awaiting-merge

#20086 [BUGFIX]package libopenblas.so.0 correctly in MXNet v1.8.x wheels
  cd/mxnet_lib/Jenkins_pipeline.groovy
Labels: pr-awaiting-review

#20070 Fix oneDNN feature name in MxNET
  cd/utils/artifact_repository.py
  cd/utils/test_artifact_repository.py
  include/mxnet/libinfo.h
  python/mxnet/amp/lists/symbol_fp16.py
  python/mxnet/runtime.py
  src/libinfo.cc
  tools/dependencies/README.md
  tools/pip/setup.py
Labels: pr-awaiting-merge

#20071 Change *MKLDNN* flag names to *ONEDNN*
  docs/static_site/src/pages/api/cpp/docs/tutorials/multi_threaded_inference.md
  docs/static_site/src/pages/api/faq/env_var.md
  example/multi_threaded_inference/Makefile
  src/common/utils.h
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/subgraph/mkldnn/mkldnn_bn_relu_property.h
  src/operator/subgraph/mkldnn/mkldnn_conv_property.h
  src/operator/subgraph/mkldnn/mkldnn_elemwisemul_post_quantize_property.h
  src/operator/subgraph/mkldnn/mkldnn_fc.cc
  src/operator/subgraph/mkldnn/mkldnn_fc_post_quantize_property.h
  src/operator/subgraph/mkldnn/mkldnn_fc_property.h
  tests/python/mkl/test_quantization_mkldnn.py
  tests/python/quantization/test_quantization.py
Labels: pr-awaiting-review

#20034 Change *_mkldnn* test and build scenarios names to *_onednn*
  ci/build_windows.py
  ci/dev_menu.py
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_centos_cpu
  ci/jenkins/Jenkinsfile_clang
  ci/jenkins/Jenkinsfile_unix_cpu
  ci/jenkins/Jenkinsfile_unix_gpu
  ci/jenkins/Jenkinsfile_windows_cpu
  ci/jenkins/Jenkinsfile_windows_gpu
  tests/nightly/JenkinsfileForBinaries
Labels: pr-awaiting-review

#20084 [v1.x] Fix cu100 pip link
  tools/pip/doc/CPU_ADDITIONAL.md
  tools/pip/doc/CU100_ADDITIONAL.md
  tools/pip/doc/CU101_ADDITIONAL.md
  tools/pip/doc/CU102_ADDITIONAL.md
  tools/pip/doc/CU110_ADDITIONAL.md
  tools/pip/doc/CU112_ADDITIONAL.md
  tools/pip/doc/NATIVE_ADDITIONAL.md
Labels: pr-awaiting-merge

#20085 [v1.8.x] Backport #20084
  tools/pip/doc/CPU_ADDITIONAL.md
  tools/pip/doc/CU100_ADDITIONAL.md
  tools/pip/doc/CU101_ADDITIONAL.md
  tools/pip/doc/CU102_ADDITIONAL.md
  tools/pip/doc/CU110_ADDITIONAL.md
  tools/pip/doc/CU112_ADDITIONAL.md
  tools/pip/doc/NATIVE_ADDITIONAL.md
Labels: pr-awaiting-merge

#20061 [v1.x] ONNX support fot gpt models
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_onnxruntime.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20083 [FFI] Randint
  python/mxnet/ndarray/numpy/random.py
  src/api/operator/random/np_randint_op.cc
  src/operator/random/sample_op.h
Labels: pr-awaiting-review

#20087 [FFI] Part1: npx.softmax, npx.activation, npx.batch_norm, npx.fully_connected
  python/mxnet/base.py
  python/mxnet/ndarray/numpy_extension/_api_internal.py
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
  src/api/operator/numpy_extension/npx_activation_op.cc
  src/api/operator/numpy_extension/npx_batch_norm_op.cc
  src/api/operator/numpy_extension/npx_fully_connected_op.cc
  src/api/operator/numpy_extension/npx_softmax_op.cc
  src/operator/nn/activation-inl.h
  src/operator/nn/batch_norm-inl.h
  src/operator/nn/fully_connected-inl.h
  src/operator/nn/softmax-inl.h
Labels: pr-awaiting-review

#20073 [operator] Fix expand_dims
  CONTRIBUTORS.md
  python/mxnet/numpy/multiarray.py
Labels: pr-awaiting-review

#20075 [v1.x] Rearrange ONNX tests in Nightly CI
  ci/docker/runtime_functions.sh
  pytest.ini
  tests/nightly/JenkinsfileForBinaries
  tests/python-pytest/onnx/test_onnxruntime_cv.py
  tests/python-pytest/onnx/test_onnxruntime_nlp.py
Labels: pr-awaiting-merge

#20060 [v1.x] ONNX export support for GRU
  python/mxnet/contrib/onnx/mx2onnx/_op_translations.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20101 [FFI] part2: npx.pick, npx.convolution, npx.deconvolution
  python/mxnet/base.py
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
  src/api/operator/numpy_extension/npx_convolution_op.cc
  src/api/operator/numpy_extension/npx_deconvolution_op.cc
  src/api/operator/numpy_extension/npx_pick_op.cc
  src/operator/nn/convolution-inl.h
  src/operator/nn/deconvolution-inl.h
  src/operator/tensor/broadcast_reduce_op.h
Labels: pr-awaiting-review

#20102 [FFI] Part3: npx.pooling, npx.dropout, npx.one_hot, npx.rnn
  python/mxnet/base.py
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
  src/api/operator/numpy_extension/npx_dropout_op.cc
  src/api/operator/numpy_extension/npx_one_hot_op.cc
  src/api/operator/numpy_extension/npx_pooling_op.cc
  src/api/operator/numpy_extension/npx_rnn_op.cc
  src/operator/nn/dropout-inl.h
  src/operator/nn/pooling-inl.h
  src/operator/rnn-inl.h
  src/operator/tensor/indexing_op.h
Labels: pr-awaiting-review

#20106 [v1.x] Fix typo in ONNX nightly tests
  tests/nightly/JenkinsfileForBinaries
Labels: pr-awaiting-merge
