Repository apache/mxnet, pull requests merged in 2021-05, with the labels that each got.

#20231 [v1.x] ONNX optimize softmax
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
Labels: pr-awaiting-review

#20021 [v1.x] Update for MXNet 1.8.0 website release
  docs/static_site/src/_config.yml
  docs/static_site/src/_config_beta.yml
  docs/static_site/src/_config_prod.yml
  docs/static_site/src/_includes/get_started/get_started.html
  docs/static_site/src/_includes/get_started/gpu_snippet.md
  docs/static_site/src/_includes/get_started/linux/python/cpu/pip.md
  docs/static_site/src/_includes/get_started/linux/python/gpu/pip.md
  docs/static_site/src/_includes/get_started/pip_snippet.md
  docs/static_site/src/_includes/header.html
  docs/static_site/src/pages/get_started/download.md
Labels: pr-awaiting-merge

#19975 updated news.md and readme.md for 1.8.0 release
  NEWS.md
  README.md
Labels: pr-awaiting-review

#20230 [v1.x] Add ONNX model support matrix
  python/mxnet/onnx/README.md
  tools/onnx/generate_model_support_matrix.py
Labels: pr-awaiting-merge

#20233 [BUGFIX] fix numpy op fallback bug when ndarray in kwargs
  python/mxnet/numpy/multiarray.py
  tests/python/unittest/test_numpy_op.py
Labels: Numpy, pr-awaiting-review

#20168 [DOC] Update Website to Add Prerequisites for GPU pip install
  docs/static_site/src/_includes/get_started/cloud/cpu.md
  docs/static_site/src/_includes/get_started/cloud/gpu.md
  docs/static_site/src/_includes/get_started/gpu_snippet.md
  docs/static_site/src/_includes/get_started/linux/python/cpu/docker.md
  docs/static_site/src/_includes/get_started/linux/python/cpu/pip.md
  docs/static_site/src/_includes/get_started/linux/python/gpu/docker.md
  docs/static_site/src/_includes/get_started/linux/python/gpu/pip.md
  python/mxnet/base.py
Labels: pr-awaiting-review

#20240 [v1.x] Fix ONNX test divided by zero
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-merge

#20242 [LICENSE] switch from DISCLAIMER-WIP to DISCLAIMER
  DISCLAIMER
  DISCLAIMER-WIP
  ci/docker/runtime_functions.sh
  rat-excludes
  tools/pip/MANIFEST.in
  tools/staticbuild/build.sh
Labels: pr-work-in-progress

#20245 [v1.x] ONNX example for CV model inference
  example/onnx/README.md
  example/onnx/cv_model_inference.py
Labels: pr-awaiting-review

#20250 [v1.x] ONNX support for _split_v2
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20246 [v1.x] ONNX add support coverage for Reshape and lstm
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20107 [v1.x][BUGFIX] Implement oneDNN deconvolution primitives to deconvolution 2D
  src/operator/nn/mkldnn/mkldnn_deconvolution-inl.h
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
  tests/python/mkl/test_mkldnn.py
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#20258 [v1.x] ONNX Change some 10D shapes to 8D
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
Labels: pr-awaiting-review

#20259 [v1.x] ONNX export support broadcast_not_equal
  python/mxnet/onnx/mx2onnx/_export_onnx.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-merge

#20252 [v1.x] Add aarch64 support
  ci/docker/Dockerfile.publish.ubuntu1804_aarch64_cpu
  ci/docker/install/ubuntu_aarch64_publish.sh
  config/distribution/linux_aarch64_cpu.cmake
  tools/dependencies/make_shared_dependencies.sh
  tools/dependencies/openssl.sh
  tools/pip/setup.py
  tools/staticbuild/build.sh
  tools/staticbuild/build_lib_cmake.sh
Labels: pr-awaiting-review

#20261 [v1.x] ONNX: fix error handling when op is not registered
  python/mxnet/onnx/README.md
  python/mxnet/onnx/mx2onnx/_export_onnx.py
Labels: pr-awaiting-merge

#20264 [v1.x] ONNX tweak Resize op
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20228 [FEATURE] Fusing LeakyRelu post operator in Fully Connected symbol
  src/operator/subgraph/mkldnn/mkldnn_fc-inl.h
  src/operator/subgraph/mkldnn/mkldnn_fc.cc
  src/operator/subgraph/mkldnn/mkldnn_fc_property.h
  tests/python/mkl/subgraphs/test_fc_subgraph.py
Labels: pr-awaiting-review

#20269 [v1.x] ONNX docs and tutorial revision
  docs/python_docs/environment.yml
  docs/python_docs/python/tutorials/deploy/export/onnx.md
  example/onnx/cv_model_inference.py
  python/mxnet/onnx/README.md
  python/mxnet/onnx/mx2onnx/_export_model.py
Labels: pr-awaiting-review

#20263 [website] Fix Jinja2 version for python doc
  docs/python_docs/requirements
Labels: pr-awaiting-review

#20272 [v1.x] onnx fix rnn
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
Labels: pr-awaiting-review

#20162 Adding MxNet.Sharp package to the ecosystem page
  docs/static_site/src/assets/img/mxnet_sharp.png
  docs/static_site/src/pages/ecosystem.html
Labels: pr-awaiting-review

#20276 Add code signing key
  KEYS
Labels: pr-awaiting-merge

#20137 [v1.x][FEATURE] Add MKLDNN Deconvolution 1D and 3D support
  src/operator/nn/deconvolution-inl.h
  src/operator/nn/deconvolution.cc
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
  tests/python/mkl/test_mkldnn.py
Labels: pr-awaiting-review

#20277 Fix precision vars initialization in TRT
  src/operator/subgraph/tensorrt/tensorrt-inl.h
Labels: pr-awaiting-review

#20291 [v1.9] backport #20277
  src/operator/subgraph/tensorrt/tensorrt-inl.h
Labels: pr-awaiting-review

#20268 [operator] Add logsigmoid activation function
  benchmark/opperf/nd_operations/nn_activation_operators.py
  benchmark/opperf/rules/default_params.py
  python/mxnet/amp/lists/symbol_bf16.py
  python/mxnet/amp/lists/symbol_fp16.py
  python/mxnet/ndarray/ndarray.py
  python/mxnet/numpy/multiarray.py
  python/mxnet/symbol/symbol.py
  src/api/operator/numpy_extension/npx_activation_op.cc
  src/common/cuda/rtc/backward_functions-inl.h
  src/common/cuda/rtc/forward_functions-inl.h
  src/operator/fusion/fused_op-inl.h
  src/operator/mshadow_op.h
  src/operator/nn/activation-inl.h
  src/operator/nn/activation.cc
  src/operator/nn/activation.cu
  src/operator/nn/mkldnn/mkldnn_act.cc
  src/operator/operator_tune.cc
  src/operator/tensor/elemwise_unary_op_basic.cc
  src/operator/tensor/elemwise_unary_op_basic.cu
  tests/cpp/operator/activation_perf.cc
  tests/python/mkl/subgraphs/test_conv_subgraph.py
  tests/python/mkl/subgraphs/test_fc_subgraph.py
  tests/python/unittest/test_operator.py
Labels: pr-work-in-progress

#20202 [v1.x] OneDNN pooling operator, additional function to prepare kernels
  src/operator/nn/mkldnn/mkldnn_pooling.cc
Labels: pr-awaiting-review

#20283 [v1.x] ONNX export for large model
  python/mxnet/onnx/README.md
  python/mxnet/onnx/mx2onnx/_export_model.py
  python/mxnet/onnx/mx2onnx/_export_onnx.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  tests/python-pytest/onnx/test_onnxruntime_cv.py
Labels: pr-awaiting-review

#20295 [v1.x] ONNX fix embedding dtype and output order
  python/mxnet/onnx/mx2onnx/_export_onnx.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
Labels: pr-awaiting-review

#19426 [FEATURE] Use RTC for reduction ops
  src/common/cuda/rtc.cc
  src/common/cuda/rtc/backward_functions-inl.h
  src/common/cuda/rtc/forward_functions-inl.h
  src/common/cuda/rtc/reducer-inl.h
  src/common/cuda/rtc/special_functions-inl.h
  src/common/cuda/rtc/util-inl.h
  src/operator/mshadow_op.h
  src/operator/nn/group_norm-inl.h
  src/operator/nn/layer_norm-inl.h
  src/operator/nn/layer_norm.cc
  src/operator/nn/layer_norm.cu
  src/operator/nn/moments-inl.h
  src/operator/numpy/linalg/broadcast_reduce_customized-inl.cuh
  src/operator/numpy/linalg/broadcast_reduce_customized-inl.h
  src/operator/numpy/linalg/broadcast_reduce_op_customized.h
  src/operator/numpy/linalg/np_norm-inl.h
  src/operator/numpy/np_broadcast_reduce_op.cc
  src/operator/numpy/np_broadcast_reduce_op.cuh
  src/operator/numpy/np_broadcast_reduce_op.h
  src/operator/numpy/np_broadcast_reduce_op_boolean.cu
  src/operator/numpy/np_broadcast_reduce_op_index.cu
  src/operator/numpy/np_broadcast_reduce_op_value.cu
  src/operator/numpy/np_constraint_check.h
  src/operator/numpy/np_cross-inl.h
  src/operator/numpy/np_elemwise_broadcast_op.h
  src/operator/numpy/np_kron-inl.h
  src/operator/numpy/np_tensordot_op-inl.h
  src/operator/numpy/np_where_op-inl.h
  src/operator/numpy/random/dist_common.h
  src/operator/numpy/random/np_exponential_op.h
  src/operator/numpy/random/np_gamma_op.h
  src/operator/numpy/random/np_location_scale_op.h
  src/operator/numpy/random/np_normal_op.h
  src/operator/numpy/random/np_pareto_op.h
  src/operator/numpy/random/np_rayleigh_op.h
  src/operator/numpy/random/np_weibull_op.h
  src/operator/quantization/quantization_utils.h
  src/operator/quantization/quantize_v2-inl.h
  src/operator/quantization/requantize-inl.h
  src/operator/random/pdf_op.h
  src/operator/tensor/broadcast_reduce-inl.cuh
  src/operator/tensor/broadcast_reduce-inl.h
  src/operator/tensor/broadcast_reduce_minmax_value.cu
  src/operator/tensor/broadcast_reduce_op.cc
  src/operator/tensor/broadcast_reduce_op.h
  src/operator/tensor/broadcast_reduce_op_value.cu
  src/operator/tensor/broadcast_reduce_prod_value.cu
  src/operator/tensor/broadcast_reduce_sum_value.cu
  src/operator/tensor/elemwise_binary_broadcast_op.cc
  src/operator/tensor/elemwise_binary_broadcast_op.h
  src/operator/tensor/matrix_op-inl.h
  src/operator/tensor/reduce_rtc.cc
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-review

#20305 [v1.9.x] ONNX fix embedding dtype and output order
  python/mxnet/onnx/mx2onnx/_export_onnx.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
Labels: pr-awaiting-merge

#20294 [v1.x] Enable MKLDNN + APL Integration in CD
  cd/python/docker/Dockerfile
  cd/python/docker/python_images.sh
  ci/docker/Dockerfile.publish.ubuntu1804_aarch64_cpu
  ci/docker/install/ubuntu_aarch64_publish.sh
  config/distribution/linux_aarch64_cpu.cmake
  docs/static_site/src/_includes/get_started/linux/python/cpu/pip.md
  tools/pip/doc/AARCH64_CPU_ADDITIONAL.md
Labels: pr-awaiting-review
