Repository apache/mxnet, pull requests merged in 2021-08, with the labels that each got.

#20459 [BUGFIX] Fix backport of SoftmaxOutput implementation using onednn kernels
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_ops-inl.h
  src/operator/nn/mkldnn/mkldnn_softmax_output.cc
  src/operator/softmax_output.cc
Labels: pr-awaiting-review

#20406 Flake8 package checking python coding style: test_mkldnn.py, small tidy up
  tests/python/mkl/test_mkldnn.py
Labels: pr-awaiting-review

#20481 [BUGFIX] Remove duplicated project command in CMakeLists.txt
  CMakeLists.txt
Labels: pr-awaiting-review

#20484 [FEATURE] Load libcuda with dlopen instead of dynamic linking
  CMakeLists.txt
  src/common/cuda/rtc.cc
  src/initialize.cc
  src/initialize.h
Labels: pr-awaiting-merge

#20487 [DOC][v2.0] Part1: Link Check
  docs/python_docs/python/Makefile
  docs/python_docs/python/tutorials/deploy/export/onnx.md
  docs/python_docs/python/tutorials/getting-started/gluon_from_experiment_to_deployment.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/custom-layer.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/save_load_params.md
  docs/python_docs/python/tutorials/packages/gluon/loss/loss.md
  docs/python_docs/python/tutorials/packages/gluon/text/gnmt.rst
  docs/python_docs/python/tutorials/packages/gluon/training/fit_api_tutorial.md
  docs/python_docs/python/tutorials/packages/gluon/training/normalization/index.md
  docs/python_docs/python/tutorials/performance/backend/profiler.md
  python/mxnet/numpy/fallback.py
  python/mxnet/onnx/mx2onnx/_export_model.py
  src/io/iter_mnist.cc
  src/operator/svm_output.cc
  src/operator/tensor/matrix_op.cc
Labels: pr-awaiting-review

#20492 [v1.9.x] Make sure files with 2 licenses are listed properly in LICENSE.
  LICENSE
  src/operator/numpy/np_einsum_op-inl.h
Labels: pr-awaiting-review

#20496 [v1.9.x]Update git repo reference
  3rdparty/mshadow/README.md
  NEWS.md
  R-package/R/zzz.R
  R-package/vignettes/CallbackFunction.Rmd
  R-package/vignettes/CustomIterator.Rmd
  R-package/vignettes/mnistCompetition.Rmd
  README.md
  docker/Dockerfiles/Dockerfile.in.lib.cpu
  docker/Dockerfiles/Dockerfile.in.lib.gpu
  docs/static_site/src/pages/api/faq/caffe.md
  docs/static_site/src/pages/api/faq/cloud.md
  docs/static_site/src/pages/api/faq/multi_devices.md
  docs/static_site/src/pages/api/faq/new_op.md
  docs/static_site/src/pages/api/faq/perf.md
  docs/static_site/src/pages/api/faq/recordio.md
  docs/static_site/src/pages/api/faq/s3_integration.md
  docs/static_site/src/pages/api/faq/smart_device.md
  docs/static_site/src/pages/api/faq/visualize_graph.md
  docs/static_site/src/pages/api/r/docs/tutorials/callback_function.md
  docs/static_site/src/pages/api/r/docs/tutorials/custom_iterator.md
  docs/static_site/src/pages/api/r/docs/tutorials/five_minutes_neural_network.md
  docs/static_site/src/pages/api/r/docs/tutorials/mnist_competition.md
  docs/static_site/src/pages/api/scala/docs/tutorials/char_lstm.md
  docs/static_site/src/pages/api/scala/docs/tutorials/mnist.md
  example/README.md
  example/caffe/README.md
  example/image-classification/README.md
  example/kaggle-ndsb1/training_curves.py
  example/rcnn/README.md
  example/reinforcement-learning/dqn/operators.py
  example/ssd/README.md
  julia/docs/src/index.md
  julia/docs/src/user-guide/install.md
  perl-package/AI-MXNet/lib/AI/MXNet.pm
  perl-package/AI-MXNet/lib/AI/MXNet/LRScheduler.pm
  plugin/caffe/README.md
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/rnn/TestCharRnn.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/rnn/TrainCharRnn.scala
  src/engine/naive_engine.cc
  src/engine/threaded_engine.h
  src/operator/svm_output.cc
  tools/coreml/converter/_layers.py
Labels: pr-awaiting-merge

#20430 [FEATURE] Asymmetric fc fc
  python/mxnet/contrib/quantization.py
  src/operator/nn/mkldnn/mkldnn_fully_connected-inl.h
  src/operator/nn/mkldnn/mkldnn_fully_connected.cc
  src/operator/quantization/asymmetric_quantize_graph_pass.cc
  src/operator/quantization/quantize_graph_pass.cc
  src/operator/quantization/quantize_graph_pass.h
  src/operator/subgraph/mkldnn/mkldnn_fc-inl.h
  src/operator/subgraph/mkldnn/mkldnn_fc.cc
  tests/python/quantization/test_quantization.py
Labels: pr-awaiting-review

#20435 [v1.x] ONNX support for 2 layers bidirectional LSTM
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20510 [v1.x]Update git repo reference
  3rdparty/mshadow/README.md
  NEWS.md
  R-package/R/zzz.R
  R-package/vignettes/CallbackFunction.Rmd
  R-package/vignettes/CustomIterator.Rmd
  R-package/vignettes/mnistCompetition.Rmd
  README.md
  docker/Dockerfiles/Dockerfile.in.lib.cpu
  docker/Dockerfiles/Dockerfile.in.lib.gpu
  docs/static_site/src/pages/api/faq/caffe.md
  docs/static_site/src/pages/api/faq/cloud.md
  docs/static_site/src/pages/api/faq/multi_devices.md
  docs/static_site/src/pages/api/faq/new_op.md
  docs/static_site/src/pages/api/faq/perf.md
  docs/static_site/src/pages/api/faq/recordio.md
  docs/static_site/src/pages/api/faq/s3_integration.md
  docs/static_site/src/pages/api/faq/smart_device.md
  docs/static_site/src/pages/api/faq/visualize_graph.md
  docs/static_site/src/pages/api/r/docs/tutorials/callback_function.md
  docs/static_site/src/pages/api/r/docs/tutorials/custom_iterator.md
  docs/static_site/src/pages/api/r/docs/tutorials/five_minutes_neural_network.md
  docs/static_site/src/pages/api/r/docs/tutorials/mnist_competition.md
  docs/static_site/src/pages/api/scala/docs/tutorials/char_lstm.md
  docs/static_site/src/pages/api/scala/docs/tutorials/mnist.md
  example/README.md
  example/caffe/README.md
  example/image-classification/README.md
  example/kaggle-ndsb1/training_curves.py
  example/rcnn/README.md
  example/reinforcement-learning/dqn/operators.py
  example/ssd/README.md
  julia/docs/src/index.md
  julia/docs/src/user-guide/install.md
  perl-package/AI-MXNet/lib/AI/MXNet.pm
  perl-package/AI-MXNet/lib/AI/MXNet/LRScheduler.pm
  plugin/caffe/README.md
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/rnn/TestCharRnn.scala
  scala-package/examples/src/main/scala/org/apache/mxnetexamples/rnn/TrainCharRnn.scala
  src/engine/naive_engine.cc
  src/engine/threaded_engine.h
  src/operator/svm_output.cc
  tools/coreml/converter/_layers.py
Labels: pr-awaiting-review

#19896 [FEATURE] OneDNN adaptive pooling support was added to mxnet.
  src/operator/contrib/adaptive_avg_pooling-inl.h
  src/operator/contrib/adaptive_avg_pooling.cc
  src/operator/nn/mkldnn/mkldnn_adaptive_pooling-inl.h
  src/operator/nn/mkldnn/mkldnn_adaptive_pooling.cc
Labels: MKLDNN, pr-awaiting-review

#20512 [CI] Fix centos CI & website build
  docs/python_docs/python/scripts/conf.py
  docs/python_docs/python/tutorials/packages/gluon/blocks/custom-layer.md
  docs/python_docs/python/tutorials/packages/gluon/training/normalization/index.md
  docs/python_docs/python/tutorials/packages/legacy/ndarray/sparse/row_sparse.md
  docs/python_docs/python/tutorials/packages/onnx/inference_on_onnx_model.md
  docs/python_docs/python/tutorials/performance/backend/profiler.md
  python/mxnet/gluon/block.py
  python/mxnet/gluon/nn/basic_layers.py
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
  src/common/cuda/rtc.cc
  src/operator/tensor/dot.cc
  src/operator/tensor/indexing_op.cc
Labels: pr-awaiting-review

#20518 [v1.x] Backport #20492
  LICENSE
  src/operator/numpy/np_einsum_op-inl.h
Labels: pr-awaiting-review

#20506 [v1.x]Unpin Pillow version
  ci/docker/install/ubuntu_onnx.sh
  example/gluon/lipnet/requirements.txt
Labels: pr-awaiting-merge

#20444 [v1.x] [Backport] Add checks in batchnorm's infer shape
  src/operator/nn/batch_norm.cc
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  tests/cpp/operator/batchnorm_test.cc
Labels: pr-awaiting-review

#20495 [LICENSE] updated licenses for files under both ASF + BSD 3-clause
  cmake/Modules/FindJeMalloc.cmake
  rat-excludes
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  tools/license_header.py
Labels: pr-awaiting-merge

#20525 [v1.x] Docker cache enhancements
  ci/Jenkinsfile_docker_cache
  ci/build.py
  ci/docker/Dockerfile.build.ubuntu_gpu_cu80
  ci/docker/Dockerfile.build.ubuntu_gpu_cu90
  ci/docker/Dockerfile.build.ubuntu_gpu_cu92
  ci/docker/docker-compose.yml
  ci/docker_cache.py
Labels: pr-awaiting-review

#20519 [master] Forward-port #20492
  LICENSE
  src/operator/numpy/np_einsum_op-inl.h
Labels: pr-awaiting-review

#20517 [v1.9.x] modify erfinv implementation based on scipy
  src/operator/contrib/erfinv-inl.h
Labels: pr-awaiting-merge

#20526 [CI] Move link check from jenkins to github action
  .github/workflows/link_check.yml
  docs/python_docs/python/Makefile
Labels: pr-awaiting-merge

#20520 [v1.9.x][License] Fix redundant ASF and Microsoft Apache 2.0 license files
  LICENSE
  rat-excludes
  src/operator/contrib/deformable_convolution-inl.h
  src/operator/contrib/deformable_convolution.cc
  src/operator/contrib/deformable_convolution.cu
  src/operator/contrib/deformable_psroi_pooling-inl.h
  src/operator/contrib/deformable_psroi_pooling.cc
  src/operator/contrib/deformable_psroi_pooling.cu
  src/operator/contrib/modulated_deformable_convolution-inl.h
  src/operator/contrib/modulated_deformable_convolution.cc
  src/operator/contrib/modulated_deformable_convolution.cu
  src/operator/contrib/multi_proposal-inl.h
  src/operator/contrib/multi_proposal.cc
  src/operator/contrib/multi_proposal.cu
  src/operator/contrib/psroi_pooling.cc
  src/operator/contrib/psroi_pooling.cu
  tools/license_header.py
Labels: pr-awaiting-review

#20490 [DOC][v2.0] Part3: Evaluate Notebooks
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_website_beta
  ci/jenkins/Jenkinsfile_website_full
  ci/jenkins/Jenkinsfile_website_full_pr
  ci/jenkins/Jenkinsfile_website_nightly
  ci/jenkins/Jenkinsfile_website_python_docs
  ci/jenkins/Jenkinsfile_website_version_artifacts
  docs/python_docs/python/scripts/md2ipynb.py
  docs/python_docs/python/tutorials/deploy/export/onnx.md
  docs/python_docs/python/tutorials/deploy/inference/image_classification_jetson.md
  docs/python_docs/python/tutorials/extend/customop.md
  docs/python_docs/python/tutorials/getting-started/crash-course/2-create-nn.md
  docs/python_docs/python/tutorials/getting-started/crash-course/4-components.md
  docs/python_docs/python/tutorials/getting-started/crash-course/5-datasets.md
  docs/python_docs/python/tutorials/getting-started/crash-course/6-train-nn.md
  docs/python_docs/python/tutorials/getting-started/crash-course/7-use-gpus.md
  docs/python_docs/python/tutorials/getting-started/gluon_from_experiment_to_deployment.md
  docs/python_docs/python/tutorials/getting-started/logistic_regression_explained.md
  docs/python_docs/python/tutorials/getting-started/to-mxnet/pytorch.md
  docs/python_docs/python/tutorials/packages/autograd/index.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/activations/activations.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/custom-layer.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/hybridize.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/init.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/naming.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/nn.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/parameters.md
  docs/python_docs/python/tutorials/packages/gluon/blocks/save_load_params.md
  docs/python_docs/python/tutorials/packages/gluon/data/datasets.md
  docs/python_docs/python/tutorials/packages/gluon/image/info_gan.md
  docs/python_docs/python/tutorials/packages/gluon/image/mnist.md
  docs/python_docs/python/tutorials/packages/gluon/loss/custom-loss.md
  docs/python_docs/python/tutorials/packages/gluon/loss/kl_divergence.md
  docs/python_docs/python/tutorials/packages/gluon/loss/loss.md
  docs/python_docs/python/tutorials/packages/gluon/training/fit_api_tutorial.md
  docs/python_docs/python/tutorials/packages/gluon/training/learning_rates/learning_rate_finder.md
  docs/python_docs/python/tutorials/packages/gluon/training/learning_rates/learning_rate_schedules.md
  docs/python_docs/python/tutorials/packages/gluon/training/normalization/index.md
  docs/python_docs/python/tutorials/packages/gluon/training/trainer.md
  docs/python_docs/python/tutorials/packages/kvstore/kvstore.md
  docs/python_docs/python/tutorials/packages/np/cheat-sheet.md
  docs/python_docs/python/tutorials/packages/onnx/fine_tuning_gluon.md
  docs/python_docs/python/tutorials/packages/optimizer/index.md
  docs/python_docs/python/tutorials/performance/backend/amp.md
  docs/python_docs/python/tutorials/performance/backend/profiler.md
Labels: pr-awaiting-review

#20530 [v1.9.x] Remove cpp-predict example due to licensing issues
  tools/source-exclude-artifacts.txt
Labels: pr-awaiting-merge

#20534 [CI] Fix link-check
  .github/workflows/link_check.yml
Labels: pr-awaiting-review

#20523 [v1.9.x] stop closing opened libs
  include/mxnet/c_api.h
  python/mxnet/library.py
  src/c_api/c_api.cc
  src/initialize.cc
  src/initialize.h
Labels: pr-awaiting-merge

#20532 Enable other axes support: the take test
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#20537 [v1.9.x] Backport docker cache fixes
  ci/Jenkinsfile_docker_cache
  ci/Jenkinsfile_utils.groovy
  ci/build.py
  ci/docker/Dockerfile.build.ubuntu_gpu_cu80
  ci/docker/Dockerfile.build.ubuntu_gpu_cu90
  ci/docker/Dockerfile.build.ubuntu_gpu_cu92
  ci/docker/docker-compose.yml
  ci/docker/install/ubuntu_core.sh
  ci/docker_cache.py
Labels: pr-awaiting-review

#20535 [v1.x] Port #20530
  tools/source-exclude-artifacts.txt
Labels: pr-awaiting-review

#20536 Port #20530 (license fixes) from v1.x.
  tools/source-exclude-artifacts.txt
Labels: pr-awaiting-review

#20545 [DOC] Pin jupyter-client
  docs/python_docs/requirements
Labels: pr-awaiting-review

#20543 [CI] Add node for website full build and nightly build
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_website_full_pr
  ci/jenkins/Jenkinsfile_website_python_docs
Labels: pr-awaiting-review

#19562 [operator] Integrate oneDNN layer normalization implementation
  src/operator/nn/layer_norm-inl.h
  src/operator/nn/layer_norm.cc
  src/operator/nn/layer_norm.cu
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_dot-inl.h
  src/operator/nn/mkldnn/mkldnn_batch_dot.cc
  src/operator/nn/mkldnn/mkldnn_layer_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_layer_norm.cc
  src/operator/nn/mkldnn/mkldnn_ops-inl.h
Labels: MKLDNN, pr-awaiting-review

#20551 [v1.x] [LICENSE] modify erfinv implementation based on scipy (backport #20517)
  src/operator/contrib/erfinv-inl.h
Labels: pr-awaiting-review
