Repository apache/mxnet, pull requests merged in 2021-04, with the labels that each got.

#20114 [FFI] fix masked_softmax
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
  src/api/operator/numpy_extension/npx_softmax_op.cc
  src/operator/nn/softmax-inl.h
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-review

#20116 [v1.x][CD] Fix CD cu102 110 112 cuda compatibility
  ci/docker/Dockerfile.build.ubuntu_gpu_cu102
  ci/docker/Dockerfile.build.ubuntu_gpu_cu110
  ci/docker/Dockerfile.build.ubuntu_gpu_cu112
Labels: pr-awaiting-review

#20117 [v1.x] Split ONNX CV tests in nightly CI
  ci/docker/runtime_functions.sh
  pytest.ini
  tests/nightly/JenkinsfileForBinaries
  tests/python-pytest/onnx/test_onnxruntime_cv.py
Labels: pr-awaiting-merge

#20094 ONNX Graduation
  python/mxnet/contrib/onnx/__init__.py
  python/mxnet/onnx/README.md
  python/mxnet/onnx/__init__.py
  python/mxnet/onnx/mx2onnx/LICENSE
  python/mxnet/onnx/mx2onnx/__init__.py
  python/mxnet/onnx/mx2onnx/_export_helper.py
  python/mxnet/onnx/mx2onnx/_export_model.py
  python/mxnet/onnx/mx2onnx/_export_onnx.py
  python/mxnet/onnx/mx2onnx/_op_translations.py
  python/mxnet/onnx/setup.py
  tests/python-pytest/onnx/backend.py
  tests/python-pytest/onnx/test_onnxruntime_cv.py
  tests/python-pytest/onnx/test_onnxruntime_nlp.py
  tests/python-pytest/onnx/test_operators.py
  tools/license_header.py
Labels: pr-awaiting-review

#20120 [v1.x] [CD] Fix nightly docker missing lib
  cd/python/docker/Dockerfile
  cd/utils/mxnet_base_image.sh
Labels: pr-awaiting-review

#20121 [CD] Fix nightly docker missing libs
  cd/python/docker/Dockerfile
Labels: pr-awaiting-review

#20091 Mark test_layer_norm and test_norm flaky
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#20122 [v1.x] Skip One ONNX Test
  tests/python-pytest/onnx/test_onnxruntime_cv.py
Labels: pr-awaiting-review

#20115 [CD] Fix the name of the pip wheels in CD
  ci/Jenkinsfile_utils.groovy
  ci/build.py
  tools/pip/setup.py
Labels: pr-awaiting-review

#20127 [PIP] set osx deploy target for v1.x wheels
  config/distribution/darwin_cpu.cmake
Labels: pr-awaiting-review

#20126 [CD] Attemp to fix nightly docker for master cu112
  cd/utils/mxnet_base_image.sh
Labels: pr-awaiting-review

#20113 [v1.x] MXNet export for ONNX 1.8 support
  ci/docker/install/ubuntu_onnx.sh
  ci/docker/runtime_functions.sh
  python/mxnet/onnx/mx2onnx/__init__.py
  python/mxnet/onnx/mx2onnx/_export_model.py
  python/mxnet/onnx/mx2onnx/_export_onnx.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset11.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tests/nightly/JenkinsfileForBinaries
  tools/license_header.py
Labels: pr-awaiting-review

#20124 [Operator] Fix dropout and doc
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
Labels: pr-awaiting-review

#20125 Revert "Mark test_layer_norm and test_norm flaky"
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#20130 [v1.x] fix onnx type inference issue
  python/mxnet/onnx/mx2onnx/_export_onnx.py
Labels: pr-awaiting-review

#20139 [v1.x] Add mx2onnx operator support matrix
  python/mxnet/onnx/README.md
  python/mxnet/onnx/__init__.py
  python/mxnet/onnx/mx2onnx/__init__.py
  python/mxnet/onnx/mx2onnx/_export_model.py
  python/mxnet/onnx/mx2onnx/_export_onnx.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  tools/license_header.py
  tools/onnx/generate_op_support_matrix.py
Labels: pr-awaiting-review

#20152 [BUGFIX] add inline for __half2float_warp
  3rdparty/mshadow/mshadow/half.h
Labels: pr-awaiting-review

#20142 [Backport 1.x] Fix for optimize_for multiple subgraph properties issue
  src/c_api/c_api_symbolic.cc
Labels: pr-awaiting-review

#20146 Define NVML_NO_UNVERSIONED_FUNC_DEFS
  CMakeLists.txt
Labels: pr-awaiting-merge

#20110 [FFI] part5: npx.batch_dot, npx.arange_like, npx.broadcast_like
  python/mxnet/base.py
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
  src/api/operator/numpy_extension/npx_arange_like_op.cc
  src/api/operator/numpy_extension/npx_batch_dot_op.cc
  src/api/operator/numpy_extension/npx_broadcast_like_op.cc
  src/operator/tensor/broadcast_reduce_op.h
  src/operator/tensor/dot-inl.h
  src/operator/tensor/init_op.h
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-review

#20161 [v1.x] increase onnx test tolerance
  tests/python-pytest/onnx/test_onnxruntime_nlp.py
Labels: pr-awaiting-review

#20169 [BUGFIX] Fix broadcast_like
  src/api/operator/numpy_extension/npx_broadcast_like_op.cc
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-review

#20157 [v1.x] fix mx2onnx wheel
  python/mxnet/onnx/mx2onnx/_op_translations/__init__.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tools/license_header.py
Labels: pr-awaiting-review

#20166 [v1.x][Bugfix] Fix take gradient
  src/operator/tensor/indexing_op.h
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#20165 [v1.x] ONNX legacy operator fix and test
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20163 [Feature] Add oneDNN support for interleaved_matmul_selfatt_* operators (fp32/int8)
  src/operator/subgraph/mkldnn/mkldnn_subgraph_property.cc
  src/operator/subgraph/mkldnn/mkldnn_transformer-inl.h
  src/operator/subgraph/mkldnn/mkldnn_transformer.cc
  src/operator/subgraph/mkldnn/mkldnn_transformer_post_quantize_property.h
  src/operator/subgraph/mkldnn/mkldnn_transformer_property.h
  tests/python/mkl/test_subgraph.py
Labels: pr-awaiting-review

#20167 [v1.8] Fix version dropdown in python doc pages
  docs/python_docs/themes/mx-theme/mxtheme/header_top.html
Labels: pr-work-in-progress

#20105 [FFI] part4: npx.embedding, npx.topk, npx.layer_norm, npx.leaky_relu
  python/mxnet/base.py
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
  src/api/operator/numpy_extension/npx_embedding_op.cc
  src/api/operator/numpy_extension/npx_layer_norm_op.cc
  src/api/operator/numpy_extension/npx_leaky_relu_op.cc
  src/api/operator/numpy_extension/npx_topk_op.cc
  src/operator/leaky_relu-inl.h
  src/operator/nn/layer_norm-inl.h
  src/operator/tensor/indexing_op.h
  src/operator/tensor/ordering_op-inl.h
  tests/python/unittest/test_numpy_gluon.py
Labels: pr-awaiting-review

#20192 [v1.x] Add onnx export operator unit tests.
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20194 [v1.x] Add more onnx operator export unit tests
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20195 [v1.x] ONNX support rewrite norm
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20200 [COMMUNITY] add Moises Hernandez as a new committer
  CONTRIBUTORS.md
Labels: Community, pr-awaiting-review

#20198 [v1.x] ONNX export support from arg/aux params
  python/mxnet/onnx/mx2onnx/_export_model.py
  tests/python-pytest/onnx/test_onnxruntime_cv.py
Labels: pr-awaiting-review

#20199 [v1.x] Bump onnxruntime version
  ci/docker/install/ubuntu_onnx.sh
Labels: pr-awaiting-review

#19971 [FEATURE] Fusing Leaky Relu operator in Fully Connected
  src/operator/subgraph/mkldnn/mkldnn_fc-inl.h
  src/operator/subgraph/mkldnn/mkldnn_fc.cc
  src/operator/subgraph/mkldnn/mkldnn_fc_property.h
  tests/python/mkl/test_subgraph.py
Labels: pr-awaiting-review

#20201 [COMMUNITY] add Anna Karbownik as a new committer
  CONTRIBUTORS.md
Labels: Community, pr-awaiting-review

#20179 [v1.x] onnx legacy operator unit tests + fixes
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review

#20208 [v1.x] skip 2 models in nightly ci
  tests/python-pytest/onnx/test_onnxruntime_cv.py
Labels: pr-awaiting-review

#20215 [BUGFIX] Fix UnicodeDecodeError in method doc (#20214)
  NEWS.md
  src/operator/numpy/np_pad_op-inl.h
Labels: pr-awaiting-review

#19905 [PERF] Moving GPU softmax to RTC and optimizations
  src/common/cuda/rtc/backward_functions-inl.h
  src/common/cuda/rtc/forward_functions-inl.h
  src/common/cuda/rtc/reducer-inl.h
  src/common/cuda/rtc/util-inl.h
  src/common/cuda/rtc/vectorization-inl.h
  src/common/cuda/utils.cc
  src/common/cuda/utils.h
  src/common/utils.h
  src/operator/mxnet_op.h
  src/operator/nn/log_softmax.cu
  src/operator/nn/softmax-inl.h
  src/operator/nn/softmax.cu
  src/operator/nn/softmin.cu
  src/operator/tensor/elemwise_binary_scalar_op.cc
Labels: pr-awaiting-review

#20209 [v1.x] ONNX fix log_softmax for opset 12
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
Labels: pr-awaiting-review

#20203 [Bugfix] Fix take gradient
  src/operator/tensor/indexing_op.h
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#20216 [v1.x] Fix gcc 10 build
  src/operator/tensor/elemwise_binary_broadcast_op_basic.cc
  src/operator/tensor/elemwise_binary_broadcast_op_basic.cu
Labels: pr-awaiting-review

#20212 [BUGFIX] Fix workspace of BoxNMS
  src/operator/contrib/bounding_box.cu
Labels: pr-awaiting-review

#20210 [v1.x] Add more ONNX model tests
  tests/python-pytest/onnx/test_onnxruntime_cv.py
Labels: pr-awaiting-merge

#20221 Reuse params from cached_op_args
  python/mxnet/gluon/block.py
Labels: pr-awaiting-review

#20229 [v1.8.x] Backport #20221
  python/mxnet/gluon/block.py
Labels: pr-awaiting-review

#20129 [BUGFIX][BACKPORT] Impose a plain format on padded concat output
  src/operator/nn/mkldnn/mkldnn_concat-inl.h
  src/operator/nn/mkldnn/mkldnn_concat.cc
  src/operator/nn/mkldnn/mkldnn_convolution.cc
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
  tests/python/mkl/test_mkldnn.py
Labels: pr-awaiting-review

#20188 [BUGFIX]try avoid the error in operator/tensor/amp_cast.h
  src/operator/tensor/amp_cast.h
Labels: pr-awaiting-review

#19976 [1.x] update news.md and readme.md for 1.8.0 release
  NEWS.md
  README.md
Labels: pr-awaiting-review

#19878 [BUGFIX] fix #18936, #18937
  src/operator/random/pdf_op.h
  tests/python/unittest/test_random.py
Labels: pr-awaiting-review

#20226 [v1.x] ONNX export support for RNN and sum_axis
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset12.py
  python/mxnet/onnx/mx2onnx/_op_translations/_op_translations_opset13.py
  tests/python-pytest/onnx/test_operators.py
Labels: pr-awaiting-review
