Repository apache/mxnet, pull requests merged in 2021-09, with the labels that each got.

#20533 [v1.x] Enabling BRGEMM FullyConnected based on shapes
  docs/static_site/src/pages/api/faq/env_var.md
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_fully_connected.cc
Labels: pr-awaiting-review

#20514 [REFACTOR] Asymmetric Quantization: deduplicate methods
  python/mxnet/contrib/quantization.py
  src/operator/quantization/asymmetric_quantize_graph_pass.cc
  src/operator/quantization/mkldnn/mkldnn_quantize_v2-inl.h
  src/operator/quantization/quantize_v2-inl.h
  tests/python/quantization/test_quantization.py
Labels: pr-awaiting-review

#20505 If variable is not used within the loop body, start the name with an underscore
  python/mxnet/gluon/contrib/estimator/estimator.py
  python/mxnet/operator.py
  python/mxnet/test_utils.py
  tests/nightly/dist_device_sync_kvstore_byteps.py
  tests/nightly/dist_device_sync_kvstore_custom.py
  tests/nightly/dist_sync_kvstore.py
  tests/nightly/test_kvstore.py
  tests/nightly/test_np_random.py
  tests/nightly/test_server_profiling.py
  tests/python/gpu/test_gluon_gpu.py
  tests/python/gpu/test_gluon_model_zoo_gpu.py
  tests/python/gpu/test_kvstore_gpu.py
  tests/python/gpu/test_operator_gpu.py
  tests/python/mkl/subgraphs/test_conv_subgraph.py
  tests/python/mkl/test_mkldnn.py
  tests/python/quantization/test_quantization.py
  tests/python/unittest/test_autograd.py
  tests/python/unittest/test_contrib_control_flow.py
  tests/python/unittest/test_contrib_gluon_data_vision.py
  tests/python/unittest/test_contrib_io.py
  tests/python/unittest/test_dgl_graph.py
  tests/python/unittest/test_engine.py
  tests/python/unittest/test_executor.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_gluon_data.py
  tests/python/unittest/test_gluon_probability_v2.py
  tests/python/unittest/test_gluon_rnn.py
  tests/python/unittest/test_gluon_trainer.py
  tests/python/unittest/test_image.py
  tests/python/unittest/test_io.py
  tests/python/unittest/test_kvstore.py
  tests/python/unittest/test_loss.py
  tests/python/unittest/test_ndarray.py
  tests/python/unittest/test_numpy_contrib_gluon_data_vision.py
  tests/python/unittest/test_numpy_gluon.py
  tests/python/unittest/test_numpy_interoperability.py
  tests/python/unittest/test_numpy_loss.py
  tests/python/unittest/test_numpy_ndarray.py
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_operator.py
  tests/python/unittest/test_profiler.py
  tests/python/unittest/test_random.py
  tests/python/unittest/test_sparse_ndarray.py
  tests/python/unittest/test_sparse_operator.py
  tests/python/unittest/test_symbol.py
Labels: pr-awaiting-review

#20568 [Backport] Enabling BRGEMM FullyConnected based on shapes
  docs/static_site/src/pages/api/faq/env_var.md
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_fully_connected.cc
Labels: pr-awaiting-review

#20562 [BUGFIX] Prohibit the use of the BLA_VENDOR flag when using MKL
  cmake/ChooseBlas.cmake
Labels: pr-awaiting-review

#20482 [BUGFIX] Fix accuracy issue due to reuse of primitives for MKLDNN-AArch64. Fixes #20265.
  CMakeLists.txt
  CONTRIBUTORS.md
  src/operator/operator_common.h
Labels: pr-awaiting-review

#20473 [v2.0][DOC] Add migration guide
  docs/python_docs/python/tutorials/getting-started/gluon_migration_guide.md
  docs/python_docs/python/tutorials/getting-started/index.rst
Labels: pr-awaiting-review

#20478 [API] Extend NumPy Array dtypes with int16, uint16, uint32, uint64
  3rdparty/mshadow/mshadow/base.h
  ci/docker/install/requirements
  ci/docker/runtime_functions.sh
  ci/jenkins/Jenkins_steps.groovy
  ci/jenkins/Jenkinsfile_unix_cpu
  contrib/tvmop/utils.py
  include/mxnet/runtime/packed_func.h
  include/mxnet/tensor_blob.h
  python/mxnet/ndarray/numpy/_op.py
  python/mxnet/numpy/utils.py
  src/ndarray/ndarray.cc
  src/ndarray/ndarray_function.cc
  src/operator/mxnet_op.h
  src/operator/numpy/np_elemwise_broadcast_logic_op.cc
  src/operator/numpy/np_init_op.h
  src/operator/operator_tune.cc
  src/operator/tensor/elemwise_binary_broadcast_op.h
  src/operator/tensor/elemwise_binary_op.h
  src/operator/tensor/elemwise_unary_op.h
  src/operator/tensor/init_op.h
  src/operator/tvmop/op_module.cc
Labels: pr-work-in-progress

#20570 [CMAKE] Fix Darwin Cmake with USE_TVM_OP ON
  CMakeLists.txt
Labels: pr-awaiting-merge

#20573 [Website] Fix website publish
  ci/docker/runtime_functions.sh
  docs/static_site/src/.asf.yaml
  docs/static_site/src/_config_prod.yml
Labels: pr-awaiting-merge

#20549 [FEATURE] MXIndexedRecordIO: avoid re-build index
  python/mxnet/recordio.py
Labels: pr-awaiting-review

#20563 [FEATURE] Add oneDNN support for npx.reshape and np.reshape
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_convolution.cc
  src/operator/nn/mkldnn/mkldnn_reshape.cc
  src/operator/numpy/np_matrix_op.cc
  src/operator/quantization/mkldnn/mkldnn_quantized_flatten.cc
  src/operator/tensor/matrix_op-inl.h
  src/operator/tensor/matrix_op.cc
Labels: pr-awaiting-review

#20580 [2.0] Split np_elemwise_broadcast_logic_op.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op.h
  src/operator/numpy/np_elemwise_broadcast_logic_op_and.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_and.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op_equal.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_equal.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op_greater.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_greater.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op_greater_equal.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_greater_equal.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op_less.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_less.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op_less_equal.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_less_equal.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op_not_equal.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_not_equal.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op_or.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_or.cu
  src/operator/numpy/np_elemwise_broadcast_logic_op_xor.cc
  src/operator/numpy/np_elemwise_broadcast_logic_op_xor.cu
  src/operator/numpy/np_elemwise_broadcast_op.cc
  src/operator/numpy/np_elemwise_broadcast_op.cu
  src/operator/numpy/np_elemwise_broadcast_op.h
  src/operator/numpy/np_elemwise_broadcast_op_add.cc
  src/operator/numpy/np_elemwise_broadcast_op_add.cu
  src/operator/numpy/np_elemwise_broadcast_op_mod.cc
  src/operator/numpy/np_elemwise_broadcast_op_mod.cu
  src/operator/numpy/np_elemwise_broadcast_op_mul.cc
  src/operator/numpy/np_elemwise_broadcast_op_mul.cu
  src/operator/numpy/np_elemwise_broadcast_op_pow.cc
  src/operator/numpy/np_elemwise_broadcast_op_pow.cu
  src/operator/numpy/np_elemwise_broadcast_op_scalar.cc
  src/operator/numpy/np_elemwise_broadcast_op_scalar.cu
  src/operator/numpy/np_elemwise_broadcast_op_sub.cc
  src/operator/numpy/np_elemwise_broadcast_op_sub.cu
Labels: pr-awaiting-review

#20597 [BUGFIX] Fix (de)conv
  python/mxnet/ndarray/numpy_extension/_op.py
Labels: pr-awaiting-review

#18683 Expand NVTX usage
  include/mxnet/c_api.h
  python/mxnet/cuda/__init__.py
  python/mxnet/cuda/nvtx.py
  src/c_api/c_api.cc
  src/common/cuda/nvtx.h
  src/engine/threaded_engine_perdevice.cc
  src/imperative/imperative_utils.h
  src/profiler/nvtx.cc
  src/profiler/nvtx.h
  src/profiler/profiler.h
Labels: pr-awaiting-review

#20500 [FEATURE] Add feature of retain_grad
  include/mxnet/c_api.h
  include/mxnet/imperative.h
  python/mxnet/ndarray/ndarray.py
  python/mxnet/numpy/multiarray.py
  src/c_api/c_api_ndarray.cc
  src/imperative/exec_pass.h
  src/imperative/imperative.cc
  src/nnvm/gradient.cc
  tests/python/unittest/test_autograd.py
Labels: pr-awaiting-review

#20349 Decouple OneDNN data structures in MXNet C++ API
  include/mxnet/ndarray.h
  src/ndarray/ndarray.cc
  src/operator/nn/concat.cc
  src/operator/nn/mkldnn/mkldnn_act.cc
  src/operator/nn/mkldnn/mkldnn_adaptive_pooling.cc
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  src/operator/nn/mkldnn/mkldnn_base.cc
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  src/operator/nn/mkldnn/mkldnn_concat.cc
  src/operator/nn/mkldnn/mkldnn_convolution.cc
  src/operator/nn/mkldnn/mkldnn_copy.cc
  src/operator/nn/mkldnn/mkldnn_deconvolution-inl.h
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
  src/operator/nn/mkldnn/mkldnn_fully_connected.cc
  src/operator/nn/mkldnn/mkldnn_log_softmax.cc
  src/operator/nn/mkldnn/mkldnn_lrn-inl.h
  src/operator/nn/mkldnn/mkldnn_pooling.cc
  src/operator/nn/mkldnn/mkldnn_reshape.cc
  src/operator/nn/mkldnn/mkldnn_slice.cc
  src/operator/nn/mkldnn/mkldnn_softmax.cc
  src/operator/nn/mkldnn/mkldnn_softmax_output.cc
  src/operator/nn/mkldnn/mkldnn_sum.cc
  src/operator/nn/mkldnn/mkldnn_transpose.cc
  src/operator/operator_common.h
  src/operator/quantization/mkldnn/mkldnn_dequantize-inl.h
  src/operator/quantization/mkldnn/mkldnn_quantize-inl.h
  src/operator/quantization/mkldnn/mkldnn_quantize_v2-inl.h
  src/operator/quantization/mkldnn/mkldnn_quantized_batch_norm.cc
  src/operator/quantization/mkldnn/mkldnn_quantized_concat.cc
  src/operator/quantization/mkldnn/mkldnn_quantized_conv.cc
  src/operator/quantization/mkldnn/mkldnn_quantized_elemwise_add.cc
  src/operator/quantization/mkldnn/mkldnn_quantized_fully_connected.cc
  src/operator/quantization/mkldnn/mkldnn_requantize-inl.h
  src/operator/subgraph/mkldnn/mkldnn_common.h
  src/operator/subgraph/mkldnn/mkldnn_conv.cc
  src/operator/subgraph/mkldnn/mkldnn_fc.cc
  src/operator/tensor/amp_cast.cc
  src/operator/tensor/cast_storage-inl.h
  tests/cpp/include/test_mkldnn.h
  tests/cpp/operator/mkldnn_operator_test.cc
  tests/cpp/operator/mkldnn_test.cc
Labels: pr-awaiting-review

#20604 [v2.0] Split Large Source Files
  src/operator/numpy/np_broadcast_reduce_op_value.cc
  src/operator/numpy/np_broadcast_reduce_op_value.cu
  src/operator/numpy/np_broadcast_reduce_op_value.h
  src/operator/numpy/np_broadcast_reduce_op_value_broadcast_to.cc
  src/operator/numpy/np_broadcast_reduce_op_value_broadcast_to.cu
  src/operator/numpy/np_broadcast_reduce_op_value_max.cc
  src/operator/numpy/np_broadcast_reduce_op_value_max.cu
  src/operator/numpy/np_broadcast_reduce_op_value_mean.cc
  src/operator/numpy/np_broadcast_reduce_op_value_mean.cu
  src/operator/numpy/np_broadcast_reduce_op_value_min.cc
  src/operator/numpy/np_broadcast_reduce_op_value_min.cu
  src/operator/numpy/np_broadcast_reduce_op_value_prod.cc
  src/operator/numpy/np_broadcast_reduce_op_value_prod.cu
  src/operator/numpy/np_broadcast_reduce_op_value_sum.cc
  src/operator/numpy/np_broadcast_reduce_op_value_sum.cu
  src/operator/numpy/np_dot_backward.cc
  src/operator/numpy/np_dot_backward.cu
  src/operator/numpy/np_dot_forward.cc
  src/operator/numpy/np_dot_forward.cu
  src/operator/numpy/np_kron_backward.cc
  src/operator/numpy/np_kron_backward.cu
  src/operator/numpy/np_kron_forward.cc
  src/operator/numpy/np_kron_forward.cu
  src/operator/numpy/np_moments_op.cu
  src/operator/numpy/np_where_backward_op.cc
  src/operator/numpy/np_where_backward_op.cu
  src/operator/numpy/np_where_forward_op.cc
  src/operator/numpy/np_where_forward_op.cu
Labels: pr-awaiting-merge

#20601 [BUGFIX] Fix NightlyTestForBinary in master branch
  python/mxnet/gluon/contrib/estimator/batch_processor.py
  tests/nightly/estimator/test_sentiment_rnn.py
  tests/nightly/test_kvstore.py
  tests/nightly/test_np_large_array.py
Labels: pr-awaiting-review

#20607 [v2.0][LICENSE] Port #20495
  cmake/Modules/FindJeMalloc.cmake
  rat-excludes
  src/operator/nn/mkldnn/mkldnn_base-inl.h
  tools/license_header.py
Labels: pr-awaiting-review

#20614 Add Code Signing Key
  KEYS
Labels: pr-awaiting-review

#20609 [v2.0][LICENSE] Port #20520
  LICENSE
  rat-excludes
  src/operator/contrib/deformable_psroi_pooling-inl.h
  src/operator/contrib/deformable_psroi_pooling.cc
  src/operator/contrib/deformable_psroi_pooling.cu
  src/operator/contrib/multi_proposal-inl.h
  src/operator/contrib/multi_proposal.cc
  src/operator/contrib/multi_proposal.cu
  src/operator/contrib/psroi_pooling.cc
  src/operator/contrib/psroi_pooling.cu
  src/operator/deformable_convolution-inl.h
  src/operator/deformable_convolution.cc
  src/operator/deformable_convolution.cu
  src/operator/modulated_deformable_convolution-inl.h
  src/operator/modulated_deformable_convolution.cc
  src/operator/modulated_deformable_convolution.cu
  tools/license_header.py
Labels: pr-awaiting-review

#20599 [FEATRURE] Add fusing FullyConnected with element-wise add
  src/operator/nn/mkldnn/mkldnn_fully_connected-inl.h
  src/operator/subgraph/build_subgraph.cc
  src/operator/subgraph/mkldnn/mkldnn_fc.cc
  src/operator/subgraph/mkldnn/mkldnn_fc_property.h
  src/operator/subgraph/mkldnn/mkldnn_fc_sum_fuse.h
  src/operator/subgraph/mkldnn/mkldnn_subgraph_property.cc
  tests/python/mkl/test_subgraph.py
Labels: pr-awaiting-review

#20292 [BACKPORT][BUGFIX][FEATURE] Add oneDNN 1D and 3D deconvolution support and fix bias
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/numpy_extension/_op.py
  src/operator/deformable_convolution-inl.h
  src/operator/modulated_deformable_convolution-inl.h
  src/operator/nn/convolution-inl.h
  src/operator/nn/deconvolution-inl.h
  src/operator/nn/deconvolution.cc
  src/operator/nn/mkldnn/mkldnn_deconvolution-inl.h
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
  tests/python/mkl/test_mkldnn.py
  tests/python/unittest/test_gluon.py
  tests/python/unittest/test_numpy_op.py
  tests/python/unittest/test_operator.py
Labels: pr-awaiting-review

#20617 [CI] Add Simple GitHub-Action Based License Checker
  .github/workflows/license_check.yml
  .licenserc.yaml
  LICENSE
  rat-excludes
  src/operator/contrib/krprod.cc
  src/operator/numpy/np_einsum_op-inl.h
  src/operator/numpy/np_einsum_op.cc
  src/operator/numpy/np_einsum_path_op-inl.h
  src/operator/subgraph/tensorrt/nnvm_to_onnx-inl.h
  src/operator/subgraph/tensorrt/onnx_to_tensorrt.h
  src/operator/subgraph/tensorrt/tensorrt-inl.h
  tests/python/gpu/test_numpy_op.py
Labels: pr-awaiting-review

#20598 [WIP] [v1.9.x] license updates
  .github/workflows/license_check.yml
  .licenserc.yaml
  LICENSE
  rat-excludes
  src/operator/contrib/krprod.cc
  src/operator/numpy/np_einsum_op-inl.h
  src/operator/numpy/np_einsum_op.cc
  src/operator/numpy/np_einsum_path_op-inl.h
  src/operator/subgraph/tensorrt/nnvm_to_onnx-inl.h
  src/operator/subgraph/tensorrt/onnx_to_tensorrt.h
  src/operator/subgraph/tensorrt/tensorrt-inl.h
  src/operator/subgraph/tensorrt/tensorrt_int8_calibrator.h
Labels: Licenses, pr-work-in-progress

#20589 [v1.x][BUGFIX][ONEDNN] Remove next_impl calls from deconvolution
  src/operator/nn/mkldnn/mkldnn_deconvolution.cc
Labels: pr-awaiting-review

#20615 Fast cuDNN BatchNorm NHWC kernels support
  python/mxnet/amp/lists/symbol_fp16.py
  src/operator/nn/batch_norm.cc
  src/operator/nn/batch_norm.cu
  src/operator/nn/cudnn/cudnn_batch_norm-inl.h
  src/operator/nn/cudnn/cudnn_batch_norm.cc
  src/operator/nn/cudnn/cudnn_batch_norm.cu
  src/operator/nn/cudnn/cudnn_batch_norm.h
Labels: pr-awaiting-merge

#20622 [v1.x] Backport #20598
  .github/workflows/license_check.yml
  .licenserc.yaml
  LICENSE
  rat-excludes
  src/operator/contrib/krprod.cc
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
  src/operator/numpy/np_einsum_op-inl.h
  src/operator/numpy/np_einsum_op.cc
  src/operator/numpy/np_einsum_path_op-inl.h
  src/operator/subgraph/tensorrt/nnvm_to_onnx-inl.h
  src/operator/subgraph/tensorrt/onnx_to_tensorrt.h
  src/operator/subgraph/tensorrt/tensorrt-inl.h
  src/operator/subgraph/tensorrt/tensorrt_int8_calibrator.h
Labels: pr-awaiting-review
