Repository apache/mxnet, pull requests merged in 2022-03, with the labels that each got.

#20917 [v1.9.x] Port #19378 from master
  src/engine/naive_engine.cc
  src/engine/threaded_engine_perdevice.cc
Labels: pr-awaiting-review

#20825 [master] Implemented oneDNN Backward Adaptive Pooling kernel
  src/operator/contrib/adaptive_avg_pooling-inl.h
  src/operator/contrib/adaptive_avg_pooling.cc
  src/operator/nn/dnnl/dnnl_pooling-inl.h
  src/operator/nn/dnnl/dnnl_pooling.cc
  src/operator/nn/pooling-inl.h
  src/operator/nn/pooling.cc
  src/operator/quantization/dnnl/dnnl_quantized_pooling.cc
  tests/python/dnnl/test_dnnl.py
Labels: pr-awaiting-review

#20921 [v1.9.x] Port #20482 from v1.x
  CMakeLists.txt
  CONTRIBUTORS.md
  src/operator/operator_common.h
Labels: pr-awaiting-review

#20907 [master] Fix issue with even number of channels in BatchNorm
  src/operator/contrib/batch_norm_relu.cc
  src/operator/nn/batch_norm.cc
  src/operator/nn/dnnl/dnnl_batch_norm-inl.h
Labels: pr-awaiting-review

#20896 [COMMUNITY] add Bartłomiej as committer
  CONTRIBUTORS.md
Labels: pr-awaiting-review

#20902 [v1.9.x] Export attributes of transformer operators
  src/operator/subgraph/mkldnn/mkldnn_transformer_property.h
Labels: pr-awaiting-review

#20862 Add oneDNN support for "where" operator
  src/operator/nn/dnnl/dnnl_ops-inl.h
  src/operator/nn/dnnl/dnnl_where-inl.h
  src/operator/nn/dnnl/dnnl_where.cc
  src/operator/numpy/np_where_forward_op.cc
Labels: pr-awaiting-review

#20908 Remove first_quantization_pass FC property
  src/operator/nn/dnnl/dnnl_fully_connected-inl.h
  src/operator/subgraph/dnnl/dnnl_fc_property.h
  src/operator/subgraph/dnnl/dnnl_fc_sum_fuse.h
Labels: pr-awaiting-review

#20817 quantized transpose operator
  python/mxnet/amp/lists/symbol_fp16.py
  src/operator/nn/dnnl/dnnl_transpose.cc
  src/operator/numpy/np_matrix_op-inl.h
  src/operator/numpy/np_matrix_op.cc
  src/operator/quantization/dnnl/dnnl_quantized_transpose.cc
  src/operator/quantization/quantized_transpose.cc
  tests/python/dnnl/subgraphs/test_conv_subgraph.py
  tests/python/dnnl/subgraphs/test_fc_subgraph.py
  tests/python/quantization/test_quantization.py
Labels: pr-awaiting-review

#20927 [v1.9.x] Fix issue with even number of channels in BatchNorm
  src/operator/contrib/batch_norm_relu.cc
  src/operator/nn/batch_norm.cc
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
Labels: pr-awaiting-review

#20865 [master] 2022.00 MKL' version, update
  ci/docker/Dockerfile.build.ubuntu
Labels: pr-awaiting-testing

#20915 Improve FC + add fusing
  src/operator/nn/mkldnn/mkldnn_fully_connected-inl.h
  src/operator/subgraph/mkldnn/mkldnn_fc_property.h
  src/operator/subgraph/mkldnn/mkldnn_fc_sum_fuse.h
Labels: pr-awaiting-review

#20922 [BUGFIX] Type fix for large tensors
  src/operator/subgraph/dnnl/dnnl_conv.cc
  src/operator/subgraph/dnnl/dnnl_fc.cc
Labels: pr-awaiting-review

#20895 [v1.x] Fix issue with even number of channels in BatchNorm
  src/operator/contrib/batch_norm_relu.cc
  src/operator/nn/batch_norm.cc
  src/operator/nn/mkldnn/mkldnn_batch_norm-inl.h
Labels: pr-awaiting-review

#20941 Avoid modifying loaded library map while iterating in lib_close()
  src/initialize.cc
  src/initialize.h
Labels: pr-awaiting-review

#20923 [v1.9.x] Port #20889 from v1.x
  docs/python_docs/python/tutorials/performance/backend/mkldnn/mkldnn_quantization.md
  example/quantization_inc/BERT_MRPC/bert.yaml
  example/quantization_inc/BERT_MRPC/details.py
  example/quantization_inc/BERT_MRPC/main.py
Labels: pr-awaiting-review

#20943 [v1.x] Port #20941 from master
  src/initialize.cc
  src/initialize.h
Labels: pr-awaiting-review

#20925 [v1.x] Reduce after quantization memory usage
  python/mxnet/contrib/quantization.py
Labels: pr-awaiting-review

#20926 FreeBSD i386 compile fix
  src/operator/quantization/quantized_elemwise_mul.cc
Labels: pr-awaiting-review

#20940 [v1.9.x] [BUGFIX] Upgrade numpy to <1.20.0 to avoid security vulnerabilities affecting numpy<1.19.1
  ci/docker/install/centos7_python.sh
  ci/docker/install/requirements
  ci/docker/install/requirements_aarch64
  ci/docker/install/ubuntu_onnx.sh
  ci/docker/install/ubuntu_publish.sh
  ci/travis/install.sh
  tests/python/unittest/test_numpy_interoperability.py
  tests/python/unittest/test_numpy_op.py
  tests/requirements.txt
Labels: pr-awaiting-review

#20950 Port #20926 to v1.x
  src/operator/quantization/quantized_elemwise_mul.cc
Labels: pr-awaiting-review

#20855 [v1.x] Implemented MKLDNN Backward Adaptive Pooling kernel
  src/operator/contrib/adaptive_avg_pooling-inl.h
  src/operator/contrib/adaptive_avg_pooling.cc
  src/operator/nn/mkldnn/mkldnn_pooling-inl.h
  src/operator/nn/mkldnn/mkldnn_pooling.cc
  src/operator/nn/pooling-inl.h
  src/operator/nn/pooling.cc
  src/operator/quantization/mkldnn/mkldnn_quantized_pooling.cc
  src/operator/quantization/quantized_pooling.cc
  tests/python/mkl/test_mkldnn.py
Labels: pr-awaiting-review

#20955 [v1.x] Port #20940 (Upgrade numpy to <1.20.0) from v1.9.x
  ci/docker/install/centos7_python.sh
  ci/docker/install/requirements
  ci/docker/install/requirements_aarch64
  ci/docker/install/ubuntu_onnx.sh
  ci/docker/install/ubuntu_publish.sh
  ci/travis/install.sh
  tests/python/unittest/test_numpy_interoperability.py
  tests/python/unittest/test_numpy_op.py
  tests/requirements.txt
Labels: pr-awaiting-review

#20957 [v2.0] [BUGFIX] Port #20940 (Upgrade numpy to <1.20.0 ...) from v1.9.x
  ci/docker/install/requirements
  tests/python/unittest/test_numpy_interoperability.py
  tests/python/unittest/test_numpy_op.py
Labels: pr-awaiting-review

#20324 [2.0] [BACKPORT] of [1.x][FEATURE] CUDA graphs support (#19142)
  docs/static_site/src/pages/api/faq/env_var.md
  include/mxnet/op_attr_types.h
  src/imperative/attach_op_execs_pass.cc
  src/imperative/cuda_graphs.h
  src/imperative/exec_pass.h
  src/imperative/imperative_utils.h
  src/operator/contrib/adamw.cu
  src/operator/contrib/index_array.cu
  src/operator/contrib/multi_lamb.cu
  src/operator/instance_norm.cu
  src/operator/leaky_relu.cu
  src/operator/nn/dropout-inl.h
  src/operator/nn/dropout.cu
  src/operator/numpy/linalg/np_eig.cu
  src/operator/numpy/linalg/np_eigvals.cu
  src/operator/numpy/linalg/np_norm_backward.cu
  src/operator/numpy/linalg/np_norm_forward.cu
  src/operator/numpy/np_boolean_mask_assign.cu
  src/operator/numpy/np_constraint_check.cu
  src/operator/numpy/np_matrix_op.cu
  src/operator/numpy/np_nonzero_op.cu
  src/operator/numpy/np_pad_op.cu
  src/operator/numpy/np_percentile_op.cu
  src/operator/numpy/random/np_bernoulli_op.cu
  src/operator/numpy/random/np_exponential_op.cu
  src/operator/numpy/random/np_gamma_op.cu
  src/operator/numpy/random/np_multinomial_op.cu
  src/operator/numpy/random/np_normal_op.cu
  src/operator/numpy/random/np_pareto_op.cu
  src/operator/numpy/random/np_power_op.cu
  src/operator/numpy/random/np_rayleigh_op.cu
  src/operator/numpy/random/np_weibull_op.cu
  src/operator/tensor/elemwise_unary_op_basic.cu
  src/operator/tensor/indexing_op.cu
  src/operator/tensor/la_op.cu
  src/operator/tensor/matrix_op.cu
  tests/python/gpu/test_gluon_gpu.py
Labels: pr-awaiting-review

#20948 [BUGFIX] Rename SetMKLMem func to SetDNNLMem to avoid confusion
  include/mxnet/ndarray.h
  src/ndarray/ndarray.cc
Labels: pr-awaiting-review

#20971 [v1.x][BUGFIX] Fix tests/python/dnnl/subgraphs/test_conv_subgraph.py
  src/operator/nn/mkldnn/mkldnn_convolution.cc
Labels: pr-awaiting-review

#20969 [BUGFIX] Fix subgraph tests
  tests/python/dnnl/subgraphs/subgraph_common.py
Labels: pr-awaiting-review

#20972 [operator] Integrate oneDNN eltwise_tanh into _npi_tanh operator
  src/operator/nn/dnnl/dnnl_base-inl.h
  src/operator/nn/dnnl/dnnl_tanh-inl.h
  src/operator/nn/dnnl/dnnl_tanh.cc
  src/operator/numpy/np_elemwise_unary_op_basic.cc
  src/operator/tensor/elemwise_unary_op.h
Labels: pr-awaiting-review

#20970 [BUGFIX] Fix tests/python/dnnl/subgraphs/test_conv_subgraph.py
  src/operator/nn/dnnl/dnnl_convolution.cc
Labels: pr-awaiting-review

#20961 Enable possibility of disabling particular graph pass
  src/c_api/c_api_symbolic.cc
Labels: pr-awaiting-merge

#20932 [FEATURE] Support bfloat and float mixed input in elemwise broadcast ops.
  src/common/utils.h
  src/operator/mshadow_op.h
  src/operator/mxnet_op.h
  src/operator/nn/dnnl/dnnl_binary.cc
  src/operator/numpy/np_elemwise_broadcast_op.h
  src/operator/numpy/np_true_divide-inl.h
  tests/python/dnnl/test_bf16_operator.py
Labels: pr-awaiting-review

#20981 [FEATURE] Add oneDNN support for npi: exp, square and sqrt
  src/operator/nn/dnnl/dnnl_base-inl.h
  src/operator/nn/dnnl/dnnl_eltwise-inl.h
  src/operator/nn/dnnl/dnnl_eltwise.cc
  src/operator/numpy/np_elemwise_unary_op_basic.cc
  src/operator/tensor/elemwise_binary_broadcast_op.h
  src/operator/tensor/elemwise_unary_op.h
Labels: pr-work-in-progress

#20753 Improve AMP, bf16 support. Support oneDNN ops in AMP
  .github/workflows/os_x_mklbuild.yml
  include/mxnet/c_api.h
  include/mxnet/runtime/packed_func.h
  python/mxnet/amp/amp.py
  python/mxnet/amp/lists/symbol_bf16.py
  python/mxnet/executor.py
  python/mxnet/gluon/block.py
  python/mxnet/gluon/nn/basic_layers.py
  python/mxnet/gluon/parameter.py
  python/mxnet/ndarray/__init__.py
  python/mxnet/ndarray/ndarray.py
  python/mxnet/ndarray/numpy/_op.py
  python/mxnet/ndarray/numpy/random.py
  python/mxnet/ndarray/numpy_extension/_op.py
  python/mxnet/ndarray/register.py
  python/mxnet/ndarray/sparse.py
  python/mxnet/numpy/multiarray.py
  python/mxnet/operator.py
  python/mxnet/rtc.py
  python/mxnet/symbol/register.py
  python/mxnet/symbol/symbol.py
  python/mxnet/test_utils.py
  src/c_api/c_api_symbolic.cc
  src/nnvm/amp_infer_unknown.cc
  src/nnvm/low_precision_pass.cc
  src/operator/nn/dnnl/dnnl_convolution-inl.h
  src/operator/nn/dnnl/dnnl_fully_connected-inl.h
  src/operator/subgraph/dnnl/dnnl_conv.cc
  src/operator/subgraph/dnnl/dnnl_fc.cc
  src/operator/subgraph/dnnl/dnnl_post_amp_property.h
  src/operator/subgraph/dnnl/dnnl_subgraph_property.cc
  src/operator/subgraph/dnnl/dnnl_transformer-inl.h
  src/operator/subgraph/dnnl/dnnl_transformer.cc
  src/operator/tensor/amp_cast.h
  src/serialization/cnpy.cc
  tests/python/dnnl/subgraphs/test_amp_subgraph.py
  tests/python/dnnl/subgraphs/test_matmul_subgraph.py
  tests/python/dnnl/test_amp.py
  tests/python/dnnl/test_bf16_operator.py
  tests/python/gpu/test_amp.py
  tests/python/unittest/test_ndarray.py
Labels: pr-awaiting-review

#20929 Post quantize property improvement
  src/operator/subgraph/dnnl/dnnl_post_quantize_property.h
Labels: pr-awaiting-review
