Repository apache/mxnet, pull requests merged in 2022-04, with the labels that each got.

#20624 [Master] Decouple OneDNN data structures in MXNet C++ API
  include/mxnet/ndarray.h
  src/ndarray/ndarray.cc
  src/operator/nn/dnnl/dnnl_act.cc
  src/operator/nn/dnnl/dnnl_base.cc
  src/operator/nn/dnnl/dnnl_batch_norm-inl.h
  src/operator/nn/dnnl/dnnl_convolution.cc
  src/operator/nn/dnnl/dnnl_copy.cc
  src/operator/nn/dnnl/dnnl_deconvolution-inl.h
  src/operator/nn/dnnl/dnnl_deconvolution.cc
  src/operator/nn/dnnl/dnnl_fully_connected.cc
  src/operator/nn/dnnl/dnnl_layer_norm.cc
  src/operator/nn/dnnl/dnnl_log_softmax.cc
  src/operator/nn/dnnl/dnnl_masked_softmax.cc
  src/operator/nn/dnnl/dnnl_pooling.cc
  src/operator/nn/dnnl/dnnl_reduce.cc
  src/operator/nn/dnnl/dnnl_softmax-inl.h
  src/operator/nn/dnnl/dnnl_softmax.cc
  src/operator/nn/dnnl/dnnl_where.cc
  src/operator/quantization/dnnl/dnnl_quantized_batch_norm.cc
  src/operator/quantization/dnnl/dnnl_quantized_conv.cc
  src/operator/quantization/dnnl/dnnl_quantized_fully_connected.cc
  src/operator/subgraph/dnnl/dnnl_common.h
  src/operator/subgraph/dnnl/dnnl_conv.cc
  src/operator/subgraph/dnnl/dnnl_fc.cc
  tests/cpp/include/test_dnnl.h
  tests/cpp/operator/dnnl_test.cc
Labels: pr-awaiting-review

#20952 Restore quantized RNN to master
  include/mxnet/op_attr_types.h
  python/mxnet/amp/lists/symbol_bf16.py
  python/mxnet/amp/lists/symbol_fp16.py
  python/mxnet/contrib/quantization.py
  python/mxnet/io/io.py
  src/operator/nn/dnnl/dnnl_rnn-inl.h
  src/operator/nn/dnnl/dnnl_rnn.cc
  src/operator/quantization/dnnl/dnnl_quantize_asym-inl.h
  src/operator/quantization/dnnl/dnnl_quantized_rnn-inl.h
  src/operator/quantization/dnnl/dnnl_quantized_rnn.cc
  src/operator/quantization/quantize_asym-inl.h
  src/operator/quantization/quantize_asym.cc
  src/operator/quantization/quantize_graph_pass.cc
  src/operator/quantization/quantize_v2.cc
  src/operator/quantization/quantized_rnn-inl.h
  src/operator/quantization/quantized_rnn.cc
  src/operator/rnn-inl.h
  src/operator/rnn.cc
  tests/python/quantization/test_quantization.py
Labels: pr-awaiting-review

#20993 [v1.9.x] Update website footer to include required Apache links
  docs/static_site/src/_includes/footer.html
  docs/static_site/src/_sass/minima/_layout.scss
  julia/docs/Makefile
Labels: pr-awaiting-review

#20990 [1.x] Fix 'module 'jinja2' has no attribute 'contextfilter''
  julia/docs/Makefile
Labels: pr-awaiting-merge

#20995 [v1.9.x] Fix css for Apache links, add to Python docs.
  ci/jenkins/Jenkins_steps.groovy
  docs/python_docs/themes/mx-theme/mxtheme/footer.html
  docs/python_docs/themes/mx-theme/src/scss/footer/_footer.scss
Labels: pr-awaiting-review

#20998 [v1.9.x] Revert #20916
  src/engine/naive_engine.cc
  src/engine/threaded_engine_perdevice.cc
Labels: pr-awaiting-merge

#21001 Fix CI on master branch
  docs/python_docs/python/tutorials/packages/onnx/fine_tuning_gluon.md
  docs/python_docs/python/tutorials/packages/onnx/inference_on_onnx_model.md
  tests/python/unittest/test_gluon.py
Labels: pr-awaiting-review

#21003 [1.9.x] Update version for 1.9.1 release
  R-package/DESCRIPTION
  contrib/clojure-package/examples/bert/project.clj
  contrib/clojure-package/examples/captcha/project.clj
  contrib/clojure-package/examples/cnn-text-classification/project.clj
  contrib/clojure-package/examples/gan/project.clj
  contrib/clojure-package/examples/imclassification/project.clj
  contrib/clojure-package/examples/infer/imageclassifier/project.clj
  contrib/clojure-package/examples/infer/objectdetector/project.clj
  contrib/clojure-package/examples/infer/predictor/project.clj
  contrib/clojure-package/examples/module/project.clj
  contrib/clojure-package/examples/multi-label/project.clj
  contrib/clojure-package/examples/neural-style/project.clj
  contrib/clojure-package/examples/pre-trained-models/project.clj
  contrib/clojure-package/examples/profiler/project.clj
  contrib/clojure-package/examples/rnn/project.clj
  contrib/clojure-package/examples/tutorial/project.clj
  contrib/clojure-package/examples/visualization/project.clj
  contrib/clojure-package/project.clj
  docs/static_site/src/pages/api/scala/docs/tutorials/mxnet_scala_on_intellij.md
  include/mxnet/base.h
  python/mxnet/libinfo.py
  scala-package/README.md
  scala-package/mxnet-demo/java-demo/README.md
  scala-package/mxnet-demo/java-demo/pom.xml
  scala-package/mxnet-demo/scala-demo/pom.xml
  scala-package/pom.xml
  snapcraft.yaml
Labels: pr-awaiting-review

#20904 [FEATURE] Integrate oneDNN support for scalar power() operator
  src/operator/nn/dnnl/dnnl_base-inl.h
  src/operator/nn/dnnl/dnnl_ops-inl.h
  src/operator/nn/dnnl/dnnl_power_scalar-inl.h
  src/operator/nn/dnnl/dnnl_power_scalar.cc
  src/operator/numpy/np_elemwise_broadcast_op_scalar.cc
  src/operator/tensor/elemwise_binary_scalar_op.h
  src/operator/tensor/elemwise_binary_scalar_op_extended.cc
Labels: pr-awaiting-review

#20999 [BUGFIX] Fix and cleanup _contrib_quantized_elemwise_add
  src/operator/operator_common.h
  src/operator/quantization/dnnl/dnnl_quantized_elemwise_add.cc
  src/operator/quantization/quantized_elemwise_add-inl.h
  tests/python/quantization/test_quantization.py
Labels: pr-awaiting-merge

#20987 [master] Unified oneDNN implementation calls for quantized operators
  src/operator/nn/dnnl/dnnl_base-inl.h
  src/operator/quantization/dnnl/dnnl_quantize-inl.h
  src/operator/quantization/quantize.cc
  src/operator/quantization/quantized_fully_connected.cc
  src/operator/quantization/requantize.cc
Labels: pr-awaiting-response

#20974 [BUGFIX] Fix bitwise_right_shift with uint input
  src/operator/mshadow_op.h
Labels: pr-awaiting-review

#21009 [BUGFIX] Fix medium blog integration.
  docs/static_site/Makefile
  docs/static_site/src/_includes/head.html
  docs/static_site/src/_layouts/home.html
  docs/static_site/src/_sass/minima/_blog.scss
  docs/static_site/src/pages/blog.html
Labels: pr-awaiting-merge
